// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::account_config_type::AccountConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `account_configs`.
///
/// Obtain a handle from the [`AccountConfigsTableAccess::account_configs`] method on [`super::RemoteTables`],
/// like `ctx.db.account_configs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.account_configs().on_insert(...)`.
pub struct AccountConfigsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AccountConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `account_configs`.
pub struct AccountConfigsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AccountConfigsTableAccessor {
    type Row = AccountConfig;
    type Handle<'db> = AccountConfigsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.account_configs()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `account_configs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AccountConfigsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AccountConfigsTableHandle`], which mediates access to the table `account_configs`.
    fn account_configs(&self) -> AccountConfigsTableHandle<'_>;
}

impl AccountConfigsTableAccess for super::RemoteTables {
    fn account_configs(&self) -> AccountConfigsTableHandle<'_> {
        AccountConfigsTableHandle {
            imp: self.imp.get_table::<AccountConfig>("account_configs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AccountConfigsInsertCallbackId(__sdk::CallbackId);
pub struct AccountConfigsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AccountConfigsTableHandle<'ctx> {
    type Row = AccountConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountConfig> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AccountConfigsTableHandle<'ctx> {
    type Row = AccountConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AccountConfigsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountConfigsInsertCallbackId {
        AccountConfigsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AccountConfigsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AccountConfigsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountConfigsDeleteCallbackId {
        AccountConfigsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AccountConfigsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AccountConfigsTableHandle<'ctx> {
    type InsertCallbackId = AccountConfigsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountConfigsInsertCallbackId {
        AccountConfigsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AccountConfigsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AccountConfigsTableHandle<'ctx> {
    type DeleteCallbackId = AccountConfigsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AccountConfigsDeleteCallbackId {
        AccountConfigsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AccountConfigsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AccountConfigsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AccountConfigsTableHandle<'ctx> {
    type UpdateCallbackId = AccountConfigsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AccountConfigsUpdateCallbackId {
        AccountConfigsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AccountConfigsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AccountConfigsTableHandle<'ctx> {
    type UpdateCallbackId = AccountConfigsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AccountConfigsUpdateCallbackId {
        AccountConfigsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AccountConfigsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `account_id` unique index on the table `account_configs`,
/// which allows point queries on the field of the same name
/// via the [`AccountConfigsAccountIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.account_configs().account_id().find(...)`.
pub struct AccountConfigsAccountIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AccountConfig, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AccountConfigsTableHandle<'ctx> {
    /// Get a handle on the `account_id` unique index on the table `account_configs`.
    pub fn account_id(&self) -> AccountConfigsAccountIdUnique<'ctx> {
        AccountConfigsAccountIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("account_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AccountConfigsAccountIdUnique<'ctx> {
    /// Find the subscribed row whose `account_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<AccountConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AccountConfig>("account_configs");
    _table.add_unique_constraint::<u64>("account_id", |row| &row.account_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AccountConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AccountConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AccountConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait account_configsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AccountConfig`.
    fn account_configs(&self) -> __sdk::__query_builder::Table<AccountConfig>;
}

impl account_configsQueryTableAccess for __sdk::QueryTableAccessor {
    fn account_configs(&self) -> __sdk::__query_builder::Table<AccountConfig> {
        __sdk::__query_builder::Table::new("account_configs")
    }
}
