// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::stalwart_config_type::StalwartConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `admin_stalwart_config`.
///
/// Obtain a handle from the [`AdminStalwartConfigTableAccess::admin_stalwart_config`] method on [`super::RemoteTables`],
/// like `ctx.db.admin_stalwart_config()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.admin_stalwart_config().on_insert(...)`.
pub struct AdminStalwartConfigTableHandle<'ctx> {
    imp: __sdk::TableHandle<StalwartConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `admin_stalwart_config`.
pub struct AdminStalwartConfigTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for AdminStalwartConfigTableAccessor {
    type Row = StalwartConfig;
    type Handle<'db> = AdminStalwartConfigTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.admin_stalwart_config()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `admin_stalwart_config`.
///
/// Implemented for [`super::RemoteTables`].
pub trait AdminStalwartConfigTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`AdminStalwartConfigTableHandle`], which mediates access to the table `admin_stalwart_config`.
    fn admin_stalwart_config(&self) -> AdminStalwartConfigTableHandle<'_>;
}

impl AdminStalwartConfigTableAccess for super::RemoteTables {
    fn admin_stalwart_config(&self) -> AdminStalwartConfigTableHandle<'_> {
        AdminStalwartConfigTableHandle {
            imp: self
                .imp
                .get_table::<StalwartConfig>("admin_stalwart_config"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct AdminStalwartConfigInsertCallbackId(__sdk::CallbackId);
pub struct AdminStalwartConfigDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for AdminStalwartConfigTableHandle<'ctx> {
    type Row = StalwartConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StalwartConfig> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for AdminStalwartConfigTableHandle<'ctx> {
    type Row = StalwartConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = StalwartConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = AdminStalwartConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminStalwartConfigInsertCallbackId {
        AdminStalwartConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdminStalwartConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = AdminStalwartConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminStalwartConfigDeleteCallbackId {
        AdminStalwartConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdminStalwartConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for AdminStalwartConfigTableHandle<'ctx> {
    type InsertCallbackId = AdminStalwartConfigInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminStalwartConfigInsertCallbackId {
        AdminStalwartConfigInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: AdminStalwartConfigInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for AdminStalwartConfigTableHandle<'ctx> {
    type DeleteCallbackId = AdminStalwartConfigDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> AdminStalwartConfigDeleteCallbackId {
        AdminStalwartConfigDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: AdminStalwartConfigDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct AdminStalwartConfigUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for AdminStalwartConfigTableHandle<'ctx> {
    type UpdateCallbackId = AdminStalwartConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AdminStalwartConfigUpdateCallbackId {
        AdminStalwartConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AdminStalwartConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for AdminStalwartConfigTableHandle<'ctx> {
    type UpdateCallbackId = AdminStalwartConfigUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> AdminStalwartConfigUpdateCallbackId {
        AdminStalwartConfigUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: AdminStalwartConfigUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `admin_stalwart_config`,
/// which allows point queries on the field of the same name
/// via the [`AdminStalwartConfigIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.admin_stalwart_config().id().find(...)`.
pub struct AdminStalwartConfigIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<StalwartConfig, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> AdminStalwartConfigTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `admin_stalwart_config`.
    pub fn id(&self) -> AdminStalwartConfigIdUnique<'ctx> {
        AdminStalwartConfigIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> AdminStalwartConfigIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<StalwartConfig> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<StalwartConfig>("admin_stalwart_config");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<StalwartConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<StalwartConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `StalwartConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait admin_stalwart_configQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `StalwartConfig`.
    fn admin_stalwart_config(&self) -> __sdk::__query_builder::Table<StalwartConfig>;
}

impl admin_stalwart_configQueryTableAccess for __sdk::QueryTableAccessor {
    fn admin_stalwart_config(&self) -> __sdk::__query_builder::Table<StalwartConfig> {
        __sdk::__query_builder::Table::new("admin_stalwart_config")
    }
}
