// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearCategoryProvisioningLockArgs {
    pub category_id: u64,
}

impl From<ClearCategoryProvisioningLockArgs> for super::Reducer {
    fn from(args: ClearCategoryProvisioningLockArgs) -> Self {
        Self::ClearCategoryProvisioningLock {
            category_id: args.category_id,
        }
    }
}

impl __sdk::InModule for ClearCategoryProvisioningLockArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_category_provisioning_lock`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_category_provisioning_lock {
    /// Request that the remote module invoke the reducer `clear_category_provisioning_lock` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`clear_category_provisioning_lock:clear_category_provisioning_lock_then`] to run a callback after the reducer completes.
    fn clear_category_provisioning_lock(&self, category_id: u64) -> __sdk::Result<()> {
        self.clear_category_provisioning_lock_then(category_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `clear_category_provisioning_lock` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn clear_category_provisioning_lock_then(
        &self,
        category_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl clear_category_provisioning_lock for super::RemoteReducers {
    fn clear_category_provisioning_lock_then(
        &self,
        category_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            ClearCategoryProvisioningLockArgs { category_id },
            callback,
        )
    }
}
