// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnqueueMailDeliveryArgs {
    pub ingress_id: String,
    pub subscription_id: u64,
    pub recipient_email: String,
    pub recipient_account_id: Option<u64>,
    pub list_email: String,
    pub list_name: String,
    pub original_sender_email: String,
    pub from_header: String,
    pub reply_to: String,
    pub subject: String,
    pub body_raw: String,
    pub headers_raw: String,
    pub raw_message: String,
    pub unsubscribe_token: String,
}

impl From<EnqueueMailDeliveryArgs> for super::Reducer {
    fn from(args: EnqueueMailDeliveryArgs) -> Self {
        Self::EnqueueMailDelivery {
            ingress_id: args.ingress_id,
            subscription_id: args.subscription_id,
            recipient_email: args.recipient_email,
            recipient_account_id: args.recipient_account_id,
            list_email: args.list_email,
            list_name: args.list_name,
            original_sender_email: args.original_sender_email,
            from_header: args.from_header,
            reply_to: args.reply_to,
            subject: args.subject,
            body_raw: args.body_raw,
            headers_raw: args.headers_raw,
            raw_message: args.raw_message,
            unsubscribe_token: args.unsubscribe_token,
        }
    }
}

impl __sdk::InModule for EnqueueMailDeliveryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `enqueue_mail_delivery`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait enqueue_mail_delivery {
    /// Request that the remote module invoke the reducer `enqueue_mail_delivery` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`enqueue_mail_delivery:enqueue_mail_delivery_then`] to run a callback after the reducer completes.
    fn enqueue_mail_delivery(
        &self,
        ingress_id: String,
        subscription_id: u64,
        recipient_email: String,
        recipient_account_id: Option<u64>,
        list_email: String,
        list_name: String,
        original_sender_email: String,
        from_header: String,
        reply_to: String,
        subject: String,
        body_raw: String,
        headers_raw: String,
        raw_message: String,
        unsubscribe_token: String,
    ) -> __sdk::Result<()> {
        self.enqueue_mail_delivery_then(
            ingress_id,
            subscription_id,
            recipient_email,
            recipient_account_id,
            list_email,
            list_name,
            original_sender_email,
            from_header,
            reply_to,
            subject,
            body_raw,
            headers_raw,
            raw_message,
            unsubscribe_token,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `enqueue_mail_delivery` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn enqueue_mail_delivery_then(
        &self,
        ingress_id: String,
        subscription_id: u64,
        recipient_email: String,
        recipient_account_id: Option<u64>,
        list_email: String,
        list_name: String,
        original_sender_email: String,
        from_header: String,
        reply_to: String,
        subject: String,
        body_raw: String,
        headers_raw: String,
        raw_message: String,
        unsubscribe_token: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl enqueue_mail_delivery for super::RemoteReducers {
    fn enqueue_mail_delivery_then(
        &self,
        ingress_id: String,
        subscription_id: u64,
        recipient_email: String,
        recipient_account_id: Option<u64>,
        list_email: String,
        list_name: String,
        original_sender_email: String,
        from_header: String,
        reply_to: String,
        subject: String,
        body_raw: String,
        headers_raw: String,
        raw_message: String,
        unsubscribe_token: String,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EnqueueMailDeliveryArgs {
                ingress_id,
                subscription_id,
                recipient_email,
                recipient_account_id,
                list_email,
                list_name,
                original_sender_email,
                from_header,
                reply_to,
                subject,
                body_raw,
                headers_raw,
                raw_message,
                unsubscribe_token,
            },
            callback,
        )
    }
}
