// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct EnsureSubscriptionUnsubscribeTokenArgs {
    pub subscription_id: u64,
}

impl From<EnsureSubscriptionUnsubscribeTokenArgs> for super::Reducer {
    fn from(args: EnsureSubscriptionUnsubscribeTokenArgs) -> Self {
        Self::EnsureSubscriptionUnsubscribeToken {
            subscription_id: args.subscription_id,
        }
    }
}

impl __sdk::InModule for EnsureSubscriptionUnsubscribeTokenArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `ensure_subscription_unsubscribe_token`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait ensure_subscription_unsubscribe_token {
    /// Request that the remote module invoke the reducer `ensure_subscription_unsubscribe_token` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`ensure_subscription_unsubscribe_token:ensure_subscription_unsubscribe_token_then`] to run a callback after the reducer completes.
    fn ensure_subscription_unsubscribe_token(&self, subscription_id: u64) -> __sdk::Result<()> {
        self.ensure_subscription_unsubscribe_token_then(subscription_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `ensure_subscription_unsubscribe_token` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn ensure_subscription_unsubscribe_token_then(
        &self,
        subscription_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl ensure_subscription_unsubscribe_token for super::RemoteReducers {
    fn ensure_subscription_unsubscribe_token_then(
        &self,
        subscription_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            EnsureSubscriptionUnsubscribeTokenArgs { subscription_id },
            callback,
        )
    }
}
