// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mail_delivery_row_type::MailDeliveryRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MailDeliveryTemporaryFailed {
    pub id: String,
    pub next_attempt_at: __sdk::Timestamp,
    pub fail_reason: String,
    pub row: MailDeliveryRow,
}

impl __sdk::InModule for MailDeliveryTemporaryFailed {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MailDeliveryTemporaryFailed`.
///
/// Provides typed access to columns for query building.
pub struct MailDeliveryTemporaryFailedCols {
    pub id: __sdk::__query_builder::Col<MailDeliveryTemporaryFailed, String>,
    pub next_attempt_at: __sdk::__query_builder::Col<MailDeliveryTemporaryFailed, __sdk::Timestamp>,
    pub fail_reason: __sdk::__query_builder::Col<MailDeliveryTemporaryFailed, String>,
    pub row: __sdk::__query_builder::Col<MailDeliveryTemporaryFailed, MailDeliveryRow>,
}

impl __sdk::__query_builder::HasCols for MailDeliveryTemporaryFailed {
    type Cols = MailDeliveryTemporaryFailedCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MailDeliveryTemporaryFailedCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            next_attempt_at: __sdk::__query_builder::Col::new(table_name, "next_attempt_at"),
            fail_reason: __sdk::__query_builder::Col::new(table_name, "fail_reason"),
            row: __sdk::__query_builder::Col::new(table_name, "row"),
        }
    }
}

/// Indexed column accessor struct for the table `MailDeliveryTemporaryFailed`.
///
/// Provides typed access to indexed columns for query building.
pub struct MailDeliveryTemporaryFailedIxCols {
    pub id: __sdk::__query_builder::IxCol<MailDeliveryTemporaryFailed, String>,
    pub next_attempt_at:
        __sdk::__query_builder::IxCol<MailDeliveryTemporaryFailed, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasIxCols for MailDeliveryTemporaryFailed {
    type IxCols = MailDeliveryTemporaryFailedIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MailDeliveryTemporaryFailedIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            next_attempt_at: __sdk::__query_builder::IxCol::new(table_name, "next_attempt_at"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MailDeliveryTemporaryFailed {}
