// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mail_delivery_row_type::MailDeliveryRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MailDeliveryDone {
    pub id: String,
    pub ingress_id: String,
    pub final_state: String,
    pub row: MailDeliveryRow,
}

impl __sdk::InModule for MailDeliveryDone {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MailDeliveryDone`.
///
/// Provides typed access to columns for query building.
pub struct MailDeliveryDoneCols {
    pub id: __sdk::__query_builder::Col<MailDeliveryDone, String>,
    pub ingress_id: __sdk::__query_builder::Col<MailDeliveryDone, String>,
    pub final_state: __sdk::__query_builder::Col<MailDeliveryDone, String>,
    pub row: __sdk::__query_builder::Col<MailDeliveryDone, MailDeliveryRow>,
}

impl __sdk::__query_builder::HasCols for MailDeliveryDone {
    type Cols = MailDeliveryDoneCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MailDeliveryDoneCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ingress_id: __sdk::__query_builder::Col::new(table_name, "ingress_id"),
            final_state: __sdk::__query_builder::Col::new(table_name, "final_state"),
            row: __sdk::__query_builder::Col::new(table_name, "row"),
        }
    }
}

/// Indexed column accessor struct for the table `MailDeliveryDone`.
///
/// Provides typed access to indexed columns for query building.
pub struct MailDeliveryDoneIxCols {
    pub id: __sdk::__query_builder::IxCol<MailDeliveryDone, String>,
    pub ingress_id: __sdk::__query_builder::IxCol<MailDeliveryDone, String>,
}

impl __sdk::__query_builder::HasIxCols for MailDeliveryDone {
    type IxCols = MailDeliveryDoneIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MailDeliveryDoneIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            ingress_id: __sdk::__query_builder::IxCol::new(table_name, "ingress_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MailDeliveryDone {}
