// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mail_delivery_row_type::MailDeliveryRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MailDeliveryPending {
    pub id: String,
    pub ingress_id: String,
    pub next_attempt_at: __sdk::Timestamp,
    pub row: MailDeliveryRow,
}

impl __sdk::InModule for MailDeliveryPending {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MailDeliveryPending`.
///
/// Provides typed access to columns for query building.
pub struct MailDeliveryPendingCols {
    pub id: __sdk::__query_builder::Col<MailDeliveryPending, String>,
    pub ingress_id: __sdk::__query_builder::Col<MailDeliveryPending, String>,
    pub next_attempt_at: __sdk::__query_builder::Col<MailDeliveryPending, __sdk::Timestamp>,
    pub row: __sdk::__query_builder::Col<MailDeliveryPending, MailDeliveryRow>,
}

impl __sdk::__query_builder::HasCols for MailDeliveryPending {
    type Cols = MailDeliveryPendingCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MailDeliveryPendingCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            ingress_id: __sdk::__query_builder::Col::new(table_name, "ingress_id"),
            next_attempt_at: __sdk::__query_builder::Col::new(table_name, "next_attempt_at"),
            row: __sdk::__query_builder::Col::new(table_name, "row"),
        }
    }
}

/// Indexed column accessor struct for the table `MailDeliveryPending`.
///
/// Provides typed access to indexed columns for query building.
pub struct MailDeliveryPendingIxCols {
    pub id: __sdk::__query_builder::IxCol<MailDeliveryPending, String>,
    pub ingress_id: __sdk::__query_builder::IxCol<MailDeliveryPending, String>,
    pub next_attempt_at: __sdk::__query_builder::IxCol<MailDeliveryPending, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasIxCols for MailDeliveryPending {
    type IxCols = MailDeliveryPendingIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MailDeliveryPendingIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            ingress_id: __sdk::__query_builder::IxCol::new(table_name, "ingress_id"),
            next_attempt_at: __sdk::__query_builder::IxCol::new(table_name, "next_attempt_at"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MailDeliveryPending {}
