// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::mail_delivery_row_type::MailDeliveryRow;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MailDeliveryClaimed {
    pub id: String,
    pub worker: __sdk::Identity,
    pub instance_id: String,
    pub lease_expires_at: __sdk::Timestamp,
    pub row: MailDeliveryRow,
}

impl __sdk::InModule for MailDeliveryClaimed {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MailDeliveryClaimed`.
///
/// Provides typed access to columns for query building.
pub struct MailDeliveryClaimedCols {
    pub id: __sdk::__query_builder::Col<MailDeliveryClaimed, String>,
    pub worker: __sdk::__query_builder::Col<MailDeliveryClaimed, __sdk::Identity>,
    pub instance_id: __sdk::__query_builder::Col<MailDeliveryClaimed, String>,
    pub lease_expires_at: __sdk::__query_builder::Col<MailDeliveryClaimed, __sdk::Timestamp>,
    pub row: __sdk::__query_builder::Col<MailDeliveryClaimed, MailDeliveryRow>,
}

impl __sdk::__query_builder::HasCols for MailDeliveryClaimed {
    type Cols = MailDeliveryClaimedCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MailDeliveryClaimedCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            worker: __sdk::__query_builder::Col::new(table_name, "worker"),
            instance_id: __sdk::__query_builder::Col::new(table_name, "instance_id"),
            lease_expires_at: __sdk::__query_builder::Col::new(table_name, "lease_expires_at"),
            row: __sdk::__query_builder::Col::new(table_name, "row"),
        }
    }
}

/// Indexed column accessor struct for the table `MailDeliveryClaimed`.
///
/// Provides typed access to indexed columns for query building.
pub struct MailDeliveryClaimedIxCols {
    pub id: __sdk::__query_builder::IxCol<MailDeliveryClaimed, String>,
    pub lease_expires_at: __sdk::__query_builder::IxCol<MailDeliveryClaimed, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasIxCols for MailDeliveryClaimed {
    type IxCols = MailDeliveryClaimedIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MailDeliveryClaimedIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            lease_expires_at: __sdk::__query_builder::IxCol::new(table_name, "lease_expires_at"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MailDeliveryClaimed {}
