// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::category_visibility_type::CategoryVisibility;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MessageCategory {
    pub id: u64,
    pub name: String,
    pub email_address: String,
    pub description: String,
    pub active: bool,
    pub visibility: CategoryVisibility,
}

impl __sdk::InModule for MessageCategory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MessageCategory`.
///
/// Provides typed access to columns for query building.
pub struct MessageCategoryCols {
    pub id: __sdk::__query_builder::Col<MessageCategory, u64>,
    pub name: __sdk::__query_builder::Col<MessageCategory, String>,
    pub email_address: __sdk::__query_builder::Col<MessageCategory, String>,
    pub description: __sdk::__query_builder::Col<MessageCategory, String>,
    pub active: __sdk::__query_builder::Col<MessageCategory, bool>,
    pub visibility: __sdk::__query_builder::Col<MessageCategory, CategoryVisibility>,
}

impl __sdk::__query_builder::HasCols for MessageCategory {
    type Cols = MessageCategoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageCategoryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            email_address: __sdk::__query_builder::Col::new(table_name, "email_address"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            visibility: __sdk::__query_builder::Col::new(table_name, "visibility"),
        }
    }
}

/// Indexed column accessor struct for the table `MessageCategory`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageCategoryIxCols {
    pub email_address: __sdk::__query_builder::IxCol<MessageCategory, String>,
    pub id: __sdk::__query_builder::IxCol<MessageCategory, u64>,
    pub visibility: __sdk::__query_builder::IxCol<MessageCategory, CategoryVisibility>,
}

impl __sdk::__query_builder::HasIxCols for MessageCategory {
    type IxCols = MessageCategoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageCategoryIxCols {
            email_address: __sdk::__query_builder::IxCol::new(table_name, "email_address"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            visibility: __sdk::__query_builder::IxCol::new(table_name, "visibility"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MessageCategory {}
