// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit 73145eb5edc0e8f29cf67afc35a274ab307e0f1c).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

pub mod account_type;
pub mod active_subscriptions_table;
pub mod active_unsubscribe_tokens_table;
pub mod add_and_subscribe_category_reducer;
pub mod add_message_category_reducer;
pub mod add_subscription_reducer;
pub mod admin_add_subscription_reducer;
pub mod admin_identity_type;
pub mod admin_stalwart_config_table;
pub mod blocked_ip_type;
pub mod cancel_mail_delivery_retry_reducer;
pub mod category_app_password_type;
pub mod category_visibility_type;
pub mod claim_next_mail_delivery_reducer;
pub mod claim_next_mail_ingress_reducer;
pub mod claim_state_type;
pub mod complete_mail_ingress_reducer;
pub mod create_webhook_token_reducer;
pub mod delivery_final_state_type;
pub mod delivery_status_type;
pub mod domain_type;
pub mod dump_mta_logs_to_server_logs_reducer;
pub mod enqueue_mail_delivery_reducer;
pub mod ensure_subscription_unsubscribe_token_reducer;
pub mod expire_stale_delivery_claims_schedule_table;
pub mod expire_stale_delivery_claims_schedule_type;
pub mod fail_mail_delivery_reducer;
pub mod fail_mail_ingress_reducer;
pub mod increment_mail_ingress_delivery_count_reducer;
pub mod increment_mail_ingress_failed_delivery_count_reducer;
pub mod mail_delivery_claimed_type;
pub mod mail_delivery_done_type;
pub mod mail_delivery_event_type;
pub mod mail_delivery_message_type;
pub mod mail_delivery_pending_type;
pub mod mail_delivery_temporary_failed_type;
pub mod mail_ingress_type;
pub mod mail_message_type;
pub mod mark_mail_delivery_bounced_reducer;
pub mod mark_mail_delivery_sent_reducer;
pub mod message_category_topic_type;
pub mod message_category_type;
pub mod mta_connection_log_type;
pub mod mta_message_log_type;
pub mod provision_message_category_procedure;
pub mod received_message_type;
pub mod register_admin_identity_reducer;
pub mod remove_message_category_reducer;
pub mod remove_subscription_reducer;
pub mod rename_topic_reducer;
pub mod requeue_temporary_failed_mails_schedule_table;
pub mod requeue_temporary_failed_mails_schedule_type;
pub mod retry_mail_ingress_reducer;
pub mod revoke_webhook_token_reducer;
pub mod schedule_mail_delivery_retry_reducer;
pub mod sender_mail_delivery_claimed_table;
pub mod sender_mail_delivery_done_table;
pub mod sender_mail_delivery_events_table;
pub mod sender_mail_delivery_messages_table;
pub mod sender_mail_delivery_pending_table;
pub mod sender_mail_delivery_temporary_failed_table;
pub mod sender_mail_ingress_table;
pub mod sender_mail_messages_table;
pub mod set_category_topics_reducer;
pub mod set_stalwart_config_reducer;
pub mod stalwart_config_type;
pub mod subscription_status_type;
pub mod subscription_type;
pub mod subscription_unsubscribe_token_type;
pub mod sync_domains_result_type;
pub mod sync_stalwart_domains_procedure;
pub mod sync_user_reducer;
pub mod topic_type;
pub mod unregister_admin_identity_reducer;
pub mod update_message_category_reducer;
pub mod visible_accounts_table;
pub mod visible_admin_identities_table;
pub mod visible_category_app_passwords_table;
pub mod visible_domains_table;
pub mod visible_message_categories_table;
pub mod visible_message_category_topics_table;
pub mod visible_messages_table;
pub mod visible_subscriptions_table;
pub mod visible_topics_table;
pub mod visible_webhook_tokens_table;
pub mod webhook_token_type;

pub use account_type::Account;
pub use active_subscriptions_table::*;
pub use active_unsubscribe_tokens_table::*;
pub use add_and_subscribe_category_reducer::add_and_subscribe_category;
pub use add_message_category_reducer::add_message_category;
pub use add_subscription_reducer::add_subscription;
pub use admin_add_subscription_reducer::admin_add_subscription;
pub use admin_identity_type::AdminIdentity;
pub use admin_stalwart_config_table::*;
pub use blocked_ip_type::BlockedIp;
pub use cancel_mail_delivery_retry_reducer::cancel_mail_delivery_retry;
pub use category_app_password_type::CategoryAppPassword;
pub use category_visibility_type::CategoryVisibility;
pub use claim_next_mail_delivery_reducer::claim_next_mail_delivery;
pub use claim_next_mail_ingress_reducer::claim_next_mail_ingress;
pub use claim_state_type::ClaimState;
pub use complete_mail_ingress_reducer::complete_mail_ingress;
pub use create_webhook_token_reducer::create_webhook_token;
pub use delivery_final_state_type::DeliveryFinalState;
pub use delivery_status_type::DeliveryStatus;
pub use domain_type::Domain;
pub use dump_mta_logs_to_server_logs_reducer::dump_mta_logs_to_server_logs;
pub use enqueue_mail_delivery_reducer::enqueue_mail_delivery;
pub use ensure_subscription_unsubscribe_token_reducer::ensure_subscription_unsubscribe_token;
pub use expire_stale_delivery_claims_schedule_table::*;
pub use expire_stale_delivery_claims_schedule_type::ExpireStaleDeliveryClaimsSchedule;
pub use fail_mail_delivery_reducer::fail_mail_delivery;
pub use fail_mail_ingress_reducer::fail_mail_ingress;
pub use increment_mail_ingress_delivery_count_reducer::increment_mail_ingress_delivery_count;
pub use increment_mail_ingress_failed_delivery_count_reducer::increment_mail_ingress_failed_delivery_count;
pub use mail_delivery_claimed_type::MailDeliveryClaimed;
pub use mail_delivery_done_type::MailDeliveryDone;
pub use mail_delivery_event_type::MailDeliveryEvent;
pub use mail_delivery_message_type::MailDeliveryMessage;
pub use mail_delivery_pending_type::MailDeliveryPending;
pub use mail_delivery_temporary_failed_type::MailDeliveryTemporaryFailed;
pub use mail_ingress_type::MailIngress;
pub use mail_message_type::MailMessage;
pub use mark_mail_delivery_bounced_reducer::mark_mail_delivery_bounced;
pub use mark_mail_delivery_sent_reducer::mark_mail_delivery_sent;
pub use message_category_topic_type::MessageCategoryTopic;
pub use message_category_type::MessageCategory;
pub use mta_connection_log_type::MtaConnectionLog;
pub use mta_message_log_type::MtaMessageLog;
pub use provision_message_category_procedure::provision_message_category;
pub use received_message_type::ReceivedMessage;
pub use register_admin_identity_reducer::register_admin_identity;
pub use remove_message_category_reducer::remove_message_category;
pub use remove_subscription_reducer::remove_subscription;
pub use rename_topic_reducer::rename_topic;
pub use requeue_temporary_failed_mails_schedule_table::*;
pub use requeue_temporary_failed_mails_schedule_type::RequeueTemporaryFailedMailsSchedule;
pub use retry_mail_ingress_reducer::retry_mail_ingress;
pub use revoke_webhook_token_reducer::revoke_webhook_token;
pub use schedule_mail_delivery_retry_reducer::schedule_mail_delivery_retry;
pub use sender_mail_delivery_claimed_table::*;
pub use sender_mail_delivery_done_table::*;
pub use sender_mail_delivery_events_table::*;
pub use sender_mail_delivery_messages_table::*;
pub use sender_mail_delivery_pending_table::*;
pub use sender_mail_delivery_temporary_failed_table::*;
pub use sender_mail_ingress_table::*;
pub use sender_mail_messages_table::*;
pub use set_category_topics_reducer::set_category_topics;
pub use set_stalwart_config_reducer::set_stalwart_config;
pub use stalwart_config_type::StalwartConfig;
pub use subscription_status_type::SubscriptionStatus;
pub use subscription_type::Subscription;
pub use subscription_unsubscribe_token_type::SubscriptionUnsubscribeToken;
pub use sync_domains_result_type::SyncDomainsResult;
pub use sync_stalwart_domains_procedure::sync_stalwart_domains;
pub use sync_user_reducer::sync_user;
pub use topic_type::Topic;
pub use unregister_admin_identity_reducer::unregister_admin_identity;
pub use update_message_category_reducer::update_message_category;
pub use visible_accounts_table::*;
pub use visible_admin_identities_table::*;
pub use visible_category_app_passwords_table::*;
pub use visible_domains_table::*;
pub use visible_message_categories_table::*;
pub use visible_message_category_topics_table::*;
pub use visible_messages_table::*;
pub use visible_subscriptions_table::*;
pub use visible_topics_table::*;
pub use visible_webhook_tokens_table::*;
pub use webhook_token_type::WebhookToken;

#[derive(Clone, PartialEq, Debug)]

/// One of the reducers defined by this module.
///
/// Contained within a [`__sdk::ReducerEvent`] in [`EventContext`]s for reducer events
/// to indicate which reducer caused the event.

pub enum Reducer {
    AddAndSubscribeCategory {
        subscriber_account_id: u64,
        subscriber_email: String,
        name: String,
        email_address: String,
        description: String,
        visibility: CategoryVisibility,
    },
    AddMessageCategory {
        name: String,
        email_address: String,
        description: String,
        visibility: CategoryVisibility,
    },
    AddSubscription {
        subscriber_account_id: u64,
        subscriber_email: String,
        category_id: u64,
    },
    AdminAddSubscription {
        subscriber_account_id: u64,
        subscriber_email: String,
        category_id: u64,
        status: SubscriptionStatus,
    },
    CancelMailDeliveryRetry {
        delivery_id: String,
    },
    ClaimNextMailDelivery {
        instance_id: String,
    },
    ClaimNextMailIngress {
        instance_id: String,
    },
    CompleteMailIngress {
        ingress_id: String,
        instance_id: String,
    },
    CreateWebhookToken {
        token_hash: String,
        label: String,
        permissions: Vec<String>,
    },
    DumpMtaLogsToServerLogs,
    EnqueueMailDelivery {
        ingress_id: String,
        subscription_id: u64,
        recipient_email: String,
        recipient_account_id: Option<u64>,
        from_header: String,
        reply_to: String,
        raw_message: String,
    },
    EnsureSubscriptionUnsubscribeToken {
        subscription_id: u64,
    },
    FailMailDelivery {
        delivery_id: String,
        instance_id: String,
        smtp_status_code: Option<u16>,
        smtp_response: String,
        error_kind: String,
    },
    FailMailIngress {
        ingress_id: String,
        instance_id: String,
        error: String,
    },
    IncrementMailIngressDeliveryCount {
        ingress_id: String,
        instance_id: String,
    },
    IncrementMailIngressFailedDeliveryCount {
        ingress_id: String,
        instance_id: String,
    },
    MarkMailDeliveryBounced {
        delivery_id: String,
        instance_id: String,
        smtp_status_code: Option<u16>,
        smtp_response: String,
        error_kind: String,
    },
    MarkMailDeliverySent {
        delivery_id: String,
        instance_id: String,
        smtp_status_code: Option<u16>,
        smtp_response: String,
    },
    RegisterAdminIdentity {
        identity_hex: String,
    },
    RemoveMessageCategory {
        category_id: u64,
    },
    RemoveSubscription {
        subscription_id: u64,
    },
    RenameTopic {
        topic_id: u64,
        new_name: String,
    },
    RetryMailIngress {
        ingress_id: String,
        instance_id: String,
        error: String,
    },
    RevokeWebhookToken {
        token_hash: String,
    },
    ScheduleMailDeliveryRetry {
        delivery_id: String,
        instance_id: String,
        error_msg: String,
        delay_micros: i64,
    },
    SetCategoryTopics {
        category_id: u64,
        topic_names: Vec<String>,
    },
    SetStalwartConfig {
        jmap_url: String,
        admin_token: String,
    },
    SyncUser {
        action: String,
        user_data: String,
    },
    UnregisterAdminIdentity {
        identity_hex: String,
    },
    UpdateMessageCategory {
        category_id: u64,
        name: String,
        description: String,
        visibility: Option<CategoryVisibility>,
    },
}

impl __sdk::InModule for Reducer {
    type Module = RemoteModule;
}

impl __sdk::Reducer for Reducer {
    fn reducer_name(&self) -> &'static str {
        match self {
            Reducer::AddAndSubscribeCategory { .. } => "add_and_subscribe_category",
            Reducer::AddMessageCategory { .. } => "add_message_category",
            Reducer::AddSubscription { .. } => "add_subscription",
            Reducer::AdminAddSubscription { .. } => "admin_add_subscription",
            Reducer::CancelMailDeliveryRetry { .. } => "cancel_mail_delivery_retry",
            Reducer::ClaimNextMailDelivery { .. } => "claim_next_mail_delivery",
            Reducer::ClaimNextMailIngress { .. } => "claim_next_mail_ingress",
            Reducer::CompleteMailIngress { .. } => "complete_mail_ingress",
            Reducer::CreateWebhookToken { .. } => "create_webhook_token",
            Reducer::DumpMtaLogsToServerLogs => "dump_mta_logs_to_server_logs",
            Reducer::EnqueueMailDelivery { .. } => "enqueue_mail_delivery",
            Reducer::EnsureSubscriptionUnsubscribeToken { .. } => {
                "ensure_subscription_unsubscribe_token"
            }
            Reducer::FailMailDelivery { .. } => "fail_mail_delivery",
            Reducer::FailMailIngress { .. } => "fail_mail_ingress",
            Reducer::IncrementMailIngressDeliveryCount { .. } => {
                "increment_mail_ingress_delivery_count"
            }
            Reducer::IncrementMailIngressFailedDeliveryCount { .. } => {
                "increment_mail_ingress_failed_delivery_count"
            }
            Reducer::MarkMailDeliveryBounced { .. } => "mark_mail_delivery_bounced",
            Reducer::MarkMailDeliverySent { .. } => "mark_mail_delivery_sent",
            Reducer::RegisterAdminIdentity { .. } => "register_admin_identity",
            Reducer::RemoveMessageCategory { .. } => "remove_message_category",
            Reducer::RemoveSubscription { .. } => "remove_subscription",
            Reducer::RenameTopic { .. } => "rename_topic",
            Reducer::RetryMailIngress { .. } => "retry_mail_ingress",
            Reducer::RevokeWebhookToken { .. } => "revoke_webhook_token",
            Reducer::ScheduleMailDeliveryRetry { .. } => "schedule_mail_delivery_retry",
            Reducer::SetCategoryTopics { .. } => "set_category_topics",
            Reducer::SetStalwartConfig { .. } => "set_stalwart_config",
            Reducer::SyncUser { .. } => "sync_user",
            Reducer::UnregisterAdminIdentity { .. } => "unregister_admin_identity",
            Reducer::UpdateMessageCategory { .. } => "update_message_category",
            _ => unreachable!(),
        }
    }
    #[allow(clippy::clone_on_copy)]
    fn args_bsatn(&self) -> Result<Vec<u8>, __sats::bsatn::EncodeError> {
        match self {
                        Reducer::AddAndSubscribeCategory{
                subscriber_account_id,
                subscriber_email,
                name,
                email_address,
                description,
                visibility,
}             => __sats::bsatn::to_vec(&add_and_subscribe_category_reducer::AddAndSubscribeCategoryArgs {
                subscriber_account_id: subscriber_account_id.clone(),
                subscriber_email: subscriber_email.clone(),
                name: name.clone(),
                email_address: email_address.clone(),
                description: description.clone(),
                visibility: visibility.clone(),
}),
            Reducer::AddMessageCategory{
                name,
                email_address,
                description,
                visibility,
}             => __sats::bsatn::to_vec(&add_message_category_reducer::AddMessageCategoryArgs {
                name: name.clone(),
                email_address: email_address.clone(),
                description: description.clone(),
                visibility: visibility.clone(),
}),
            Reducer::AddSubscription{
                subscriber_account_id,
                subscriber_email,
                category_id,
}             => __sats::bsatn::to_vec(&add_subscription_reducer::AddSubscriptionArgs {
                subscriber_account_id: subscriber_account_id.clone(),
                subscriber_email: subscriber_email.clone(),
                category_id: category_id.clone(),
}),
            Reducer::AdminAddSubscription{
                subscriber_account_id,
                subscriber_email,
                category_id,
                status,
}             => __sats::bsatn::to_vec(&admin_add_subscription_reducer::AdminAddSubscriptionArgs {
                subscriber_account_id: subscriber_account_id.clone(),
                subscriber_email: subscriber_email.clone(),
                category_id: category_id.clone(),
                status: status.clone(),
}),
            Reducer::CancelMailDeliveryRetry{
                delivery_id,
}             => __sats::bsatn::to_vec(&cancel_mail_delivery_retry_reducer::CancelMailDeliveryRetryArgs {
                delivery_id: delivery_id.clone(),
}),
            Reducer::ClaimNextMailDelivery{
                instance_id,
}             => __sats::bsatn::to_vec(&claim_next_mail_delivery_reducer::ClaimNextMailDeliveryArgs {
                instance_id: instance_id.clone(),
}),
            Reducer::ClaimNextMailIngress{
                instance_id,
}             => __sats::bsatn::to_vec(&claim_next_mail_ingress_reducer::ClaimNextMailIngressArgs {
                instance_id: instance_id.clone(),
}),
            Reducer::CompleteMailIngress{
                ingress_id,
                instance_id,
}             => __sats::bsatn::to_vec(&complete_mail_ingress_reducer::CompleteMailIngressArgs {
                ingress_id: ingress_id.clone(),
                instance_id: instance_id.clone(),
}),
            Reducer::CreateWebhookToken{
                token_hash,
                label,
                permissions,
}             => __sats::bsatn::to_vec(&create_webhook_token_reducer::CreateWebhookTokenArgs {
                token_hash: token_hash.clone(),
                label: label.clone(),
                permissions: permissions.clone(),
}),
            Reducer::DumpMtaLogsToServerLogs => __sats::bsatn::to_vec(&dump_mta_logs_to_server_logs_reducer::DumpMtaLogsToServerLogsArgs {
                }),
Reducer::EnqueueMailDelivery{
                ingress_id,
                subscription_id,
                recipient_email,
                recipient_account_id,
                from_header,
                reply_to,
                raw_message,
}             => __sats::bsatn::to_vec(&enqueue_mail_delivery_reducer::EnqueueMailDeliveryArgs {
                ingress_id: ingress_id.clone(),
                subscription_id: subscription_id.clone(),
                recipient_email: recipient_email.clone(),
                recipient_account_id: recipient_account_id.clone(),
                from_header: from_header.clone(),
                reply_to: reply_to.clone(),
                raw_message: raw_message.clone(),
}),
            Reducer::EnsureSubscriptionUnsubscribeToken{
                subscription_id,
}             => __sats::bsatn::to_vec(&ensure_subscription_unsubscribe_token_reducer::EnsureSubscriptionUnsubscribeTokenArgs {
                subscription_id: subscription_id.clone(),
}),
            Reducer::FailMailDelivery{
                delivery_id,
                instance_id,
                smtp_status_code,
                smtp_response,
                error_kind,
}             => __sats::bsatn::to_vec(&fail_mail_delivery_reducer::FailMailDeliveryArgs {
                delivery_id: delivery_id.clone(),
                instance_id: instance_id.clone(),
                smtp_status_code: smtp_status_code.clone(),
                smtp_response: smtp_response.clone(),
                error_kind: error_kind.clone(),
}),
            Reducer::FailMailIngress{
                ingress_id,
                instance_id,
                error,
}             => __sats::bsatn::to_vec(&fail_mail_ingress_reducer::FailMailIngressArgs {
                ingress_id: ingress_id.clone(),
                instance_id: instance_id.clone(),
                error: error.clone(),
}),
            Reducer::IncrementMailIngressDeliveryCount{
                ingress_id,
                instance_id,
}             => __sats::bsatn::to_vec(&increment_mail_ingress_delivery_count_reducer::IncrementMailIngressDeliveryCountArgs {
                ingress_id: ingress_id.clone(),
                instance_id: instance_id.clone(),
}),
            Reducer::IncrementMailIngressFailedDeliveryCount{
                ingress_id,
                instance_id,
}             => __sats::bsatn::to_vec(&increment_mail_ingress_failed_delivery_count_reducer::IncrementMailIngressFailedDeliveryCountArgs {
                ingress_id: ingress_id.clone(),
                instance_id: instance_id.clone(),
}),
            Reducer::MarkMailDeliveryBounced{
                delivery_id,
                instance_id,
                smtp_status_code,
                smtp_response,
                error_kind,
}             => __sats::bsatn::to_vec(&mark_mail_delivery_bounced_reducer::MarkMailDeliveryBouncedArgs {
                delivery_id: delivery_id.clone(),
                instance_id: instance_id.clone(),
                smtp_status_code: smtp_status_code.clone(),
                smtp_response: smtp_response.clone(),
                error_kind: error_kind.clone(),
}),
            Reducer::MarkMailDeliverySent{
                delivery_id,
                instance_id,
                smtp_status_code,
                smtp_response,
}             => __sats::bsatn::to_vec(&mark_mail_delivery_sent_reducer::MarkMailDeliverySentArgs {
                delivery_id: delivery_id.clone(),
                instance_id: instance_id.clone(),
                smtp_status_code: smtp_status_code.clone(),
                smtp_response: smtp_response.clone(),
}),
            Reducer::RegisterAdminIdentity{
                identity_hex,
}             => __sats::bsatn::to_vec(&register_admin_identity_reducer::RegisterAdminIdentityArgs {
                identity_hex: identity_hex.clone(),
}),
            Reducer::RemoveMessageCategory{
                category_id,
}             => __sats::bsatn::to_vec(&remove_message_category_reducer::RemoveMessageCategoryArgs {
                category_id: category_id.clone(),
}),
            Reducer::RemoveSubscription{
                subscription_id,
}             => __sats::bsatn::to_vec(&remove_subscription_reducer::RemoveSubscriptionArgs {
                subscription_id: subscription_id.clone(),
}),
            Reducer::RenameTopic{
                topic_id,
                new_name,
}             => __sats::bsatn::to_vec(&rename_topic_reducer::RenameTopicArgs {
                topic_id: topic_id.clone(),
                new_name: new_name.clone(),
}),
            Reducer::RetryMailIngress{
                ingress_id,
                instance_id,
                error,
}             => __sats::bsatn::to_vec(&retry_mail_ingress_reducer::RetryMailIngressArgs {
                ingress_id: ingress_id.clone(),
                instance_id: instance_id.clone(),
                error: error.clone(),
}),
            Reducer::RevokeWebhookToken{
                token_hash,
}             => __sats::bsatn::to_vec(&revoke_webhook_token_reducer::RevokeWebhookTokenArgs {
                token_hash: token_hash.clone(),
}),
            Reducer::ScheduleMailDeliveryRetry{
                delivery_id,
                instance_id,
                error_msg,
                delay_micros,
}             => __sats::bsatn::to_vec(&schedule_mail_delivery_retry_reducer::ScheduleMailDeliveryRetryArgs {
                delivery_id: delivery_id.clone(),
                instance_id: instance_id.clone(),
                error_msg: error_msg.clone(),
                delay_micros: delay_micros.clone(),
}),
            Reducer::SetCategoryTopics{
                category_id,
                topic_names,
}             => __sats::bsatn::to_vec(&set_category_topics_reducer::SetCategoryTopicsArgs {
                category_id: category_id.clone(),
                topic_names: topic_names.clone(),
}),
            Reducer::SetStalwartConfig{
                jmap_url,
                admin_token,
}             => __sats::bsatn::to_vec(&set_stalwart_config_reducer::SetStalwartConfigArgs {
                jmap_url: jmap_url.clone(),
                admin_token: admin_token.clone(),
}),
            Reducer::SyncUser{
                action,
                user_data,
}             => __sats::bsatn::to_vec(&sync_user_reducer::SyncUserArgs {
                action: action.clone(),
                user_data: user_data.clone(),
}),
            Reducer::UnregisterAdminIdentity{
                identity_hex,
}             => __sats::bsatn::to_vec(&unregister_admin_identity_reducer::UnregisterAdminIdentityArgs {
                identity_hex: identity_hex.clone(),
}),
            Reducer::UpdateMessageCategory{
                category_id,
                name,
                description,
                visibility,
}             => __sats::bsatn::to_vec(&update_message_category_reducer::UpdateMessageCategoryArgs {
                category_id: category_id.clone(),
                name: name.clone(),
                description: description.clone(),
                visibility: visibility.clone(),
}),
            _ => unreachable!(),
}
    }
}

#[derive(Default, Debug)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct DbUpdate {
    active_subscriptions: __sdk::TableUpdate<Subscription>,
    active_unsubscribe_tokens: __sdk::TableUpdate<SubscriptionUnsubscribeToken>,
    admin_stalwart_config: __sdk::TableUpdate<StalwartConfig>,
    expire_stale_delivery_claims_schedule: __sdk::TableUpdate<ExpireStaleDeliveryClaimsSchedule>,
    requeue_temporary_failed_mails_schedule:
        __sdk::TableUpdate<RequeueTemporaryFailedMailsSchedule>,
    sender_mail_delivery_claimed: __sdk::TableUpdate<MailDeliveryClaimed>,
    sender_mail_delivery_done: __sdk::TableUpdate<MailDeliveryDone>,
    sender_mail_delivery_events: __sdk::TableUpdate<MailDeliveryEvent>,
    sender_mail_delivery_messages: __sdk::TableUpdate<MailDeliveryMessage>,
    sender_mail_delivery_pending: __sdk::TableUpdate<MailDeliveryPending>,
    sender_mail_delivery_temporary_failed: __sdk::TableUpdate<MailDeliveryTemporaryFailed>,
    sender_mail_ingress: __sdk::TableUpdate<MailIngress>,
    sender_mail_messages: __sdk::TableUpdate<MailMessage>,
    visible_accounts: __sdk::TableUpdate<Account>,
    visible_admin_identities: __sdk::TableUpdate<AdminIdentity>,
    visible_category_app_passwords: __sdk::TableUpdate<CategoryAppPassword>,
    visible_domains: __sdk::TableUpdate<Domain>,
    visible_message_categories: __sdk::TableUpdate<MessageCategory>,
    visible_message_category_topics: __sdk::TableUpdate<MessageCategoryTopic>,
    visible_messages: __sdk::TableUpdate<ReceivedMessage>,
    visible_subscriptions: __sdk::TableUpdate<Subscription>,
    visible_topics: __sdk::TableUpdate<Topic>,
    visible_webhook_tokens: __sdk::TableUpdate<WebhookToken>,
}

impl TryFrom<__ws::v2::TransactionUpdate> for DbUpdate {
    type Error = __sdk::Error;
    fn try_from(raw: __ws::v2::TransactionUpdate) -> Result<Self, Self::Error> {
        let mut db_update = DbUpdate::default();
        for table_update in __sdk::transaction_update_iter_table_updates(raw) {
            match &table_update.table_name[..] {
                "active_subscriptions" => db_update.active_subscriptions.append(
                    active_subscriptions_table::parse_table_update(table_update)?,
                ),
                "active_unsubscribe_tokens" => db_update.active_unsubscribe_tokens.append(
                    active_unsubscribe_tokens_table::parse_table_update(table_update)?,
                ),
                "admin_stalwart_config" => db_update.admin_stalwart_config.append(
                    admin_stalwart_config_table::parse_table_update(table_update)?,
                ),
                "expire_stale_delivery_claims_schedule" => {
                    db_update.expire_stale_delivery_claims_schedule.append(
                        expire_stale_delivery_claims_schedule_table::parse_table_update(
                            table_update,
                        )?,
                    )
                }
                "requeue_temporary_failed_mails_schedule" => {
                    db_update.requeue_temporary_failed_mails_schedule.append(
                        requeue_temporary_failed_mails_schedule_table::parse_table_update(
                            table_update,
                        )?,
                    )
                }
                "sender_mail_delivery_claimed" => db_update.sender_mail_delivery_claimed.append(
                    sender_mail_delivery_claimed_table::parse_table_update(table_update)?,
                ),
                "sender_mail_delivery_done" => db_update.sender_mail_delivery_done.append(
                    sender_mail_delivery_done_table::parse_table_update(table_update)?,
                ),
                "sender_mail_delivery_events" => db_update.sender_mail_delivery_events.append(
                    sender_mail_delivery_events_table::parse_table_update(table_update)?,
                ),
                "sender_mail_delivery_messages" => db_update.sender_mail_delivery_messages.append(
                    sender_mail_delivery_messages_table::parse_table_update(table_update)?,
                ),
                "sender_mail_delivery_pending" => db_update.sender_mail_delivery_pending.append(
                    sender_mail_delivery_pending_table::parse_table_update(table_update)?,
                ),
                "sender_mail_delivery_temporary_failed" => {
                    db_update.sender_mail_delivery_temporary_failed.append(
                        sender_mail_delivery_temporary_failed_table::parse_table_update(
                            table_update,
                        )?,
                    )
                }
                "sender_mail_ingress" => db_update
                    .sender_mail_ingress
                    .append(sender_mail_ingress_table::parse_table_update(table_update)?),
                "sender_mail_messages" => db_update.sender_mail_messages.append(
                    sender_mail_messages_table::parse_table_update(table_update)?,
                ),
                "visible_accounts" => db_update
                    .visible_accounts
                    .append(visible_accounts_table::parse_table_update(table_update)?),
                "visible_admin_identities" => db_update.visible_admin_identities.append(
                    visible_admin_identities_table::parse_table_update(table_update)?,
                ),
                "visible_category_app_passwords" => {
                    db_update.visible_category_app_passwords.append(
                        visible_category_app_passwords_table::parse_table_update(table_update)?,
                    )
                }
                "visible_domains" => db_update
                    .visible_domains
                    .append(visible_domains_table::parse_table_update(table_update)?),
                "visible_message_categories" => db_update.visible_message_categories.append(
                    visible_message_categories_table::parse_table_update(table_update)?,
                ),
                "visible_message_category_topics" => {
                    db_update.visible_message_category_topics.append(
                        visible_message_category_topics_table::parse_table_update(table_update)?,
                    )
                }
                "visible_messages" => db_update
                    .visible_messages
                    .append(visible_messages_table::parse_table_update(table_update)?),
                "visible_subscriptions" => db_update.visible_subscriptions.append(
                    visible_subscriptions_table::parse_table_update(table_update)?,
                ),
                "visible_topics" => db_update
                    .visible_topics
                    .append(visible_topics_table::parse_table_update(table_update)?),
                "visible_webhook_tokens" => db_update.visible_webhook_tokens.append(
                    visible_webhook_tokens_table::parse_table_update(table_update)?,
                ),

                unknown => {
                    return Err(__sdk::InternalError::unknown_name(
                        "table",
                        unknown,
                        "DatabaseUpdate",
                    )
                    .into());
                }
            }
        }
        Ok(db_update)
    }
}

impl __sdk::InModule for DbUpdate {
    type Module = RemoteModule;
}

impl __sdk::DbUpdate for DbUpdate {
    fn apply_to_client_cache(
        &self,
        cache: &mut __sdk::ClientCache<RemoteModule>,
    ) -> AppliedDiff<'_> {
        let mut diff = AppliedDiff::default();

        diff.expire_stale_delivery_claims_schedule = cache
            .apply_diff_to_table::<ExpireStaleDeliveryClaimsSchedule>(
                "expire_stale_delivery_claims_schedule",
                &self.expire_stale_delivery_claims_schedule,
            )
            .with_updates_by_pk(|row| &row.scheduled_id);
        diff.requeue_temporary_failed_mails_schedule = cache
            .apply_diff_to_table::<RequeueTemporaryFailedMailsSchedule>(
                "requeue_temporary_failed_mails_schedule",
                &self.requeue_temporary_failed_mails_schedule,
            )
            .with_updates_by_pk(|row| &row.scheduled_id);
        diff.active_subscriptions = cache.apply_diff_to_table::<Subscription>(
            "active_subscriptions",
            &self.active_subscriptions,
        );
        diff.active_unsubscribe_tokens = cache
            .apply_diff_to_table::<SubscriptionUnsubscribeToken>(
                "active_unsubscribe_tokens",
                &self.active_unsubscribe_tokens,
            )
            .with_updates_by_pk(|row| &row.token);
        diff.admin_stalwart_config = cache
            .apply_diff_to_table::<StalwartConfig>(
                "admin_stalwart_config",
                &self.admin_stalwart_config,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.sender_mail_delivery_claimed = cache
            .apply_diff_to_table::<MailDeliveryClaimed>(
                "sender_mail_delivery_claimed",
                &self.sender_mail_delivery_claimed,
            )
            .with_updates_by_pk(|row| &row.delivery_id);
        diff.sender_mail_delivery_done = cache
            .apply_diff_to_table::<MailDeliveryDone>(
                "sender_mail_delivery_done",
                &self.sender_mail_delivery_done,
            )
            .with_updates_by_pk(|row| &row.delivery_id);
        diff.sender_mail_delivery_events = cache
            .apply_diff_to_table::<MailDeliveryEvent>(
                "sender_mail_delivery_events",
                &self.sender_mail_delivery_events,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.sender_mail_delivery_messages = cache
            .apply_diff_to_table::<MailDeliveryMessage>(
                "sender_mail_delivery_messages",
                &self.sender_mail_delivery_messages,
            )
            .with_updates_by_pk(|row| &row.delivery_id);
        diff.sender_mail_delivery_pending = cache
            .apply_diff_to_table::<MailDeliveryPending>(
                "sender_mail_delivery_pending",
                &self.sender_mail_delivery_pending,
            )
            .with_updates_by_pk(|row| &row.delivery_id);
        diff.sender_mail_delivery_temporary_failed = cache
            .apply_diff_to_table::<MailDeliveryTemporaryFailed>(
                "sender_mail_delivery_temporary_failed",
                &self.sender_mail_delivery_temporary_failed,
            )
            .with_updates_by_pk(|row| &row.delivery_id);
        diff.sender_mail_ingress = cache
            .apply_diff_to_table::<MailIngress>("sender_mail_ingress", &self.sender_mail_ingress)
            .with_updates_by_pk(|row| &row.id);
        diff.sender_mail_messages = cache
            .apply_diff_to_table::<MailMessage>("sender_mail_messages", &self.sender_mail_messages)
            .with_updates_by_pk(|row| &row.id);
        diff.visible_accounts =
            cache.apply_diff_to_table::<Account>("visible_accounts", &self.visible_accounts);
        diff.visible_admin_identities = cache
            .apply_diff_to_table::<AdminIdentity>(
                "visible_admin_identities",
                &self.visible_admin_identities,
            )
            .with_updates_by_pk(|row| &row.identity);
        diff.visible_category_app_passwords = cache
            .apply_diff_to_table::<CategoryAppPassword>(
                "visible_category_app_passwords",
                &self.visible_category_app_passwords,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.visible_domains = cache
            .apply_diff_to_table::<Domain>("visible_domains", &self.visible_domains)
            .with_updates_by_pk(|row| &row.id);
        diff.visible_message_categories = cache.apply_diff_to_table::<MessageCategory>(
            "visible_message_categories",
            &self.visible_message_categories,
        );
        diff.visible_message_category_topics = cache
            .apply_diff_to_table::<MessageCategoryTopic>(
                "visible_message_category_topics",
                &self.visible_message_category_topics,
            )
            .with_updates_by_pk(|row| &row.id);
        diff.visible_messages = cache
            .apply_diff_to_table::<ReceivedMessage>("visible_messages", &self.visible_messages);
        diff.visible_subscriptions = cache.apply_diff_to_table::<Subscription>(
            "visible_subscriptions",
            &self.visible_subscriptions,
        );
        diff.visible_topics = cache
            .apply_diff_to_table::<Topic>("visible_topics", &self.visible_topics)
            .with_updates_by_pk(|row| &row.id);
        diff.visible_webhook_tokens = cache
            .apply_diff_to_table::<WebhookToken>(
                "visible_webhook_tokens",
                &self.visible_webhook_tokens,
            )
            .with_updates_by_pk(|row| &row.id);

        diff
    }
    fn parse_initial_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "active_subscriptions" => db_update
                    .active_subscriptions
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "active_unsubscribe_tokens" => db_update
                    .active_unsubscribe_tokens
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "admin_stalwart_config" => db_update
                    .admin_stalwart_config
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "expire_stale_delivery_claims_schedule" => db_update
                    .expire_stale_delivery_claims_schedule
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "requeue_temporary_failed_mails_schedule" => db_update
                    .requeue_temporary_failed_mails_schedule
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sender_mail_delivery_claimed" => db_update
                    .sender_mail_delivery_claimed
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sender_mail_delivery_done" => db_update
                    .sender_mail_delivery_done
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sender_mail_delivery_events" => db_update
                    .sender_mail_delivery_events
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sender_mail_delivery_messages" => db_update
                    .sender_mail_delivery_messages
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sender_mail_delivery_pending" => db_update
                    .sender_mail_delivery_pending
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sender_mail_delivery_temporary_failed" => db_update
                    .sender_mail_delivery_temporary_failed
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sender_mail_ingress" => db_update
                    .sender_mail_ingress
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "sender_mail_messages" => db_update
                    .sender_mail_messages
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_accounts" => db_update
                    .visible_accounts
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_admin_identities" => db_update
                    .visible_admin_identities
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_category_app_passwords" => db_update
                    .visible_category_app_passwords
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_domains" => db_update
                    .visible_domains
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_message_categories" => db_update
                    .visible_message_categories
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_message_category_topics" => db_update
                    .visible_message_category_topics
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_messages" => db_update
                    .visible_messages
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_subscriptions" => db_update
                    .visible_subscriptions
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_topics" => db_update
                    .visible_topics
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                "visible_webhook_tokens" => db_update
                    .visible_webhook_tokens
                    .append(__sdk::parse_row_list_as_inserts(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
    fn parse_unsubscribe_rows(raw: __ws::v2::QueryRows) -> __sdk::Result<Self> {
        let mut db_update = DbUpdate::default();
        for table_rows in raw.tables {
            match &table_rows.table[..] {
                "active_subscriptions" => db_update
                    .active_subscriptions
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "active_unsubscribe_tokens" => db_update
                    .active_unsubscribe_tokens
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "admin_stalwart_config" => db_update
                    .admin_stalwart_config
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "expire_stale_delivery_claims_schedule" => db_update
                    .expire_stale_delivery_claims_schedule
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "requeue_temporary_failed_mails_schedule" => db_update
                    .requeue_temporary_failed_mails_schedule
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sender_mail_delivery_claimed" => db_update
                    .sender_mail_delivery_claimed
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sender_mail_delivery_done" => db_update
                    .sender_mail_delivery_done
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sender_mail_delivery_events" => db_update
                    .sender_mail_delivery_events
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sender_mail_delivery_messages" => db_update
                    .sender_mail_delivery_messages
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sender_mail_delivery_pending" => db_update
                    .sender_mail_delivery_pending
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sender_mail_delivery_temporary_failed" => db_update
                    .sender_mail_delivery_temporary_failed
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sender_mail_ingress" => db_update
                    .sender_mail_ingress
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "sender_mail_messages" => db_update
                    .sender_mail_messages
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_accounts" => db_update
                    .visible_accounts
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_admin_identities" => db_update
                    .visible_admin_identities
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_category_app_passwords" => db_update
                    .visible_category_app_passwords
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_domains" => db_update
                    .visible_domains
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_message_categories" => db_update
                    .visible_message_categories
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_message_category_topics" => db_update
                    .visible_message_category_topics
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_messages" => db_update
                    .visible_messages
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_subscriptions" => db_update
                    .visible_subscriptions
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_topics" => db_update
                    .visible_topics
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                "visible_webhook_tokens" => db_update
                    .visible_webhook_tokens
                    .append(__sdk::parse_row_list_as_deletes(table_rows.rows)?),
                unknown => {
                    return Err(
                        __sdk::InternalError::unknown_name("table", unknown, "QueryRows").into(),
                    );
                }
            }
        }
        Ok(db_update)
    }
}

#[derive(Default)]
#[allow(non_snake_case)]
#[doc(hidden)]
pub struct AppliedDiff<'r> {
    active_subscriptions: __sdk::TableAppliedDiff<'r, Subscription>,
    active_unsubscribe_tokens: __sdk::TableAppliedDiff<'r, SubscriptionUnsubscribeToken>,
    admin_stalwart_config: __sdk::TableAppliedDiff<'r, StalwartConfig>,
    expire_stale_delivery_claims_schedule:
        __sdk::TableAppliedDiff<'r, ExpireStaleDeliveryClaimsSchedule>,
    requeue_temporary_failed_mails_schedule:
        __sdk::TableAppliedDiff<'r, RequeueTemporaryFailedMailsSchedule>,
    sender_mail_delivery_claimed: __sdk::TableAppliedDiff<'r, MailDeliveryClaimed>,
    sender_mail_delivery_done: __sdk::TableAppliedDiff<'r, MailDeliveryDone>,
    sender_mail_delivery_events: __sdk::TableAppliedDiff<'r, MailDeliveryEvent>,
    sender_mail_delivery_messages: __sdk::TableAppliedDiff<'r, MailDeliveryMessage>,
    sender_mail_delivery_pending: __sdk::TableAppliedDiff<'r, MailDeliveryPending>,
    sender_mail_delivery_temporary_failed: __sdk::TableAppliedDiff<'r, MailDeliveryTemporaryFailed>,
    sender_mail_ingress: __sdk::TableAppliedDiff<'r, MailIngress>,
    sender_mail_messages: __sdk::TableAppliedDiff<'r, MailMessage>,
    visible_accounts: __sdk::TableAppliedDiff<'r, Account>,
    visible_admin_identities: __sdk::TableAppliedDiff<'r, AdminIdentity>,
    visible_category_app_passwords: __sdk::TableAppliedDiff<'r, CategoryAppPassword>,
    visible_domains: __sdk::TableAppliedDiff<'r, Domain>,
    visible_message_categories: __sdk::TableAppliedDiff<'r, MessageCategory>,
    visible_message_category_topics: __sdk::TableAppliedDiff<'r, MessageCategoryTopic>,
    visible_messages: __sdk::TableAppliedDiff<'r, ReceivedMessage>,
    visible_subscriptions: __sdk::TableAppliedDiff<'r, Subscription>,
    visible_topics: __sdk::TableAppliedDiff<'r, Topic>,
    visible_webhook_tokens: __sdk::TableAppliedDiff<'r, WebhookToken>,
    __unused: std::marker::PhantomData<&'r ()>,
}

impl __sdk::InModule for AppliedDiff<'_> {
    type Module = RemoteModule;
}

impl<'r> __sdk::AppliedDiff<'r> for AppliedDiff<'r> {
    fn invoke_row_callbacks(
        &self,
        event: &EventContext,
        callbacks: &mut __sdk::DbCallbacks<RemoteModule>,
    ) {
        callbacks.invoke_table_row_callbacks::<Subscription>(
            "active_subscriptions",
            &self.active_subscriptions,
            event,
        );
        callbacks.invoke_table_row_callbacks::<SubscriptionUnsubscribeToken>(
            "active_unsubscribe_tokens",
            &self.active_unsubscribe_tokens,
            event,
        );
        callbacks.invoke_table_row_callbacks::<StalwartConfig>(
            "admin_stalwart_config",
            &self.admin_stalwart_config,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ExpireStaleDeliveryClaimsSchedule>(
            "expire_stale_delivery_claims_schedule",
            &self.expire_stale_delivery_claims_schedule,
            event,
        );
        callbacks.invoke_table_row_callbacks::<RequeueTemporaryFailedMailsSchedule>(
            "requeue_temporary_failed_mails_schedule",
            &self.requeue_temporary_failed_mails_schedule,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MailDeliveryClaimed>(
            "sender_mail_delivery_claimed",
            &self.sender_mail_delivery_claimed,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MailDeliveryDone>(
            "sender_mail_delivery_done",
            &self.sender_mail_delivery_done,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MailDeliveryEvent>(
            "sender_mail_delivery_events",
            &self.sender_mail_delivery_events,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MailDeliveryMessage>(
            "sender_mail_delivery_messages",
            &self.sender_mail_delivery_messages,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MailDeliveryPending>(
            "sender_mail_delivery_pending",
            &self.sender_mail_delivery_pending,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MailDeliveryTemporaryFailed>(
            "sender_mail_delivery_temporary_failed",
            &self.sender_mail_delivery_temporary_failed,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MailIngress>(
            "sender_mail_ingress",
            &self.sender_mail_ingress,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MailMessage>(
            "sender_mail_messages",
            &self.sender_mail_messages,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Account>(
            "visible_accounts",
            &self.visible_accounts,
            event,
        );
        callbacks.invoke_table_row_callbacks::<AdminIdentity>(
            "visible_admin_identities",
            &self.visible_admin_identities,
            event,
        );
        callbacks.invoke_table_row_callbacks::<CategoryAppPassword>(
            "visible_category_app_passwords",
            &self.visible_category_app_passwords,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Domain>(
            "visible_domains",
            &self.visible_domains,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MessageCategory>(
            "visible_message_categories",
            &self.visible_message_categories,
            event,
        );
        callbacks.invoke_table_row_callbacks::<MessageCategoryTopic>(
            "visible_message_category_topics",
            &self.visible_message_category_topics,
            event,
        );
        callbacks.invoke_table_row_callbacks::<ReceivedMessage>(
            "visible_messages",
            &self.visible_messages,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Subscription>(
            "visible_subscriptions",
            &self.visible_subscriptions,
            event,
        );
        callbacks.invoke_table_row_callbacks::<Topic>(
            "visible_topics",
            &self.visible_topics,
            event,
        );
        callbacks.invoke_table_row_callbacks::<WebhookToken>(
            "visible_webhook_tokens",
            &self.visible_webhook_tokens,
            event,
        );
    }
}

#[doc(hidden)]
#[derive(Debug)]
pub struct RemoteModule;

impl __sdk::InModule for RemoteModule {
    type Module = Self;
}

/// The `reducers` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each reducer defined by the module.
pub struct RemoteReducers {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteReducers {
    type Module = RemoteModule;
}

/// The `procedures` field of [`DbConnection`] and other [`DbContext`] types,
/// with methods provided by extension traits for each procedure defined by the module.
pub struct RemoteProcedures {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteProcedures {
    type Module = RemoteModule;
}

/// The `db` field of [`EventContext`] and [`DbConnection`],
/// with methods provided by extension traits for each table defined by the module.
pub struct RemoteTables {
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for RemoteTables {
    type Module = RemoteModule;
}

/// A connection to a remote module, including a materialized view of a subset of the database.
///
/// Connect to a remote module by calling [`DbConnection::builder`]
/// and using the [`__sdk::DbConnectionBuilder`] builder-pattern constructor.
///
/// You must explicitly advance the connection by calling any one of:
///
/// - [`DbConnection::frame_tick`].
#[cfg_attr(not(target_arch = "wasm32"), doc = "- [`DbConnection::run_threaded`].")]
#[cfg_attr(
    target_arch = "wasm32",
    doc = "- [`DbConnection::run_background_task`]."
)]
/// - [`DbConnection::run_async`].
/// - [`DbConnection::advance_one_message`].
#[cfg_attr(
    not(target_arch = "wasm32"),
    doc = "- [`DbConnection::advance_one_message_blocking`]."
)]
/// - [`DbConnection::advance_one_message_async`].
///
/// Which of these methods you should call depends on the specific needs of your application,
/// but you must call one of them, or else the connection will never progress.
pub struct DbConnection {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    #[doc(hidden)]

    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,

    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::InModule for DbConnection {
    type Module = RemoteModule;
}

impl __sdk::DbContext for DbConnection {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl DbConnection {
    /// Builder-pattern constructor for a connection to a remote module.
    ///
    /// See [`__sdk::DbConnectionBuilder`] for required and optional configuration for the new connection.
    pub fn builder() -> __sdk::DbConnectionBuilder<RemoteModule> {
        __sdk::DbConnectionBuilder::new()
    }

    /// If any WebSocket messages are waiting, process one of them.
    ///
    /// Returns `true` if a message was processed, or `false` if the queue is empty.
    /// Callers should invoke this message in a loop until it returns `false`
    /// or for as much time is available to process messages.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::frame_tick`] each frame
    /// to fully exhaust the queue whenever time is available.
    pub fn advance_one_message(&self) -> __sdk::Result<bool> {
        self.imp.advance_one_message()
    }

    /// Process one WebSocket message, potentially blocking the current thread until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_threaded`] to spawn a thread
    /// which advances the connection automatically.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn advance_one_message_blocking(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_blocking()
    }

    /// Process one WebSocket message, `await`ing until one is received.
    ///
    /// Returns an error if the connection is disconnected.
    /// If the disconnection in question was normal,
    ///  i.e. the result of a call to [`__sdk::DbContext::disconnect`],
    /// the returned error will be downcastable to [`__sdk::DisconnectedError`].
    ///
    /// This is a low-level primitive exposed for power users who need significant control over scheduling.
    /// Most applications should call [`Self::run_async`] to run an `async` loop
    /// which advances the connection when polled.
    pub async fn advance_one_message_async(&self) -> __sdk::Result<()> {
        self.imp.advance_one_message_async().await
    }

    /// Process all WebSocket messages waiting in the queue,
    /// then return without `await`ing or blocking the current thread.
    pub fn frame_tick(&self) -> __sdk::Result<()> {
        self.imp.frame_tick()
    }

    /// Spawn a thread which processes WebSocket messages as they are received.
    #[cfg(not(target_arch = "wasm32"))]
    pub fn run_threaded(&self) -> std::thread::JoinHandle<()> {
        self.imp.run_threaded()
    }

    /// Spawn a background task which processes WebSocket messages as they are received.
    #[cfg(target_arch = "wasm32")]
    pub fn run_background_task(&self) {
        self.imp.run_background_task()
    }

    /// Run an `async` loop which processes WebSocket messages when polled.
    pub async fn run_async(&self) -> __sdk::Result<()> {
        self.imp.run_async().await
    }
}

impl __sdk::DbConnection for DbConnection {
    fn new(imp: __sdk::DbContextImpl<RemoteModule>) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

/// A handle on a subscribed query.
// TODO: Document this better after implementing the new subscription API.
#[derive(Clone)]
pub struct SubscriptionHandle {
    imp: __sdk::SubscriptionHandleImpl<RemoteModule>,
}

impl __sdk::InModule for SubscriptionHandle {
    type Module = RemoteModule;
}

impl __sdk::SubscriptionHandle for SubscriptionHandle {
    fn new(imp: __sdk::SubscriptionHandleImpl<RemoteModule>) -> Self {
        Self { imp }
    }

    /// Returns true if this subscription has been terminated due to an unsubscribe call or an error.
    fn is_ended(&self) -> bool {
        self.imp.is_ended()
    }

    /// Returns true if this subscription has been applied and has not yet been unsubscribed.
    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    /// Unsubscribe from the query controlled by this `SubscriptionHandle`,
    /// then run `on_end` when its rows are removed from the client cache.
    fn unsubscribe_then(self, on_end: __sdk::OnEndedCallback<RemoteModule>) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(Some(on_end))
    }

    fn unsubscribe(self) -> __sdk::Result<()> {
        self.imp.unsubscribe_then(None)
    }
}

/// Alias trait for a [`__sdk::DbContext`] connected to this module,
/// with that trait's associated types bounded to this module's concrete types.
///
/// Users can use this trait as a boundary on definitions which should accept
/// either a [`DbConnection`] or an [`EventContext`] and operate on either.
pub trait RemoteDbContext:
    __sdk::DbContext<
    DbView = RemoteTables,
    Reducers = RemoteReducers,
    SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
>
{
}
impl<
        Ctx: __sdk::DbContext<
            DbView = RemoteTables,
            Reducers = RemoteReducers,
            SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>,
        >,
    > RemoteDbContext for Ctx
{
}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Event`],
/// passed to [`__sdk::Table::on_insert`], [`__sdk::Table::on_delete`] and [`__sdk::TableWithPrimaryKey::on_update`] callbacks.
pub struct EventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::Event<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for EventContext {
    type Event = __sdk::Event<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for EventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for EventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::EventContext for EventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::ReducerEvent`],
/// passed to on-reducer callbacks.
pub struct ReducerEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: __sdk::ReducerEvent<Reducer>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ReducerEventContext {
    type Event = __sdk::ReducerEvent<Reducer>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ReducerEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ReducerEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ReducerEventContext for ReducerEventContext {}

/// An [`__sdk::DbContext`] passed to procedure callbacks.
pub struct ProcedureEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ProcedureEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for ProcedureEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ProcedureEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ProcedureEventContext for ProcedureEventContext {}

/// An [`__sdk::DbContext`] passed to [`__sdk::SubscriptionBuilder::on_applied`] and [`SubscriptionHandle::unsubscribe_then`] callbacks.
pub struct SubscriptionEventContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for SubscriptionEventContext {
    type Event = ();
    fn event(&self) -> &Self::Event {
        &()
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, _event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            imp,
        }
    }
}

impl __sdk::InModule for SubscriptionEventContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for SubscriptionEventContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::SubscriptionEventContext for SubscriptionEventContext {}

/// An [`__sdk::DbContext`] augmented with a [`__sdk::Error`],
/// passed to [`__sdk::DbConnectionBuilder::on_disconnect`], [`__sdk::DbConnectionBuilder::on_connect_error`] and [`__sdk::SubscriptionBuilder::on_error`] callbacks.
pub struct ErrorContext {
    /// Access to tables defined by the module via extension traits implemented for [`RemoteTables`].
    pub db: RemoteTables,
    /// Access to reducers defined by the module via extension traits implemented for [`RemoteReducers`].
    pub reducers: RemoteReducers,
    /// Access to procedures defined by the module via extension traits implemented for [`RemoteProcedures`].
    pub procedures: RemoteProcedures,
    /// The event which caused these callbacks to run.
    pub event: Option<__sdk::Error>,
    imp: __sdk::DbContextImpl<RemoteModule>,
}

impl __sdk::AbstractEventContext for ErrorContext {
    type Event = Option<__sdk::Error>;
    fn event(&self) -> &Self::Event {
        &self.event
    }
    fn new(imp: __sdk::DbContextImpl<RemoteModule>, event: Self::Event) -> Self {
        Self {
            db: RemoteTables { imp: imp.clone() },
            reducers: RemoteReducers { imp: imp.clone() },
            procedures: RemoteProcedures { imp: imp.clone() },
            event,
            imp,
        }
    }
}

impl __sdk::InModule for ErrorContext {
    type Module = RemoteModule;
}

impl __sdk::DbContext for ErrorContext {
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;

    fn db(&self) -> &Self::DbView {
        &self.db
    }
    fn reducers(&self) -> &Self::Reducers {
        &self.reducers
    }
    fn procedures(&self) -> &Self::Procedures {
        &self.procedures
    }

    fn is_active(&self) -> bool {
        self.imp.is_active()
    }

    fn disconnect(&self) -> __sdk::Result<()> {
        self.imp.disconnect()
    }

    type SubscriptionBuilder = __sdk::SubscriptionBuilder<RemoteModule>;

    fn subscription_builder(&self) -> Self::SubscriptionBuilder {
        __sdk::SubscriptionBuilder::new(&self.imp)
    }

    fn try_identity(&self) -> Option<__sdk::Identity> {
        self.imp.try_identity()
    }
    fn connection_id(&self) -> __sdk::ConnectionId {
        self.imp.connection_id()
    }
    fn try_connection_id(&self) -> Option<__sdk::ConnectionId> {
        self.imp.try_connection_id()
    }
}

impl __sdk::ErrorContext for ErrorContext {}

impl __sdk::SpacetimeModule for RemoteModule {
    type DbConnection = DbConnection;
    type EventContext = EventContext;
    type ReducerEventContext = ReducerEventContext;
    type ProcedureEventContext = ProcedureEventContext;
    type SubscriptionEventContext = SubscriptionEventContext;
    type ErrorContext = ErrorContext;
    type Reducer = Reducer;
    type DbView = RemoteTables;
    type Reducers = RemoteReducers;
    type Procedures = RemoteProcedures;
    type DbUpdate = DbUpdate;
    type AppliedDiff<'r> = AppliedDiff<'r>;
    type SubscriptionHandle = SubscriptionHandle;
    type QueryBuilder = __sdk::QueryBuilder;

    fn register_tables(client_cache: &mut __sdk::ClientCache<Self>) {
        active_subscriptions_table::register_table(client_cache);
        active_unsubscribe_tokens_table::register_table(client_cache);
        admin_stalwart_config_table::register_table(client_cache);
        expire_stale_delivery_claims_schedule_table::register_table(client_cache);
        requeue_temporary_failed_mails_schedule_table::register_table(client_cache);
        sender_mail_delivery_claimed_table::register_table(client_cache);
        sender_mail_delivery_done_table::register_table(client_cache);
        sender_mail_delivery_events_table::register_table(client_cache);
        sender_mail_delivery_messages_table::register_table(client_cache);
        sender_mail_delivery_pending_table::register_table(client_cache);
        sender_mail_delivery_temporary_failed_table::register_table(client_cache);
        sender_mail_ingress_table::register_table(client_cache);
        sender_mail_messages_table::register_table(client_cache);
        visible_accounts_table::register_table(client_cache);
        visible_admin_identities_table::register_table(client_cache);
        visible_category_app_passwords_table::register_table(client_cache);
        visible_domains_table::register_table(client_cache);
        visible_message_categories_table::register_table(client_cache);
        visible_message_category_topics_table::register_table(client_cache);
        visible_messages_table::register_table(client_cache);
        visible_subscriptions_table::register_table(client_cache);
        visible_topics_table::register_table(client_cache);
        visible_webhook_tokens_table::register_table(client_cache);
    }
    const ALL_TABLE_NAMES: &'static [&'static str] = &[
        "active_subscriptions",
        "active_unsubscribe_tokens",
        "admin_stalwart_config",
        "expire_stale_delivery_claims_schedule",
        "requeue_temporary_failed_mails_schedule",
        "sender_mail_delivery_claimed",
        "sender_mail_delivery_done",
        "sender_mail_delivery_events",
        "sender_mail_delivery_messages",
        "sender_mail_delivery_pending",
        "sender_mail_delivery_temporary_failed",
        "sender_mail_ingress",
        "sender_mail_messages",
        "visible_accounts",
        "visible_admin_identities",
        "visible_category_app_passwords",
        "visible_domains",
        "visible_message_categories",
        "visible_message_category_topics",
        "visible_messages",
        "visible_subscriptions",
        "visible_topics",
        "visible_webhook_tokens",
    ];
}
