// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::topic_visibility_type::TopicVisibility;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct ProvisionMessageTopicArgs {
    pub name: String,
    pub base: String,
    pub domain_id: String,
    pub description: String,
    pub visibility: TopicVisibility,
}

impl __sdk::InModule for ProvisionMessageTopicArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `provision_message_topic`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait provision_message_topic {
    fn provision_message_topic(
        &self,
        name: String,
        base: String,
        domain_id: String,
        description: String,
        visibility: TopicVisibility,
    ) {
        self.provision_message_topic_then(
            name,
            base,
            domain_id,
            description,
            visibility,
            |_, _| {},
        );
    }

    fn provision_message_topic_then(
        &self,
        name: String,
        base: String,
        domain_id: String,
        description: String,
        visibility: TopicVisibility,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl provision_message_topic for super::RemoteProcedures {
    fn provision_message_topic_then(
        &self,
        name: String,
        base: String,
        domain_id: String,
        description: String,
        visibility: TopicVisibility,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<(), String>>(
                "provision_message_topic",
                ProvisionMessageTopicArgs {
                    name,
                    base,
                    domain_id,
                    description,
                    visibility,
                },
                __callback,
            );
    }
}
