// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct RequeueTemporaryFailedMailsSchedule {
    pub scheduled_id: u64,
    pub scheduled_at: __sdk::ScheduleAt,
}

impl __sdk::InModule for RequeueTemporaryFailedMailsSchedule {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `RequeueTemporaryFailedMailsSchedule`.
///
/// Provides typed access to columns for query building.
pub struct RequeueTemporaryFailedMailsScheduleCols {
    pub scheduled_id: __sdk::__query_builder::Col<RequeueTemporaryFailedMailsSchedule, u64>,
    pub scheduled_at:
        __sdk::__query_builder::Col<RequeueTemporaryFailedMailsSchedule, __sdk::ScheduleAt>,
}

impl __sdk::__query_builder::HasCols for RequeueTemporaryFailedMailsSchedule {
    type Cols = RequeueTemporaryFailedMailsScheduleCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        RequeueTemporaryFailedMailsScheduleCols {
            scheduled_id: __sdk::__query_builder::Col::new(table_name, "scheduled_id"),
            scheduled_at: __sdk::__query_builder::Col::new(table_name, "scheduled_at"),
        }
    }
}

/// Indexed column accessor struct for the table `RequeueTemporaryFailedMailsSchedule`.
///
/// Provides typed access to indexed columns for query building.
pub struct RequeueTemporaryFailedMailsScheduleIxCols {
    pub scheduled_id: __sdk::__query_builder::IxCol<RequeueTemporaryFailedMailsSchedule, u64>,
}

impl __sdk::__query_builder::HasIxCols for RequeueTemporaryFailedMailsSchedule {
    type IxCols = RequeueTemporaryFailedMailsScheduleIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        RequeueTemporaryFailedMailsScheduleIxCols {
            scheduled_id: __sdk::__query_builder::IxCol::new(table_name, "scheduled_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for RequeueTemporaryFailedMailsSchedule {}
