// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::message_topic_type::MessageTopic;
use super::subscription_permission_type::SubscriptionPermission;
use super::topic_visibility_type::TopicVisibility;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sender_message_topics`.
///
/// Obtain a handle from the [`SenderMessageTopicsTableAccess::sender_message_topics`] method on [`super::RemoteTables`],
/// like `ctx.db.sender_message_topics()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_message_topics().on_insert(...)`.
pub struct SenderMessageTopicsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MessageTopic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sender_message_topics`.
pub struct SenderMessageTopicsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SenderMessageTopicsTableAccessor {
    type Row = MessageTopic;
    type Handle<'db> = SenderMessageTopicsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sender_message_topics()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sender_message_topics`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SenderMessageTopicsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SenderMessageTopicsTableHandle`], which mediates access to the table `sender_message_topics`.
    fn sender_message_topics(&self) -> SenderMessageTopicsTableHandle<'_>;
}

impl SenderMessageTopicsTableAccess for super::RemoteTables {
    fn sender_message_topics(&self) -> SenderMessageTopicsTableHandle<'_> {
        SenderMessageTopicsTableHandle {
            imp: self.imp.get_table::<MessageTopic>("sender_message_topics"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SenderMessageTopicsInsertCallbackId(__sdk::CallbackId);
pub struct SenderMessageTopicsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SenderMessageTopicsTableHandle<'ctx> {
    type Row = MessageTopic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageTopic> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SenderMessageTopicsTableHandle<'ctx> {
    type Row = MessageTopic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageTopic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SenderMessageTopicsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMessageTopicsInsertCallbackId {
        SenderMessageTopicsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMessageTopicsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SenderMessageTopicsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMessageTopicsDeleteCallbackId {
        SenderMessageTopicsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMessageTopicsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SenderMessageTopicsTableHandle<'ctx> {
    type InsertCallbackId = SenderMessageTopicsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMessageTopicsInsertCallbackId {
        SenderMessageTopicsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMessageTopicsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SenderMessageTopicsTableHandle<'ctx> {
    type DeleteCallbackId = SenderMessageTopicsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMessageTopicsDeleteCallbackId {
        SenderMessageTopicsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMessageTopicsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SenderMessageTopicsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SenderMessageTopicsTableHandle<'ctx> {
    type UpdateCallbackId = SenderMessageTopicsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMessageTopicsUpdateCallbackId {
        SenderMessageTopicsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMessageTopicsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SenderMessageTopicsTableHandle<'ctx> {
    type UpdateCallbackId = SenderMessageTopicsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMessageTopicsUpdateCallbackId {
        SenderMessageTopicsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMessageTopicsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sender_message_topics`,
/// which allows point queries on the field of the same name
/// via the [`SenderMessageTopicsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_message_topics().id().find(...)`.
pub struct SenderMessageTopicsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MessageTopic, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SenderMessageTopicsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sender_message_topics`.
    pub fn id(&self) -> SenderMessageTopicsIdUnique<'ctx> {
        SenderMessageTopicsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SenderMessageTopicsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MessageTopic> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MessageTopic>("sender_message_topics");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MessageTopic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MessageTopic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MessageTopic`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sender_message_topicsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MessageTopic`.
    fn sender_message_topics(&self) -> __sdk::__query_builder::Table<MessageTopic>;
}

impl sender_message_topicsQueryTableAccess for __sdk::QueryTableAccessor {
    fn sender_message_topics(&self) -> __sdk::__query_builder::Table<MessageTopic> {
        __sdk::__query_builder::Table::new("sender_message_topics")
    }
}
