// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::system_mail_pending_type::SystemMailPending;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sender_system_mail_pending`.
///
/// Obtain a handle from the [`SenderSystemMailPendingTableAccess::sender_system_mail_pending`] method on [`super::RemoteTables`],
/// like `ctx.db.sender_system_mail_pending()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_system_mail_pending().on_insert(...)`.
pub struct SenderSystemMailPendingTableHandle<'ctx> {
    imp: __sdk::TableHandle<SystemMailPending>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sender_system_mail_pending`.
pub struct SenderSystemMailPendingTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SenderSystemMailPendingTableAccessor {
    type Row = SystemMailPending;
    type Handle<'db> = SenderSystemMailPendingTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sender_system_mail_pending()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sender_system_mail_pending`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SenderSystemMailPendingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SenderSystemMailPendingTableHandle`], which mediates access to the table `sender_system_mail_pending`.
    fn sender_system_mail_pending(&self) -> SenderSystemMailPendingTableHandle<'_>;
}

impl SenderSystemMailPendingTableAccess for super::RemoteTables {
    fn sender_system_mail_pending(&self) -> SenderSystemMailPendingTableHandle<'_> {
        SenderSystemMailPendingTableHandle {
            imp: self
                .imp
                .get_table::<SystemMailPending>("sender_system_mail_pending"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SenderSystemMailPendingInsertCallbackId(__sdk::CallbackId);
pub struct SenderSystemMailPendingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SenderSystemMailPendingTableHandle<'ctx> {
    type Row = SystemMailPending;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SystemMailPending> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SenderSystemMailPendingTableHandle<'ctx> {
    type Row = SystemMailPending;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SystemMailPending> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SenderSystemMailPendingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderSystemMailPendingInsertCallbackId {
        SenderSystemMailPendingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderSystemMailPendingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SenderSystemMailPendingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderSystemMailPendingDeleteCallbackId {
        SenderSystemMailPendingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderSystemMailPendingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SenderSystemMailPendingTableHandle<'ctx> {
    type InsertCallbackId = SenderSystemMailPendingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderSystemMailPendingInsertCallbackId {
        SenderSystemMailPendingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderSystemMailPendingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SenderSystemMailPendingTableHandle<'ctx> {
    type DeleteCallbackId = SenderSystemMailPendingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderSystemMailPendingDeleteCallbackId {
        SenderSystemMailPendingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderSystemMailPendingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SenderSystemMailPendingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SenderSystemMailPendingTableHandle<'ctx> {
    type UpdateCallbackId = SenderSystemMailPendingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderSystemMailPendingUpdateCallbackId {
        SenderSystemMailPendingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderSystemMailPendingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SenderSystemMailPendingTableHandle<'ctx> {
    type UpdateCallbackId = SenderSystemMailPendingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderSystemMailPendingUpdateCallbackId {
        SenderSystemMailPendingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderSystemMailPendingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sender_system_mail_pending`,
/// which allows point queries on the field of the same name
/// via the [`SenderSystemMailPendingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_system_mail_pending().id().find(...)`.
pub struct SenderSystemMailPendingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SystemMailPending, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SenderSystemMailPendingTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sender_system_mail_pending`.
    pub fn id(&self) -> SenderSystemMailPendingIdUnique<'ctx> {
        SenderSystemMailPendingIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SenderSystemMailPendingIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SystemMailPending> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<SystemMailPending>("sender_system_mail_pending");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SystemMailPending>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<SystemMailPending>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SystemMailPending`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sender_system_mail_pendingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SystemMailPending`.
    fn sender_system_mail_pending(&self) -> __sdk::__query_builder::Table<SystemMailPending>;
}

impl sender_system_mail_pendingQueryTableAccess for __sdk::QueryTableAccessor {
    fn sender_system_mail_pending(&self) -> __sdk::__query_builder::Table<SystemMailPending> {
        __sdk::__query_builder::Table::new("sender_system_mail_pending")
    }
}
