// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mail_delivery_done_type::MailDeliveryDone;
use super::mail_delivery_row_type::MailDeliveryRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sender_mail_delivery_done`.
///
/// Obtain a handle from the [`SenderMailDeliveryDoneTableAccess::sender_mail_delivery_done`] method on [`super::RemoteTables`],
/// like `ctx.db.sender_mail_delivery_done()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_mail_delivery_done().on_insert(...)`.
pub struct SenderMailDeliveryDoneTableHandle<'ctx> {
    imp: __sdk::TableHandle<MailDeliveryDone>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sender_mail_delivery_done`.
pub struct SenderMailDeliveryDoneTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SenderMailDeliveryDoneTableAccessor {
    type Row = MailDeliveryDone;
    type Handle<'db> = SenderMailDeliveryDoneTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sender_mail_delivery_done()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sender_mail_delivery_done`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SenderMailDeliveryDoneTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SenderMailDeliveryDoneTableHandle`], which mediates access to the table `sender_mail_delivery_done`.
    fn sender_mail_delivery_done(&self) -> SenderMailDeliveryDoneTableHandle<'_>;
}

impl SenderMailDeliveryDoneTableAccess for super::RemoteTables {
    fn sender_mail_delivery_done(&self) -> SenderMailDeliveryDoneTableHandle<'_> {
        SenderMailDeliveryDoneTableHandle {
            imp: self
                .imp
                .get_table::<MailDeliveryDone>("sender_mail_delivery_done"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SenderMailDeliveryDoneInsertCallbackId(__sdk::CallbackId);
pub struct SenderMailDeliveryDoneDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SenderMailDeliveryDoneTableHandle<'ctx> {
    type Row = MailDeliveryDone;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailDeliveryDone> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SenderMailDeliveryDoneTableHandle<'ctx> {
    type Row = MailDeliveryDone;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailDeliveryDone> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SenderMailDeliveryDoneInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryDoneInsertCallbackId {
        SenderMailDeliveryDoneInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMailDeliveryDoneInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SenderMailDeliveryDoneDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryDoneDeleteCallbackId {
        SenderMailDeliveryDoneDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMailDeliveryDoneDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SenderMailDeliveryDoneTableHandle<'ctx> {
    type InsertCallbackId = SenderMailDeliveryDoneInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryDoneInsertCallbackId {
        SenderMailDeliveryDoneInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMailDeliveryDoneInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SenderMailDeliveryDoneTableHandle<'ctx> {
    type DeleteCallbackId = SenderMailDeliveryDoneDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryDoneDeleteCallbackId {
        SenderMailDeliveryDoneDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMailDeliveryDoneDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SenderMailDeliveryDoneUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SenderMailDeliveryDoneTableHandle<'ctx> {
    type UpdateCallbackId = SenderMailDeliveryDoneUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryDoneUpdateCallbackId {
        SenderMailDeliveryDoneUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMailDeliveryDoneUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SenderMailDeliveryDoneTableHandle<'ctx> {
    type UpdateCallbackId = SenderMailDeliveryDoneUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryDoneUpdateCallbackId {
        SenderMailDeliveryDoneUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMailDeliveryDoneUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sender_mail_delivery_done`,
/// which allows point queries on the field of the same name
/// via the [`SenderMailDeliveryDoneIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_mail_delivery_done().id().find(...)`.
pub struct SenderMailDeliveryDoneIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MailDeliveryDone, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SenderMailDeliveryDoneTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sender_mail_delivery_done`.
    pub fn id(&self) -> SenderMailDeliveryDoneIdUnique<'ctx> {
        SenderMailDeliveryDoneIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SenderMailDeliveryDoneIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<MailDeliveryDone> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MailDeliveryDone>("sender_mail_delivery_done");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MailDeliveryDone>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MailDeliveryDone>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MailDeliveryDone`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sender_mail_delivery_doneQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MailDeliveryDone`.
    fn sender_mail_delivery_done(&self) -> __sdk::__query_builder::Table<MailDeliveryDone>;
}

impl sender_mail_delivery_doneQueryTableAccess for __sdk::QueryTableAccessor {
    fn sender_mail_delivery_done(&self) -> __sdk::__query_builder::Table<MailDeliveryDone> {
        __sdk::__query_builder::Table::new("sender_mail_delivery_done")
    }
}
