// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mail_delivery_pending_type::MailDeliveryPending;
use super::mail_delivery_row_type::MailDeliveryRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sender_mail_delivery_pending`.
///
/// Obtain a handle from the [`SenderMailDeliveryPendingTableAccess::sender_mail_delivery_pending`] method on [`super::RemoteTables`],
/// like `ctx.db.sender_mail_delivery_pending()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_mail_delivery_pending().on_insert(...)`.
pub struct SenderMailDeliveryPendingTableHandle<'ctx> {
    imp: __sdk::TableHandle<MailDeliveryPending>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sender_mail_delivery_pending`.
pub struct SenderMailDeliveryPendingTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SenderMailDeliveryPendingTableAccessor {
    type Row = MailDeliveryPending;
    type Handle<'db> = SenderMailDeliveryPendingTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sender_mail_delivery_pending()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sender_mail_delivery_pending`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SenderMailDeliveryPendingTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SenderMailDeliveryPendingTableHandle`], which mediates access to the table `sender_mail_delivery_pending`.
    fn sender_mail_delivery_pending(&self) -> SenderMailDeliveryPendingTableHandle<'_>;
}

impl SenderMailDeliveryPendingTableAccess for super::RemoteTables {
    fn sender_mail_delivery_pending(&self) -> SenderMailDeliveryPendingTableHandle<'_> {
        SenderMailDeliveryPendingTableHandle {
            imp: self
                .imp
                .get_table::<MailDeliveryPending>("sender_mail_delivery_pending"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SenderMailDeliveryPendingInsertCallbackId(__sdk::CallbackId);
pub struct SenderMailDeliveryPendingDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SenderMailDeliveryPendingTableHandle<'ctx> {
    type Row = MailDeliveryPending;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailDeliveryPending> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SenderMailDeliveryPendingTableHandle<'ctx> {
    type Row = MailDeliveryPending;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailDeliveryPending> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SenderMailDeliveryPendingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryPendingInsertCallbackId {
        SenderMailDeliveryPendingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMailDeliveryPendingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SenderMailDeliveryPendingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryPendingDeleteCallbackId {
        SenderMailDeliveryPendingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMailDeliveryPendingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SenderMailDeliveryPendingTableHandle<'ctx> {
    type InsertCallbackId = SenderMailDeliveryPendingInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryPendingInsertCallbackId {
        SenderMailDeliveryPendingInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMailDeliveryPendingInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SenderMailDeliveryPendingTableHandle<'ctx> {
    type DeleteCallbackId = SenderMailDeliveryPendingDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryPendingDeleteCallbackId {
        SenderMailDeliveryPendingDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMailDeliveryPendingDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SenderMailDeliveryPendingUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SenderMailDeliveryPendingTableHandle<'ctx> {
    type UpdateCallbackId = SenderMailDeliveryPendingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryPendingUpdateCallbackId {
        SenderMailDeliveryPendingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMailDeliveryPendingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SenderMailDeliveryPendingTableHandle<'ctx> {
    type UpdateCallbackId = SenderMailDeliveryPendingUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryPendingUpdateCallbackId {
        SenderMailDeliveryPendingUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMailDeliveryPendingUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sender_mail_delivery_pending`,
/// which allows point queries on the field of the same name
/// via the [`SenderMailDeliveryPendingIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_mail_delivery_pending().id().find(...)`.
pub struct SenderMailDeliveryPendingIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MailDeliveryPending, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SenderMailDeliveryPendingTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sender_mail_delivery_pending`.
    pub fn id(&self) -> SenderMailDeliveryPendingIdUnique<'ctx> {
        SenderMailDeliveryPendingIdUnique {
            imp: self.imp.get_unique_constraint::<String>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SenderMailDeliveryPendingIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<MailDeliveryPending> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<MailDeliveryPending>("sender_mail_delivery_pending");
    _table.add_unique_constraint::<String>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MailDeliveryPending>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MailDeliveryPending>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MailDeliveryPending`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sender_mail_delivery_pendingQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MailDeliveryPending`.
    fn sender_mail_delivery_pending(&self) -> __sdk::__query_builder::Table<MailDeliveryPending>;
}

impl sender_mail_delivery_pendingQueryTableAccess for __sdk::QueryTableAccessor {
    fn sender_mail_delivery_pending(&self) -> __sdk::__query_builder::Table<MailDeliveryPending> {
        __sdk::__query_builder::Table::new("sender_mail_delivery_pending")
    }
}
