// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::account_type::Account;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sender_accounts`.
///
/// Obtain a handle from the [`SenderAccountsTableAccess::sender_accounts`] method on [`super::RemoteTables`],
/// like `ctx.db.sender_accounts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_accounts().on_insert(...)`.
pub struct SenderAccountsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Account>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sender_accounts`.
pub struct SenderAccountsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SenderAccountsTableAccessor {
    type Row = Account;
    type Handle<'db> = SenderAccountsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sender_accounts()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sender_accounts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SenderAccountsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SenderAccountsTableHandle`], which mediates access to the table `sender_accounts`.
    fn sender_accounts(&self) -> SenderAccountsTableHandle<'_>;
}

impl SenderAccountsTableAccess for super::RemoteTables {
    fn sender_accounts(&self) -> SenderAccountsTableHandle<'_> {
        SenderAccountsTableHandle {
            imp: self.imp.get_table::<Account>("sender_accounts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SenderAccountsInsertCallbackId(__sdk::CallbackId);
pub struct SenderAccountsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SenderAccountsTableHandle<'ctx> {
    type Row = Account;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Account> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SenderAccountsTableHandle<'ctx> {
    type Row = Account;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Account> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SenderAccountsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderAccountsInsertCallbackId {
        SenderAccountsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderAccountsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SenderAccountsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderAccountsDeleteCallbackId {
        SenderAccountsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderAccountsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SenderAccountsTableHandle<'ctx> {
    type InsertCallbackId = SenderAccountsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderAccountsInsertCallbackId {
        SenderAccountsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderAccountsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SenderAccountsTableHandle<'ctx> {
    type DeleteCallbackId = SenderAccountsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderAccountsDeleteCallbackId {
        SenderAccountsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderAccountsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SenderAccountsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SenderAccountsTableHandle<'ctx> {
    type UpdateCallbackId = SenderAccountsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderAccountsUpdateCallbackId {
        SenderAccountsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderAccountsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SenderAccountsTableHandle<'ctx> {
    type UpdateCallbackId = SenderAccountsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderAccountsUpdateCallbackId {
        SenderAccountsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderAccountsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sender_accounts`,
/// which allows point queries on the field of the same name
/// via the [`SenderAccountsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_accounts().id().find(...)`.
pub struct SenderAccountsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Account, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SenderAccountsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sender_accounts`.
    pub fn id(&self) -> SenderAccountsIdUnique<'ctx> {
        SenderAccountsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SenderAccountsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Account> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Account>("sender_accounts");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Account>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Account>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Account`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sender_accountsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Account`.
    fn sender_accounts(&self) -> __sdk::__query_builder::Table<Account>;
}

impl sender_accountsQueryTableAccess for __sdk::QueryTableAccessor {
    fn sender_accounts(&self) -> __sdk::__query_builder::Table<Account> {
        __sdk::__query_builder::Table::new("sender_accounts")
    }
}
