// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mail_message_type::MailMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sender_mail_messages`.
///
/// Obtain a handle from the [`SenderMailMessagesTableAccess::sender_mail_messages`] method on [`super::RemoteTables`],
/// like `ctx.db.sender_mail_messages()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_mail_messages().on_insert(...)`.
pub struct SenderMailMessagesTableHandle<'ctx> {
    imp: __sdk::TableHandle<MailMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sender_mail_messages`.
pub struct SenderMailMessagesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SenderMailMessagesTableAccessor {
    type Row = MailMessage;
    type Handle<'db> = SenderMailMessagesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sender_mail_messages()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sender_mail_messages`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SenderMailMessagesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SenderMailMessagesTableHandle`], which mediates access to the table `sender_mail_messages`.
    fn sender_mail_messages(&self) -> SenderMailMessagesTableHandle<'_>;
}

impl SenderMailMessagesTableAccess for super::RemoteTables {
    fn sender_mail_messages(&self) -> SenderMailMessagesTableHandle<'_> {
        SenderMailMessagesTableHandle {
            imp: self.imp.get_table::<MailMessage>("sender_mail_messages"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SenderMailMessagesInsertCallbackId(__sdk::CallbackId);
pub struct SenderMailMessagesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SenderMailMessagesTableHandle<'ctx> {
    type Row = MailMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailMessage> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SenderMailMessagesTableHandle<'ctx> {
    type Row = MailMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SenderMailMessagesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailMessagesInsertCallbackId {
        SenderMailMessagesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMailMessagesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SenderMailMessagesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailMessagesDeleteCallbackId {
        SenderMailMessagesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMailMessagesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SenderMailMessagesTableHandle<'ctx> {
    type InsertCallbackId = SenderMailMessagesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailMessagesInsertCallbackId {
        SenderMailMessagesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMailMessagesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SenderMailMessagesTableHandle<'ctx> {
    type DeleteCallbackId = SenderMailMessagesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailMessagesDeleteCallbackId {
        SenderMailMessagesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMailMessagesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SenderMailMessagesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SenderMailMessagesTableHandle<'ctx> {
    type UpdateCallbackId = SenderMailMessagesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMailMessagesUpdateCallbackId {
        SenderMailMessagesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMailMessagesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SenderMailMessagesTableHandle<'ctx> {
    type UpdateCallbackId = SenderMailMessagesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMailMessagesUpdateCallbackId {
        SenderMailMessagesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMailMessagesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sender_mail_messages`,
/// which allows point queries on the field of the same name
/// via the [`SenderMailMessagesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_mail_messages().id().find(...)`.
pub struct SenderMailMessagesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MailMessage, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SenderMailMessagesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sender_mail_messages`.
    pub fn id(&self) -> SenderMailMessagesIdUnique<'ctx> {
        SenderMailMessagesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SenderMailMessagesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MailMessage> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MailMessage>("sender_mail_messages");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MailMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MailMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MailMessage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sender_mail_messagesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MailMessage`.
    fn sender_mail_messages(&self) -> __sdk::__query_builder::Table<MailMessage>;
}

impl sender_mail_messagesQueryTableAccess for __sdk::QueryTableAccessor {
    fn sender_mail_messages(&self) -> __sdk::__query_builder::Table<MailMessage> {
        __sdk::__query_builder::Table::new("sender_mail_messages")
    }
}
