// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subscription_unsubscribe_token_type::SubscriptionUnsubscribeToken;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `subscription_unsubscribe_tokens`.
///
/// Obtain a handle from the [`SubscriptionUnsubscribeTokensTableAccess::subscription_unsubscribe_tokens`] method on [`super::RemoteTables`],
/// like `ctx.db.subscription_unsubscribe_tokens()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_unsubscribe_tokens().on_insert(...)`.
pub struct SubscriptionUnsubscribeTokensTableHandle<'ctx> {
    imp: __sdk::TableHandle<SubscriptionUnsubscribeToken>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `subscription_unsubscribe_tokens`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SubscriptionUnsubscribeTokensTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SubscriptionUnsubscribeTokensTableHandle`], which mediates access to the table `subscription_unsubscribe_tokens`.
    fn subscription_unsubscribe_tokens(&self) -> SubscriptionUnsubscribeTokensTableHandle<'_>;
}

impl SubscriptionUnsubscribeTokensTableAccess for super::RemoteTables {
    fn subscription_unsubscribe_tokens(&self) -> SubscriptionUnsubscribeTokensTableHandle<'_> {
        SubscriptionUnsubscribeTokensTableHandle {
            imp: self
                .imp
                .get_table::<SubscriptionUnsubscribeToken>("subscription_unsubscribe_tokens"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SubscriptionUnsubscribeTokensInsertCallbackId(__sdk::CallbackId);
pub struct SubscriptionUnsubscribeTokensDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SubscriptionUnsubscribeTokensTableHandle<'ctx> {
    type Row = SubscriptionUnsubscribeToken;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = SubscriptionUnsubscribeToken> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SubscriptionUnsubscribeTokensInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionUnsubscribeTokensInsertCallbackId {
        SubscriptionUnsubscribeTokensInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SubscriptionUnsubscribeTokensInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SubscriptionUnsubscribeTokensDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionUnsubscribeTokensDeleteCallbackId {
        SubscriptionUnsubscribeTokensDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SubscriptionUnsubscribeTokensDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SubscriptionUnsubscribeTokensUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SubscriptionUnsubscribeTokensTableHandle<'ctx> {
    type UpdateCallbackId = SubscriptionUnsubscribeTokensUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SubscriptionUnsubscribeTokensUpdateCallbackId {
        SubscriptionUnsubscribeTokensUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SubscriptionUnsubscribeTokensUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `token` unique index on the table `subscription_unsubscribe_tokens`,
/// which allows point queries on the field of the same name
/// via the [`SubscriptionUnsubscribeTokensTokenUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_unsubscribe_tokens().token().find(...)`.
pub struct SubscriptionUnsubscribeTokensTokenUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SubscriptionUnsubscribeToken, String>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubscriptionUnsubscribeTokensTableHandle<'ctx> {
    /// Get a handle on the `token` unique index on the table `subscription_unsubscribe_tokens`.
    pub fn token(&self) -> SubscriptionUnsubscribeTokensTokenUnique<'ctx> {
        SubscriptionUnsubscribeTokensTokenUnique {
            imp: self.imp.get_unique_constraint::<String>("token"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubscriptionUnsubscribeTokensTokenUnique<'ctx> {
    /// Find the subscribed row whose `token` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &String) -> Option<SubscriptionUnsubscribeToken> {
        self.imp.find(col_val)
    }
}

/// Access to the `subscription_id` unique index on the table `subscription_unsubscribe_tokens`,
/// which allows point queries on the field of the same name
/// via the [`SubscriptionUnsubscribeTokensSubscriptionIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscription_unsubscribe_tokens().subscription_id().find(...)`.
pub struct SubscriptionUnsubscribeTokensSubscriptionIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<SubscriptionUnsubscribeToken, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubscriptionUnsubscribeTokensTableHandle<'ctx> {
    /// Get a handle on the `subscription_id` unique index on the table `subscription_unsubscribe_tokens`.
    pub fn subscription_id(&self) -> SubscriptionUnsubscribeTokensSubscriptionIdUnique<'ctx> {
        SubscriptionUnsubscribeTokensSubscriptionIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("subscription_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubscriptionUnsubscribeTokensSubscriptionIdUnique<'ctx> {
    /// Find the subscribed row whose `subscription_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<SubscriptionUnsubscribeToken> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache
        .get_or_make_table::<SubscriptionUnsubscribeToken>("subscription_unsubscribe_tokens");
    _table.add_unique_constraint::<String>("token", |row| &row.token);
    _table.add_unique_constraint::<u64>("subscription_id", |row| &row.subscription_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<SubscriptionUnsubscribeToken>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<SubscriptionUnsubscribeToken>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `SubscriptionUnsubscribeToken`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait subscription_unsubscribe_tokensQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `SubscriptionUnsubscribeToken`.
    fn subscription_unsubscribe_tokens(
        &self,
    ) -> __sdk::__query_builder::Table<SubscriptionUnsubscribeToken>;
}

impl subscription_unsubscribe_tokensQueryTableAccess for __sdk::QueryTableAccessor {
    fn subscription_unsubscribe_tokens(
        &self,
    ) -> __sdk::__query_builder::Table<SubscriptionUnsubscribeToken> {
        __sdk::__query_builder::Table::new("subscription_unsubscribe_tokens")
    }
}
