// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::subscription_permission_type::SubscriptionPermission;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateSubscriptionPermissionArgs {
    pub subscription_id: u64,
    pub permission: SubscriptionPermission,
}

impl From<UpdateSubscriptionPermissionArgs> for super::Reducer {
    fn from(args: UpdateSubscriptionPermissionArgs) -> Self {
        Self::UpdateSubscriptionPermission {
            subscription_id: args.subscription_id,
            permission: args.permission,
        }
    }
}

impl __sdk::InModule for UpdateSubscriptionPermissionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_subscription_permission`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_subscription_permission {
    /// Request that the remote module invoke the reducer `update_subscription_permission` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`update_subscription_permission:update_subscription_permission_then`] to run a callback after the reducer completes.
    fn update_subscription_permission(
        &self,
        subscription_id: u64,
        permission: SubscriptionPermission,
    ) -> __sdk::Result<()> {
        self.update_subscription_permission_then(subscription_id, permission, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_subscription_permission` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_subscription_permission_then(
        &self,
        subscription_id: u64,
        permission: SubscriptionPermission,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_subscription_permission for super::RemoteReducers {
    fn update_subscription_permission_then(
        &self,
        subscription_id: u64,
        permission: SubscriptionPermission,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateSubscriptionPermissionArgs {
                subscription_id,
                permission,
            },
            callback,
        )
    }
}
