// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::message_topic_type::MessageTopic;
use super::subscription_permission_type::SubscriptionPermission;
use super::topic_visibility_type::TopicVisibility;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_message_topics`.
///
/// Obtain a handle from the [`VisibleMessageTopicsTableAccess::visible_message_topics`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_message_topics()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_message_topics().on_insert(...)`.
pub struct VisibleMessageTopicsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MessageTopic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_message_topics`.
pub struct VisibleMessageTopicsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleMessageTopicsTableAccessor {
    type Row = MessageTopic;
    type Handle<'db> = VisibleMessageTopicsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_message_topics()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_message_topics`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleMessageTopicsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleMessageTopicsTableHandle`], which mediates access to the table `visible_message_topics`.
    fn visible_message_topics(&self) -> VisibleMessageTopicsTableHandle<'_>;
}

impl VisibleMessageTopicsTableAccess for super::RemoteTables {
    fn visible_message_topics(&self) -> VisibleMessageTopicsTableHandle<'_> {
        VisibleMessageTopicsTableHandle {
            imp: self.imp.get_table::<MessageTopic>("visible_message_topics"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleMessageTopicsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleMessageTopicsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleMessageTopicsTableHandle<'ctx> {
    type Row = MessageTopic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageTopic> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleMessageTopicsTableHandle<'ctx> {
    type Row = MessageTopic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageTopic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleMessageTopicsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicsInsertCallbackId {
        VisibleMessageTopicsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessageTopicsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleMessageTopicsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicsDeleteCallbackId {
        VisibleMessageTopicsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessageTopicsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleMessageTopicsTableHandle<'ctx> {
    type InsertCallbackId = VisibleMessageTopicsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicsInsertCallbackId {
        VisibleMessageTopicsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessageTopicsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleMessageTopicsTableHandle<'ctx> {
    type DeleteCallbackId = VisibleMessageTopicsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicsDeleteCallbackId {
        VisibleMessageTopicsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessageTopicsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MessageTopic>("visible_message_topics");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MessageTopic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MessageTopic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MessageTopic`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_message_topicsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MessageTopic`.
    fn visible_message_topics(&self) -> __sdk::__query_builder::Table<MessageTopic>;
}

impl visible_message_topicsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_message_topics(&self) -> __sdk::__query_builder::Table<MessageTopic> {
        __sdk::__query_builder::Table::new("visible_message_topics")
    }
}
