// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::topic_app_password_type::TopicAppPassword;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_topic_app_passwords`.
///
/// Obtain a handle from the [`VisibleTopicAppPasswordsTableAccess::visible_topic_app_passwords`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_topic_app_passwords()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_topic_app_passwords().on_insert(...)`.
pub struct VisibleTopicAppPasswordsTableHandle<'ctx> {
    imp: __sdk::TableHandle<TopicAppPassword>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_topic_app_passwords`.
pub struct VisibleTopicAppPasswordsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleTopicAppPasswordsTableAccessor {
    type Row = TopicAppPassword;
    type Handle<'db> = VisibleTopicAppPasswordsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_topic_app_passwords()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_topic_app_passwords`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleTopicAppPasswordsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleTopicAppPasswordsTableHandle`], which mediates access to the table `visible_topic_app_passwords`.
    fn visible_topic_app_passwords(&self) -> VisibleTopicAppPasswordsTableHandle<'_>;
}

impl VisibleTopicAppPasswordsTableAccess for super::RemoteTables {
    fn visible_topic_app_passwords(&self) -> VisibleTopicAppPasswordsTableHandle<'_> {
        VisibleTopicAppPasswordsTableHandle {
            imp: self
                .imp
                .get_table::<TopicAppPassword>("visible_topic_app_passwords"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleTopicAppPasswordsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleTopicAppPasswordsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleTopicAppPasswordsTableHandle<'ctx> {
    type Row = TopicAppPassword;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TopicAppPassword> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleTopicAppPasswordsTableHandle<'ctx> {
    type Row = TopicAppPassword;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = TopicAppPassword> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleTopicAppPasswordsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleTopicAppPasswordsInsertCallbackId {
        VisibleTopicAppPasswordsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleTopicAppPasswordsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleTopicAppPasswordsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleTopicAppPasswordsDeleteCallbackId {
        VisibleTopicAppPasswordsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleTopicAppPasswordsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleTopicAppPasswordsTableHandle<'ctx> {
    type InsertCallbackId = VisibleTopicAppPasswordsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleTopicAppPasswordsInsertCallbackId {
        VisibleTopicAppPasswordsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleTopicAppPasswordsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleTopicAppPasswordsTableHandle<'ctx> {
    type DeleteCallbackId = VisibleTopicAppPasswordsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleTopicAppPasswordsDeleteCallbackId {
        VisibleTopicAppPasswordsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleTopicAppPasswordsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleTopicAppPasswordsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleTopicAppPasswordsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleTopicAppPasswordsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleTopicAppPasswordsUpdateCallbackId {
        VisibleTopicAppPasswordsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleTopicAppPasswordsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleTopicAppPasswordsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleTopicAppPasswordsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleTopicAppPasswordsUpdateCallbackId {
        VisibleTopicAppPasswordsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleTopicAppPasswordsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `visible_topic_app_passwords`,
/// which allows point queries on the field of the same name
/// via the [`VisibleTopicAppPasswordsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_topic_app_passwords().id().find(...)`.
pub struct VisibleTopicAppPasswordsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<TopicAppPassword, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleTopicAppPasswordsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `visible_topic_app_passwords`.
    pub fn id(&self) -> VisibleTopicAppPasswordsIdUnique<'ctx> {
        VisibleTopicAppPasswordsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleTopicAppPasswordsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<TopicAppPassword> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<TopicAppPassword>("visible_topic_app_passwords");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<TopicAppPassword>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<TopicAppPassword>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `TopicAppPassword`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_topic_app_passwordsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `TopicAppPassword`.
    fn visible_topic_app_passwords(&self) -> __sdk::__query_builder::Table<TopicAppPassword>;
}

impl visible_topic_app_passwordsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_topic_app_passwords(&self) -> __sdk::__query_builder::Table<TopicAppPassword> {
        __sdk::__query_builder::Table::new("visible_topic_app_passwords")
    }
}
