// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::account_config_type::AccountConfig;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_account_configs`.
///
/// Obtain a handle from the [`VisibleAccountConfigsTableAccess::visible_account_configs`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_account_configs()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_account_configs().on_insert(...)`.
pub struct VisibleAccountConfigsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AccountConfig>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_account_configs`.
pub struct VisibleAccountConfigsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleAccountConfigsTableAccessor {
    type Row = AccountConfig;
    type Handle<'db> = VisibleAccountConfigsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_account_configs()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_account_configs`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleAccountConfigsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleAccountConfigsTableHandle`], which mediates access to the table `visible_account_configs`.
    fn visible_account_configs(&self) -> VisibleAccountConfigsTableHandle<'_>;
}

impl VisibleAccountConfigsTableAccess for super::RemoteTables {
    fn visible_account_configs(&self) -> VisibleAccountConfigsTableHandle<'_> {
        VisibleAccountConfigsTableHandle {
            imp: self
                .imp
                .get_table::<AccountConfig>("visible_account_configs"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleAccountConfigsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleAccountConfigsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleAccountConfigsTableHandle<'ctx> {
    type Row = AccountConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountConfig> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleAccountConfigsTableHandle<'ctx> {
    type Row = AccountConfig;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountConfig> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleAccountConfigsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAccountConfigsInsertCallbackId {
        VisibleAccountConfigsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleAccountConfigsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleAccountConfigsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAccountConfigsDeleteCallbackId {
        VisibleAccountConfigsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleAccountConfigsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleAccountConfigsTableHandle<'ctx> {
    type InsertCallbackId = VisibleAccountConfigsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAccountConfigsInsertCallbackId {
        VisibleAccountConfigsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleAccountConfigsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleAccountConfigsTableHandle<'ctx> {
    type DeleteCallbackId = VisibleAccountConfigsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAccountConfigsDeleteCallbackId {
        VisibleAccountConfigsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleAccountConfigsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AccountConfig>("visible_account_configs");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AccountConfig>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AccountConfig>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AccountConfig`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_account_configsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AccountConfig`.
    fn visible_account_configs(&self) -> __sdk::__query_builder::Table<AccountConfig>;
}

impl visible_account_configsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_account_configs(&self) -> __sdk::__query_builder::Table<AccountConfig> {
        __sdk::__query_builder::Table::new("visible_account_configs")
    }
}
