// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct AccountConfig {
    pub account_id: u64,
    pub message_offset: u32,
    pub message_limit: u32,
    pub selected_message_category: Option<u64>,
    pub member_offset: u32,
    pub member_limit: u32,
    pub member_search_query: Option<String>,
    pub viewing_category_id: Option<u64>,
    pub language: Option<String>,
    pub theme: Option<String>,
    pub search_matching_accounts: u32,
}

impl __sdk::InModule for AccountConfig {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `AccountConfig`.
///
/// Provides typed access to columns for query building.
pub struct AccountConfigCols {
    pub account_id: __sdk::__query_builder::Col<AccountConfig, u64>,
    pub message_offset: __sdk::__query_builder::Col<AccountConfig, u32>,
    pub message_limit: __sdk::__query_builder::Col<AccountConfig, u32>,
    pub selected_message_category: __sdk::__query_builder::Col<AccountConfig, Option<u64>>,
    pub member_offset: __sdk::__query_builder::Col<AccountConfig, u32>,
    pub member_limit: __sdk::__query_builder::Col<AccountConfig, u32>,
    pub member_search_query: __sdk::__query_builder::Col<AccountConfig, Option<String>>,
    pub viewing_category_id: __sdk::__query_builder::Col<AccountConfig, Option<u64>>,
    pub language: __sdk::__query_builder::Col<AccountConfig, Option<String>>,
    pub theme: __sdk::__query_builder::Col<AccountConfig, Option<String>>,
    pub search_matching_accounts: __sdk::__query_builder::Col<AccountConfig, u32>,
}

impl __sdk::__query_builder::HasCols for AccountConfig {
    type Cols = AccountConfigCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountConfigCols {
            account_id: __sdk::__query_builder::Col::new(table_name, "account_id"),
            message_offset: __sdk::__query_builder::Col::new(table_name, "message_offset"),
            message_limit: __sdk::__query_builder::Col::new(table_name, "message_limit"),
            selected_message_category: __sdk::__query_builder::Col::new(
                table_name,
                "selected_message_category",
            ),
            member_offset: __sdk::__query_builder::Col::new(table_name, "member_offset"),
            member_limit: __sdk::__query_builder::Col::new(table_name, "member_limit"),
            member_search_query: __sdk::__query_builder::Col::new(
                table_name,
                "member_search_query",
            ),
            viewing_category_id: __sdk::__query_builder::Col::new(
                table_name,
                "viewing_category_id",
            ),
            language: __sdk::__query_builder::Col::new(table_name, "language"),
            theme: __sdk::__query_builder::Col::new(table_name, "theme"),
            search_matching_accounts: __sdk::__query_builder::Col::new(
                table_name,
                "search_matching_accounts",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `AccountConfig`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountConfigIxCols {
    pub account_id: __sdk::__query_builder::IxCol<AccountConfig, u64>,
}

impl __sdk::__query_builder::HasIxCols for AccountConfig {
    type IxCols = AccountConfigIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountConfigIxCols {
            account_id: __sdk::__query_builder::IxCol::new(table_name, "account_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for AccountConfig {}
