// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subscription_status_type::SubscriptionStatus;
use super::subscription_type::Subscription;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `active_subscriptions`.
///
/// Obtain a handle from the [`ActiveSubscriptionsTableAccess::active_subscriptions`] method on [`super::RemoteTables`],
/// like `ctx.db.active_subscriptions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.active_subscriptions().on_insert(...)`.
pub struct ActiveSubscriptionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Subscription>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `active_subscriptions`.
pub struct ActiveSubscriptionsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for ActiveSubscriptionsTableAccessor {
    type Row = Subscription;
    type Handle<'db> = ActiveSubscriptionsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.active_subscriptions()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `active_subscriptions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait ActiveSubscriptionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`ActiveSubscriptionsTableHandle`], which mediates access to the table `active_subscriptions`.
    fn active_subscriptions(&self) -> ActiveSubscriptionsTableHandle<'_>;
}

impl ActiveSubscriptionsTableAccess for super::RemoteTables {
    fn active_subscriptions(&self) -> ActiveSubscriptionsTableHandle<'_> {
        ActiveSubscriptionsTableHandle {
            imp: self.imp.get_table::<Subscription>("active_subscriptions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct ActiveSubscriptionsInsertCallbackId(__sdk::CallbackId);
pub struct ActiveSubscriptionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for ActiveSubscriptionsTableHandle<'ctx> {
    type Row = Subscription;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Subscription> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for ActiveSubscriptionsTableHandle<'ctx> {
    type Row = Subscription;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Subscription> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = ActiveSubscriptionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveSubscriptionsInsertCallbackId {
        ActiveSubscriptionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveSubscriptionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = ActiveSubscriptionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveSubscriptionsDeleteCallbackId {
        ActiveSubscriptionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveSubscriptionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for ActiveSubscriptionsTableHandle<'ctx> {
    type InsertCallbackId = ActiveSubscriptionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveSubscriptionsInsertCallbackId {
        ActiveSubscriptionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: ActiveSubscriptionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for ActiveSubscriptionsTableHandle<'ctx> {
    type DeleteCallbackId = ActiveSubscriptionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> ActiveSubscriptionsDeleteCallbackId {
        ActiveSubscriptionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: ActiveSubscriptionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Subscription>("active_subscriptions");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Subscription>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Subscription>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Subscription`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait active_subscriptionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Subscription`.
    fn active_subscriptions(&self) -> __sdk::__query_builder::Table<Subscription>;
}

impl active_subscriptionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn active_subscriptions(&self) -> __sdk::__query_builder::Table<Subscription> {
        __sdk::__query_builder::Table::new("active_subscriptions")
    }
}
