// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.7.1 (commit c1e5e2706d69e57f0539cc69c3747ebeda5a0a4e).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::category_visibility_type::CategoryVisibility;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddAndSubscribeCategoryArgs {
    pub subscriber_account_id: u64,
    pub subscriber_email: String,
    pub name: String,
    pub email_address: String,
    pub description: String,
    pub visibility: CategoryVisibility,
}

impl From<AddAndSubscribeCategoryArgs> for super::Reducer {
    fn from(args: AddAndSubscribeCategoryArgs) -> Self {
        Self::AddAndSubscribeCategory {
            subscriber_account_id: args.subscriber_account_id,
            subscriber_email: args.subscriber_email,
            name: args.name,
            email_address: args.email_address,
            description: args.description,
            visibility: args.visibility,
        }
    }
}

impl __sdk::InModule for AddAndSubscribeCategoryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_and_subscribe_category`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_and_subscribe_category {
    /// Request that the remote module invoke the reducer `add_and_subscribe_category` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`add_and_subscribe_category::add_and_subscribe_category_then`] to run a callback after the reducer completes.
    fn add_and_subscribe_category(
        &self,
        subscriber_account_id: u64,
        subscriber_email: String,
        name: String,
        email_address: String,
        description: String,
        visibility: CategoryVisibility,
    ) -> __sdk::Result<()> {
        self.add_and_subscribe_category_then(
            subscriber_account_id,
            subscriber_email,
            name,
            email_address,
            description,
            visibility,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `add_and_subscribe_category` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_and_subscribe_category_then(
        &self,
        subscriber_account_id: u64,
        subscriber_email: String,
        name: String,
        email_address: String,
        description: String,
        visibility: CategoryVisibility,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_and_subscribe_category for super::RemoteReducers {
    fn add_and_subscribe_category_then(
        &self,
        subscriber_account_id: u64,
        subscriber_email: String,
        name: String,
        email_address: String,
        description: String,
        visibility: CategoryVisibility,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddAndSubscribeCategoryArgs {
                subscriber_account_id,
                subscriber_email,
                name,
                email_address,
                description,
                visibility,
            },
            callback,
        )
    }
}
