// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit 73145eb5edc0e8f29cf67afc35a274ab307e0f1c).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct CancelMailDeliveryRetryArgs {
    pub delivery_id: String,
}

impl From<CancelMailDeliveryRetryArgs> for super::Reducer {
    fn from(args: CancelMailDeliveryRetryArgs) -> Self {
        Self::CancelMailDeliveryRetry {
            delivery_id: args.delivery_id,
        }
    }
}

impl __sdk::InModule for CancelMailDeliveryRetryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `cancel_mail_delivery_retry`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait cancel_mail_delivery_retry {
    /// Request that the remote module invoke the reducer `cancel_mail_delivery_retry` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`cancel_mail_delivery_retry::cancel_mail_delivery_retry_then`] to run a callback after the reducer completes.
    fn cancel_mail_delivery_retry(&self, delivery_id: String) -> __sdk::Result<()> {
        self.cancel_mail_delivery_retry_then(delivery_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `cancel_mail_delivery_retry` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn cancel_mail_delivery_retry_then(
        &self,
        delivery_id: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl cancel_mail_delivery_retry for super::RemoteReducers {
    fn cancel_mail_delivery_retry_then(
        &self,
        delivery_id: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(CancelMailDeliveryRetryArgs { delivery_id }, callback)
    }
}
