// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct CategoryMessageCount {
    pub category_id: u64,
    pub count: u64,
}

impl __sdk::InModule for CategoryMessageCount {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `CategoryMessageCount`.
///
/// Provides typed access to columns for query building.
pub struct CategoryMessageCountCols {
    pub category_id: __sdk::__query_builder::Col<CategoryMessageCount, u64>,
    pub count: __sdk::__query_builder::Col<CategoryMessageCount, u64>,
}

impl __sdk::__query_builder::HasCols for CategoryMessageCount {
    type Cols = CategoryMessageCountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        CategoryMessageCountCols {
            category_id: __sdk::__query_builder::Col::new(table_name, "category_id"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
        }
    }
}
