// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::category_message_count_type::CategoryMessageCount;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `category_message_counts`.
///
/// Obtain a handle from the [`CategoryMessageCountsTableAccess::category_message_counts`] method on [`super::RemoteTables`],
/// like `ctx.db.category_message_counts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.category_message_counts().on_insert(...)`.
pub struct CategoryMessageCountsTableHandle<'ctx> {
    imp: __sdk::TableHandle<CategoryMessageCount>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `category_message_counts`.
pub struct CategoryMessageCountsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for CategoryMessageCountsTableAccessor {
    type Row = CategoryMessageCount;
    type Handle<'db> = CategoryMessageCountsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.category_message_counts()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `category_message_counts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait CategoryMessageCountsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`CategoryMessageCountsTableHandle`], which mediates access to the table `category_message_counts`.
    fn category_message_counts(&self) -> CategoryMessageCountsTableHandle<'_>;
}

impl CategoryMessageCountsTableAccess for super::RemoteTables {
    fn category_message_counts(&self) -> CategoryMessageCountsTableHandle<'_> {
        CategoryMessageCountsTableHandle {
            imp: self
                .imp
                .get_table::<CategoryMessageCount>("category_message_counts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct CategoryMessageCountsInsertCallbackId(__sdk::CallbackId);
pub struct CategoryMessageCountsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for CategoryMessageCountsTableHandle<'ctx> {
    type Row = CategoryMessageCount;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CategoryMessageCount> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for CategoryMessageCountsTableHandle<'ctx> {
    type Row = CategoryMessageCount;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CategoryMessageCount> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = CategoryMessageCountsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CategoryMessageCountsInsertCallbackId {
        CategoryMessageCountsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CategoryMessageCountsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = CategoryMessageCountsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CategoryMessageCountsDeleteCallbackId {
        CategoryMessageCountsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CategoryMessageCountsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for CategoryMessageCountsTableHandle<'ctx> {
    type InsertCallbackId = CategoryMessageCountsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CategoryMessageCountsInsertCallbackId {
        CategoryMessageCountsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: CategoryMessageCountsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for CategoryMessageCountsTableHandle<'ctx> {
    type DeleteCallbackId = CategoryMessageCountsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> CategoryMessageCountsDeleteCallbackId {
        CategoryMessageCountsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: CategoryMessageCountsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CategoryMessageCount>("category_message_counts");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CategoryMessageCount>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CategoryMessageCount>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CategoryMessageCount`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait category_message_countsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CategoryMessageCount`.
    fn category_message_counts(&self) -> __sdk::__query_builder::Table<CategoryMessageCount>;
}

impl category_message_countsQueryTableAccess for __sdk::QueryTableAccessor {
    fn category_message_counts(&self) -> __sdk::__query_builder::Table<CategoryMessageCount> {
        __sdk::__query_builder::Table::new("category_message_counts")
    }
}
