// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit e9bdb3e5f2cd8e90bb43b33f5fa54a6a9df04d27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClaimNextMailIngressArgs {}

impl From<ClaimNextMailIngressArgs> for super::Reducer {
    fn from(args: ClaimNextMailIngressArgs) -> Self {
        Self::ClaimNextMailIngress
    }
}

impl __sdk::InModule for ClaimNextMailIngressArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `claim_next_mail_ingress`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait claim_next_mail_ingress {
    /// Request that the remote module invoke the reducer `claim_next_mail_ingress` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`claim_next_mail_ingress::claim_next_mail_ingress_then`] to run a callback after the reducer completes.
    fn claim_next_mail_ingress(&self) -> __sdk::Result<()> {
        self.claim_next_mail_ingress_then(|_, _| {})
    }

    /// Request that the remote module invoke the reducer `claim_next_mail_ingress` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn claim_next_mail_ingress_then(
        &self,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl claim_next_mail_ingress for super::RemoteReducers {
    fn claim_next_mail_ingress_then(
        &self,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClaimNextMailIngressArgs {}, callback)
    }
}
