// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit 73145eb5edc0e8f29cf67afc35a274ab307e0f1c).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct ClearTopicProvisioningLockArgs {
    pub topic_id: u64,
}

impl From<ClearTopicProvisioningLockArgs> for super::Reducer {
    fn from(args: ClearTopicProvisioningLockArgs) -> Self {
        Self::ClearTopicProvisioningLock {
            topic_id: args.topic_id,
        }
    }
}

impl __sdk::InModule for ClearTopicProvisioningLockArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `clear_topic_provisioning_lock`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait clear_topic_provisioning_lock {
    /// Request that the remote module invoke the reducer `clear_topic_provisioning_lock` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`clear_topic_provisioning_lock::clear_topic_provisioning_lock_then`] to run a callback after the reducer completes.
    fn clear_topic_provisioning_lock(&self, topic_id: u64) -> __sdk::Result<()> {
        self.clear_topic_provisioning_lock_then(topic_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `clear_topic_provisioning_lock` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn clear_topic_provisioning_lock_then(
        &self,
        topic_id: u64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl clear_topic_provisioning_lock for super::RemoteReducers {
    fn clear_topic_provisioning_lock_then(
        &self,
        topic_id: u64,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(ClearTopicProvisioningLockArgs { topic_id }, callback)
    }
}
