// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit 755267c4218d91927e457feb403a2c6fcfa2d92a).

#![allow(unused, clippy::all)]

//! Dioxus v0.7 signals and hooks for SpacetimeDB integration.

use super::*;
use ::dioxus::prelude::*;
use ::dioxus::signals::SyncSignal;
use spacetimedb_sdk::{DbContext, Identity, Table, TableWithPrimaryKey};
use std::sync::{Arc, Mutex};

/// Thread-safe wrapper for the database connection.
pub type SharedConnection = Arc<DbConnection>;

/// Container for all table signals, created at root level.
#[derive(Clone)]
pub struct TableSignals {
    pub account: SyncSignal<Vec<Account>>,
    pub admin_identities: SyncSignal<Vec<AdminIdentity>>,
    pub message_categories: SyncSignal<Vec<MessageCategory>>,
    pub visible_accounts: SyncSignal<Vec<Account>>,
    pub visible_messages: SyncSignal<Vec<ReceivedMessage>>,
    pub visible_subscriptions: SyncSignal<Vec<Subscription>>,
}

/// Internal state for managing the SpacetimeDB connection.
#[derive(Clone)]
pub struct SpacetimeDbContext {
    /// The database connection (wrapped in Arc for thread-safety).
    pub connection: SyncSignal<Option<SharedConnection>>,
    /// The current connection state.
    pub state: SyncSignal<ConnectionState>,
    /// Error from the last connection attempt, if any.
    pub error: SyncSignal<Option<String>>,
    /// All table signals, created at root level.
    pub tables: TableSignals,
}

/// The current state of the SpacetimeDB connection.
#[derive(Clone, PartialEq, Eq, Debug, Default)]
pub enum ConnectionState {
    #[default]
    Disconnected,
    Connecting,
    Reconnecting {
        attempt: u32,
        delay_ms: u64,
    },
    /// Connected includes the `Identity` assigned by the server and a private access token (JWT)
    /// which can be persisted by the application for future reconnection as the same Identity.
    Connected(Identity, String),
    Error,
}

const RECONNECT_BASE_DELAY_MS: u64 = 400;
const RECONNECT_MAX_DELAY_MS: u64 = 10_000;
const RECONNECT_JITTER_MS: u64 = 300;
const MAX_RECONNECT_ATTEMPTS: u32 = 0;

#[must_use]
fn should_retry_reconnect(attempt: u32) -> bool {
    MAX_RECONNECT_ATTEMPTS == 0 || attempt <= MAX_RECONNECT_ATTEMPTS
}

#[must_use]
fn reconnect_delay_ms(attempt: u32) -> u64 {
    let shift = attempt.min(8);
    let factor = 1u64.checked_shl(shift).unwrap_or(u64::MAX);
    let base_ms = RECONNECT_BASE_DELAY_MS
        .saturating_mul(factor)
        .min(RECONNECT_MAX_DELAY_MS);
    let jitter = (u64::from(attempt).saturating_mul(137)) % RECONNECT_JITTER_MS.max(1);
    base_ms.saturating_add(jitter)
}

#[cfg(not(target_arch = "wasm32"))]
struct ThreadSleep {
    done: Arc<std::sync::atomic::AtomicBool>,
    started: bool,
    delay_ms: u64,
}

#[cfg(not(target_arch = "wasm32"))]
impl ThreadSleep {
    fn new(delay_ms: u64) -> Self {
        Self {
            done: Arc::new(std::sync::atomic::AtomicBool::new(false)),
            started: false,
            delay_ms,
        }
    }
}

#[cfg(not(target_arch = "wasm32"))]
impl std::future::Future for ThreadSleep {
    type Output = ();

    fn poll(
        mut self: std::pin::Pin<&mut Self>,
        cx: &mut std::task::Context<'_>,
    ) -> std::task::Poll<Self::Output> {
        if self.done.load(std::sync::atomic::Ordering::Acquire) {
            return std::task::Poll::Ready(());
        }

        if !self.started {
            self.started = true;
            let done = Arc::clone(&self.done);
            let delay_ms = self.delay_ms;
            let waker = cx.waker().clone();
            std::thread::spawn(move || {
                std::thread::sleep(std::time::Duration::from_millis(delay_ms));
                done.store(true, std::sync::atomic::Ordering::Release);
                waker.wake();
            });
        }

        std::task::Poll::Pending
    }
}

async fn reconnect_sleep(delay_ms: u64) {
    #[cfg(not(target_arch = "wasm32"))]
    {
        ThreadSleep::new(delay_ms).await;
    }
    #[cfg(target_arch = "wasm32")]
    {
        let _ = delay_ms;
    }
}

#[must_use]
fn is_fatal_connection_error(err: &spacetimedb_sdk::Error) -> bool {
    let msg = err.to_string().to_ascii_lowercase();
    msg.contains("unauthorized")
        || msg.contains("forbidden")
        || msg.contains("invalid credentials")
        || msg.contains("invalid token")
        || msg.contains("token expired")
}

/// Initialize the SpacetimeDB context provider at the root of your application.
///
/// This hook must be called at the root component before using any other SpacetimeDB hooks.
/// It creates all table signals at root level to ensure they outlive child components.
///
/// # Arguments
/// * `uri` - The SpacetimeDB server URI
/// * `module_name` - The module name to connect to
/// * `token` - An optional OpenID Connect compliant JSON Web Token (JWT) for authentication.
///   If `None` is passed or this method is not called, SpacetimeDB will generate a new Identity
///   and sign a new private access token for the connection.
#[must_use]
pub fn use_spacetimedb_context_provider(
    uri: &str,
    module_name: &str,
    token: Option<impl ToString>,
) -> SpacetimeDbContext {
    let uri = uri.to_string();
    let module_name = module_name.to_string();
    let token = token.map(|t| t.to_string());
    let active_token: Arc<Mutex<Option<String>>> = Arc::new(Mutex::new(token.clone()));

    let connection: SyncSignal<Option<SharedConnection>> = use_signal_sync(|| None);
    let state: SyncSignal<ConnectionState> = use_signal_sync(|| ConnectionState::Disconnected);
    let error: SyncSignal<Option<String>> = use_signal_sync(|| None);

    let mut table_signals = TableSignals {
        account: use_signal_sync(Vec::new),
        admin_identities: use_signal_sync(Vec::new),
        message_categories: use_signal_sync(Vec::new),
        visible_accounts: use_signal_sync(Vec::new),
        visible_messages: use_signal_sync(Vec::new),
        visible_subscriptions: use_signal_sync(Vec::new),
    };

    let ctx = SpacetimeDbContext {
        connection,
        state,
        error,
        tables: table_signals.clone(),
    };

    use_context_provider(|| ctx.clone());

    use_effect(move || {
        let mut connection = connection;
        let mut state = state;
        let mut error = error;
        let uri = uri.clone();
        let module_name = module_name.clone();
        let active_token = active_token.clone();
        let table_signals = table_signals.clone();

        spawn(async move {
            let mut reconnect_attempt: u32 = 0;

            loop {
                if reconnect_attempt == 0 {
                    state.set(ConnectionState::Connecting);
                } else {
                    let delay_ms = reconnect_delay_ms(reconnect_attempt);
                    state.set(ConnectionState::Reconnecting {
                        attempt: reconnect_attempt,
                        delay_ms,
                    });
                }

                let token_for_build = active_token.lock().ok().and_then(|token| token.clone());

                let disconnect_fatal: Arc<Mutex<bool>> = Arc::new(Mutex::new(false));
                let disconnect_fatal_on_disconnect = disconnect_fatal.clone();

                let mut connection_on_disconnect = connection.clone();
                let mut state_on_disconnect = state.clone();
                let mut error_on_disconnect = error.clone();
                let mut state_on_connect = state.clone();
                let mut error_on_connect = error.clone();
                let mut table_signals_on_connect = table_signals.clone();
                let active_token_on_connect = active_token.clone();

                let conn = match DbConnection::builder()
                    .with_uri(&uri)
                    .with_database_name(&module_name)
                    .with_token(token_for_build)
                    .on_connect(move |conn, identity, token| {
                        // Populate initial rows for account
                        let current: Vec<Account> = conn.db.account().iter().collect();
                        table_signals_on_connect.account.set(current);

                        // Keep signal in sync on changes
                        conn.db.account().on_insert(move |ctx, _row| {
                            let updated: Vec<Account> = ctx.db.account().iter().collect();
                            table_signals_on_connect.account.set(updated);
                        });
                        conn.db.account().on_update(move |ctx, _old, _new| {
                            let updated: Vec<Account> = ctx.db.account().iter().collect();
                            table_signals_on_connect.account.set(updated);
                        });
                        conn.db.account().on_delete(move |ctx, _row| {
                            let updated: Vec<Account> = ctx.db.account().iter().collect();
                            table_signals_on_connect.account.set(updated);
                        });
                        // Populate initial rows for admin_identities
                        let current: Vec<AdminIdentity> =
                            conn.db.admin_identities().iter().collect();
                        table_signals_on_connect.admin_identities.set(current);

                        // Keep signal in sync on changes
                        conn.db.admin_identities().on_insert(move |ctx, _row| {
                            let updated: Vec<AdminIdentity> =
                                ctx.db.admin_identities().iter().collect();
                            table_signals_on_connect.admin_identities.set(updated);
                        });
                        conn.db
                            .admin_identities()
                            .on_update(move |ctx, _old, _new| {
                                let updated: Vec<AdminIdentity> =
                                    ctx.db.admin_identities().iter().collect();
                                table_signals_on_connect.admin_identities.set(updated);
                            });
                        conn.db.admin_identities().on_delete(move |ctx, _row| {
                            let updated: Vec<AdminIdentity> =
                                ctx.db.admin_identities().iter().collect();
                            table_signals_on_connect.admin_identities.set(updated);
                        });
                        // Populate initial rows for message_categories
                        let current: Vec<MessageCategory> =
                            conn.db.message_categories().iter().collect();
                        table_signals_on_connect.message_categories.set(current);

                        // Keep signal in sync on changes
                        conn.db.message_categories().on_insert(move |ctx, _row| {
                            let updated: Vec<MessageCategory> =
                                ctx.db.message_categories().iter().collect();
                            table_signals_on_connect.message_categories.set(updated);
                        });
                        conn.db
                            .message_categories()
                            .on_update(move |ctx, _old, _new| {
                                let updated: Vec<MessageCategory> =
                                    ctx.db.message_categories().iter().collect();
                                table_signals_on_connect.message_categories.set(updated);
                            });
                        conn.db.message_categories().on_delete(move |ctx, _row| {
                            let updated: Vec<MessageCategory> =
                                ctx.db.message_categories().iter().collect();
                            table_signals_on_connect.message_categories.set(updated);
                        });
                        // Populate initial rows for visible_accounts
                        let current: Vec<Account> = conn.db.visible_accounts().iter().collect();
                        table_signals_on_connect.visible_accounts.set(current);

                        // Keep signal in sync on changes
                        conn.db.visible_accounts().on_insert(move |ctx, _row| {
                            let updated: Vec<Account> = ctx.db.visible_accounts().iter().collect();
                            table_signals_on_connect.visible_accounts.set(updated);
                        });
                        conn.db.visible_accounts().on_delete(move |ctx, _row| {
                            let updated: Vec<Account> = ctx.db.visible_accounts().iter().collect();
                            table_signals_on_connect.visible_accounts.set(updated);
                        });
                        // Populate initial rows for visible_messages
                        let current: Vec<ReceivedMessage> =
                            conn.db.visible_messages().iter().collect();
                        table_signals_on_connect.visible_messages.set(current);

                        // Keep signal in sync on changes
                        conn.db.visible_messages().on_insert(move |ctx, _row| {
                            let updated: Vec<ReceivedMessage> =
                                ctx.db.visible_messages().iter().collect();
                            table_signals_on_connect.visible_messages.set(updated);
                        });
                        conn.db.visible_messages().on_delete(move |ctx, _row| {
                            let updated: Vec<ReceivedMessage> =
                                ctx.db.visible_messages().iter().collect();
                            table_signals_on_connect.visible_messages.set(updated);
                        });
                        // Populate initial rows for visible_subscriptions
                        let current: Vec<Subscription> =
                            conn.db.visible_subscriptions().iter().collect();
                        table_signals_on_connect.visible_subscriptions.set(current);

                        // Keep signal in sync on changes
                        conn.db.visible_subscriptions().on_insert(move |ctx, _row| {
                            let updated: Vec<Subscription> =
                                ctx.db.visible_subscriptions().iter().collect();
                            table_signals_on_connect.visible_subscriptions.set(updated);
                        });
                        conn.db.visible_subscriptions().on_delete(move |ctx, _row| {
                            let updated: Vec<Subscription> =
                                ctx.db.visible_subscriptions().iter().collect();
                            table_signals_on_connect.visible_subscriptions.set(updated);
                        });
                        if let Ok(mut token_store) = active_token_on_connect.lock() {
                            *token_store = Some(token.to_string());
                        }

                        // Store the assigned Identity and private access token in state so the app
                        // can persist the token (JWT) and reuse it for future reconnections via `with_token`.
                        error_on_connect.set(None);
                        state_on_connect
                            .set(ConnectionState::Connected(identity, token.to_string()));
                    })
                    .on_disconnect(move |_ctx, err: Option<spacetimedb_sdk::Error>| {
                        connection_on_disconnect.set(None);
                        if let Some(e) = err {
                            error_on_disconnect.set(Some::<String>(e.to_string()));
                            if is_fatal_connection_error(&e) {
                                if let Ok(mut fatal) = disconnect_fatal_on_disconnect.lock() {
                                    *fatal = true;
                                }
                            }
                        }
                        state_on_disconnect.set(ConnectionState::Disconnected);
                    })
                    .build()
                    .await
                {
                    Ok(conn) => conn,
                    Err(e) => {
                        connection.set(None);
                        error.set(Some::<String>(e.to_string()));
                        if is_fatal_connection_error(&e) {
                            state.set(ConnectionState::Error);
                            break;
                        }
                        reconnect_attempt = reconnect_attempt.saturating_add(1);
                        if !should_retry_reconnect(reconnect_attempt) {
                            state.set(ConnectionState::Error);
                            break;
                        }
                        let delay_ms = reconnect_delay_ms(reconnect_attempt);
                        state.set(ConnectionState::Reconnecting {
                            attempt: reconnect_attempt,
                            delay_ms,
                        });
                        reconnect_sleep(delay_ms).await;
                        continue;
                    }
                };

                let shared_conn: Arc<DbConnection> = Arc::new(conn);
                connection.set(Some(shared_conn.clone()));
                reconnect_attempt = 0;

                let run_result = shared_conn.run_async().await;
                connection.set(None);

                let disconnected_with_fatal_error = disconnect_fatal
                    .lock()
                    .ok()
                    .map(|fatal| *fatal)
                    .unwrap_or(false);
                if disconnected_with_fatal_error {
                    state.set(ConnectionState::Error);
                    break;
                }

                if let Err(e) = run_result {
                    error.set(Some::<String>(e.to_string()));
                    if is_fatal_connection_error(&e) {
                        state.set(ConnectionState::Error);
                        break;
                    }
                }

                reconnect_attempt = reconnect_attempt.saturating_add(1);
                if !should_retry_reconnect(reconnect_attempt) {
                    state.set(ConnectionState::Error);
                    break;
                }

                let delay_ms = reconnect_delay_ms(reconnect_attempt);
                state.set(ConnectionState::Reconnecting {
                    attempt: reconnect_attempt,
                    delay_ms,
                });
                reconnect_sleep(delay_ms).await;
            }
        });
    });

    ctx
}

/// Get the SpacetimeDB context from a parent component.
#[must_use]
pub fn use_spacetimedb_context() -> SpacetimeDbContext {
    use_context::<SpacetimeDbContext>()
}

/// Get the current database connection, if connected.
#[must_use]
pub fn use_connection() -> SyncSignal<Option<SharedConnection>> {
    let ctx = use_spacetimedb_context();
    ctx.connection
}

/// Subscribe to a set of SQL queries.
///
/// Re-subscribes automatically whenever the connection instance changes
/// (initial connect, or reconnect after a network interruption).
/// Avoids duplicate subscriptions while the connection is stable.
/// Subscription errors are printed to stderr for diagnosis.
pub fn use_subscription(queries: &[&str]) {
    let queries: Vec<String> = queries.iter().map(|s| s.to_string()).collect();
    let conn_signal = use_connection();

    // Stores the Arc pointer of the last successfully-subscribed connection.
    // Using peek() inside the effect keeps this read non-reactive (no infinite loop).
    let last_conn: SyncSignal<Option<SharedConnection>> = use_signal_sync(|| None);

    use_effect(move || {
        // transition (None->Some on connect, Some->None on disconnect, Some(a)->Some(b) on reconnect).
        let current = conn_signal();
        let mut last = last_conn;

        match current.as_ref() {
            None => {
                // Connection lost: clear the tracker so the next connection
                // instance will trigger a fresh subscribe.
                // peek() avoids creating a reactive dependency that would loop.
                if last.peek().is_some() {
                    last.set(None);
                }
            }
            Some(conn) => {
                // peek() reads last without subscribing to it reactively.
                if last
                    .peek()
                    .as_ref()
                    .map(|prev| Arc::ptr_eq(prev, conn))
                    .unwrap_or(false)
                {
                    // Same connection instance – already subscribed, nothing to do.
                    return;
                }
                // New or reconnected instance – store it and subscribe.
                last.set(Some(conn.clone()));
                let queries = queries.clone();
                conn.subscription_builder()
                    .on_applied(|_ctx| {})
                    .on_error(|_ctx, err| {
                        eprintln!("[spacetimedb] subscription error: {err}");
                    })
                    .subscribe(queries);
            }
        }
    });
}

// --- Table hooks ---

/// Get a reactive signal containing all rows of the `account` table.
#[must_use]
pub fn use_table_account() -> SyncSignal<Vec<Account>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.account
}

/// Get a reactive signal containing all rows of the `admin_identities` table.
#[must_use]
pub fn use_table_admin_identities() -> SyncSignal<Vec<AdminIdentity>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.admin_identities
}

/// Get a reactive signal containing all rows of the `message_categories` table.
#[must_use]
pub fn use_table_message_categories() -> SyncSignal<Vec<MessageCategory>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.message_categories
}

/// Get a reactive signal containing all rows of the `visible_accounts` table.
#[must_use]
pub fn use_table_visible_accounts() -> SyncSignal<Vec<Account>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.visible_accounts
}

/// Get a reactive signal containing all rows of the `visible_messages` table.
#[must_use]
pub fn use_table_visible_messages() -> SyncSignal<Vec<ReceivedMessage>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.visible_messages
}

/// Get a reactive signal containing all rows of the `visible_subscriptions` table.
#[must_use]
pub fn use_table_visible_subscriptions() -> SyncSignal<Vec<Subscription>> {
    let ctx = use_spacetimedb_context();
    ctx.tables.visible_subscriptions
}

// --- Reducer hooks ---

/// Get a callback to invoke the `add_message_category` reducer.
#[must_use]
pub fn use_reducer_add_message_category(
) -> impl Fn(String, String, String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |name: String, email_address: String, description: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers
                .add_message_category(name, email_address, description)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `add_subscription` reducer.
#[must_use]
pub fn use_reducer_add_subscription(
) -> impl Fn(u64, String, u64) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |subscriber_account_id: u64, subscriber_email: String, category_id: u64| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers
                .add_subscription(subscriber_account_id, subscriber_email, category_id)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `block_ip` reducer.
#[must_use]
pub fn use_reducer_block_ip(
) -> impl Fn(String, String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |ip: String, reason: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.block_ip(ip, reason)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `dump_mta_logs_to_server_logs` reducer.
#[must_use]
pub fn use_reducer_dump_mta_logs_to_server_logs(
) -> impl Fn() -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move || {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.dump_mta_logs_to_server_logs()
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `handle_mta_hook` reducer.
#[must_use]
pub fn use_reducer_handle_mta_hook(
) -> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |hook_data: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.handle_mta_hook(hook_data)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `register_admin_identity` reducer.
#[must_use]
pub fn use_reducer_register_admin_identity(
) -> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |identity_hex: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.register_admin_identity(identity_hex)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `remove_message_category` reducer.
#[must_use]
pub fn use_reducer_remove_message_category(
) -> impl Fn(u64) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |category_id: u64| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.remove_message_category(category_id)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `remove_subscription` reducer.
#[must_use]
pub fn use_reducer_remove_subscription(
) -> impl Fn(u64) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |subscription_id: u64| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.remove_subscription(subscription_id)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `sync_user` reducer.
#[must_use]
pub fn use_reducer_sync_user(
) -> impl Fn(String, String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |action: String, user_data: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.sync_user(action, user_data)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

/// Get a callback to invoke the `unregister_admin_identity` reducer.
#[must_use]
pub fn use_reducer_unregister_admin_identity(
) -> impl Fn(String) -> spacetimedb_sdk::Result<()> + Clone + 'static {
    let conn_signal = use_connection();

    move |identity_hex: String| {
        if let Some(conn) = conn_signal().as_ref() {
            conn.reducers.unregister_admin_identity(identity_hex)
        } else {
            Err(spacetimedb_sdk::Error::Disconnected)
        }
    }
}

// --- Procedure hooks ---

/// Invoke the `provision_message_category` procedure and get a reactive signal for its result.
///
/// Returns `(invoke, result)`. Calling `invoke(...)` sends the procedure call to the server.
/// The `result` signal is updated to `Some(Ok(value))` on success or `Some(Err(message))`
/// on failure once the server responds.
#[must_use]
pub fn use_procedure_provision_message_category() -> (
    impl Fn(String, String, String) + Clone + 'static,
    SyncSignal<Option<Result<Result<(), String>, String>>>,
) {
    let conn_signal = use_connection();
    let result: SyncSignal<Option<Result<Result<(), String>, String>>> = use_signal_sync(|| None);

    let invoke = move |name: String, email_address: String, description: String| {
        if let Some(conn) = conn_signal().as_ref() {
            let mut result = result;
            conn.procedures.provision_message_category_then(
                name,
                email_address,
                description,
                move |_ctx, res| {
                    result.set(Some(res.map_err(|e| e.to_string())));
                },
            );
        }
    };

    (invoke, result)
}

// --- Connection state hooks ---

/// Get a reactive signal for the current connection state.
#[must_use]
pub fn use_connection_state() -> SyncSignal<ConnectionState> {
    let ctx = use_spacetimedb_context();
    ctx.state
}

/// Get a reactive signal for the current connection error, if any.
#[must_use]
pub fn use_connection_error() -> SyncSignal<Option<String>> {
    let ctx = use_spacetimedb_context();
    ctx.error
}
