// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.4.1 (commit 5e5e941b7b9a98e1d77cf7a267c1aeb93d43d02c).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct HandleMtaHookArgs {
    pub hook_data: String,
}

impl From<HandleMtaHookArgs> for super::Reducer {
    fn from(args: HandleMtaHookArgs) -> Self {
        Self::HandleMtaHook {
            hook_data: args.hook_data,
        }
    }
}

impl __sdk::InModule for HandleMtaHookArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `handle_mta_hook`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait handle_mta_hook {
    /// Request that the remote module invoke the reducer `handle_mta_hook` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`handle_mta_hook::handle_mta_hook_then`] to run a callback after the reducer completes.
    fn handle_mta_hook(&self, hook_data: String) -> __sdk::Result<()> {
        self.handle_mta_hook_then(hook_data, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `handle_mta_hook` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn handle_mta_hook_then(
        &self,
        hook_data: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl handle_mta_hook for super::RemoteReducers {
    fn handle_mta_hook_then(
        &self,
        hook_data: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(HandleMtaHookArgs { hook_data }, callback)
    }
}
