// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.2 (commit eea2de269164e025c641bf5041c8d85eba3d8a6e).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct IncrementMailIngressFailedDeliveryCountArgs {
    pub ingress_id: String,
    pub instance_id: String,
}

impl From<IncrementMailIngressFailedDeliveryCountArgs> for super::Reducer {
    fn from(args: IncrementMailIngressFailedDeliveryCountArgs) -> Self {
        Self::IncrementMailIngressFailedDeliveryCount {
            ingress_id: args.ingress_id,
            instance_id: args.instance_id,
        }
    }
}

impl __sdk::InModule for IncrementMailIngressFailedDeliveryCountArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `increment_mail_ingress_failed_delivery_count`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait increment_mail_ingress_failed_delivery_count {
    /// Request that the remote module invoke the reducer `increment_mail_ingress_failed_delivery_count` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`increment_mail_ingress_failed_delivery_count::increment_mail_ingress_failed_delivery_count_then`] to run a callback after the reducer completes.
    fn increment_mail_ingress_failed_delivery_count(
        &self,
        ingress_id: String,
        instance_id: String,
    ) -> __sdk::Result<()> {
        self.increment_mail_ingress_failed_delivery_count_then(ingress_id, instance_id, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `increment_mail_ingress_failed_delivery_count` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn increment_mail_ingress_failed_delivery_count_then(
        &self,
        ingress_id: String,
        instance_id: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl increment_mail_ingress_failed_delivery_count for super::RemoteReducers {
    fn increment_mail_ingress_failed_delivery_count_then(
        &self,
        ingress_id: String,
        instance_id: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            IncrementMailIngressFailedDeliveryCountArgs {
                ingress_id,
                instance_id,
            },
            callback,
        )
    }
}
