// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit e9bdb3e5f2cd8e90bb43b33f5fa54a6a9df04d27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct MarkMailDeliverySentArgs {
    pub delivery_id: String,
    pub smtp_status_code: Option<u16>,
    pub smtp_response: String,
}

impl From<MarkMailDeliverySentArgs> for super::Reducer {
    fn from(args: MarkMailDeliverySentArgs) -> Self {
        Self::MarkMailDeliverySent {
            delivery_id: args.delivery_id,
            smtp_status_code: args.smtp_status_code,
            smtp_response: args.smtp_response,
        }
    }
}

impl __sdk::InModule for MarkMailDeliverySentArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `mark_mail_delivery_sent`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait mark_mail_delivery_sent {
    /// Request that the remote module invoke the reducer `mark_mail_delivery_sent` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`mark_mail_delivery_sent::mark_mail_delivery_sent_then`] to run a callback after the reducer completes.
    fn mark_mail_delivery_sent(
        &self,
        delivery_id: String,
        smtp_status_code: Option<u16>,
        smtp_response: String,
    ) -> __sdk::Result<()> {
        self.mark_mail_delivery_sent_then(delivery_id, smtp_status_code, smtp_response, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `mark_mail_delivery_sent` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn mark_mail_delivery_sent_then(
        &self,
        delivery_id: String,
        smtp_status_code: Option<u16>,
        smtp_response: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl mark_mail_delivery_sent for super::RemoteReducers {
    fn mark_mail_delivery_sent_then(
        &self,
        delivery_id: String,
        smtp_status_code: Option<u16>,
        smtp_response: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            MarkMailDeliverySentArgs {
                delivery_id,
                smtp_status_code,
                smtp_response,
            },
            callback,
        )
    }
}
