// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MessageTopicCategory {
    pub id: u64,
    pub topic_id: u64,
    pub category_id: u64,
}

impl __sdk::InModule for MessageTopicCategory {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MessageTopicCategory`.
///
/// Provides typed access to columns for query building.
pub struct MessageTopicCategoryCols {
    pub id: __sdk::__query_builder::Col<MessageTopicCategory, u64>,
    pub topic_id: __sdk::__query_builder::Col<MessageTopicCategory, u64>,
    pub category_id: __sdk::__query_builder::Col<MessageTopicCategory, u64>,
}

impl __sdk::__query_builder::HasCols for MessageTopicCategory {
    type Cols = MessageTopicCategoryCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageTopicCategoryCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            topic_id: __sdk::__query_builder::Col::new(table_name, "topic_id"),
            category_id: __sdk::__query_builder::Col::new(table_name, "category_id"),
        }
    }
}

/// Indexed column accessor struct for the table `MessageTopicCategory`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageTopicCategoryIxCols {
    pub category_id: __sdk::__query_builder::IxCol<MessageTopicCategory, u64>,
    pub id: __sdk::__query_builder::IxCol<MessageTopicCategory, u64>,
    pub topic_id: __sdk::__query_builder::IxCol<MessageTopicCategory, u64>,
}

impl __sdk::__query_builder::HasIxCols for MessageTopicCategory {
    type IxCols = MessageTopicCategoryIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageTopicCategoryIxCols {
            category_id: __sdk::__query_builder::IxCol::new(table_name, "category_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            topic_id: __sdk::__query_builder::IxCol::new(table_name, "topic_id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MessageTopicCategory {}
