// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

use super::subscription_permission_type::SubscriptionPermission;
use super::topic_visibility_type::TopicVisibility;

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MessageTopic {
    pub id: u64,
    pub name: String,
    pub email_address: String,
    pub description: String,
    pub active: bool,
    pub visibility: TopicVisibility,
    pub app_password_id: Option<u64>,
    pub default_permission: SubscriptionPermission,
    pub locked_is_provisioning: bool,
}

impl __sdk::InModule for MessageTopic {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MessageTopic`.
///
/// Provides typed access to columns for query building.
pub struct MessageTopicCols {
    pub id: __sdk::__query_builder::Col<MessageTopic, u64>,
    pub name: __sdk::__query_builder::Col<MessageTopic, String>,
    pub email_address: __sdk::__query_builder::Col<MessageTopic, String>,
    pub description: __sdk::__query_builder::Col<MessageTopic, String>,
    pub active: __sdk::__query_builder::Col<MessageTopic, bool>,
    pub visibility: __sdk::__query_builder::Col<MessageTopic, TopicVisibility>,
    pub app_password_id: __sdk::__query_builder::Col<MessageTopic, Option<u64>>,
    pub default_permission: __sdk::__query_builder::Col<MessageTopic, SubscriptionPermission>,
    pub locked_is_provisioning: __sdk::__query_builder::Col<MessageTopic, bool>,
}

impl __sdk::__query_builder::HasCols for MessageTopic {
    type Cols = MessageTopicCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MessageTopicCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            email_address: __sdk::__query_builder::Col::new(table_name, "email_address"),
            description: __sdk::__query_builder::Col::new(table_name, "description"),
            active: __sdk::__query_builder::Col::new(table_name, "active"),
            visibility: __sdk::__query_builder::Col::new(table_name, "visibility"),
            app_password_id: __sdk::__query_builder::Col::new(table_name, "app_password_id"),
            default_permission: __sdk::__query_builder::Col::new(table_name, "default_permission"),
            locked_is_provisioning: __sdk::__query_builder::Col::new(
                table_name,
                "locked_is_provisioning",
            ),
        }
    }
}

/// Indexed column accessor struct for the table `MessageTopic`.
///
/// Provides typed access to indexed columns for query building.
pub struct MessageTopicIxCols {
    pub app_password_id: __sdk::__query_builder::IxCol<MessageTopic, Option<u64>>,
    pub email_address: __sdk::__query_builder::IxCol<MessageTopic, String>,
    pub id: __sdk::__query_builder::IxCol<MessageTopic, u64>,
    pub visibility: __sdk::__query_builder::IxCol<MessageTopic, TopicVisibility>,
}

impl __sdk::__query_builder::HasIxCols for MessageTopic {
    type IxCols = MessageTopicIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MessageTopicIxCols {
            app_password_id: __sdk::__query_builder::IxCol::new(table_name, "app_password_id"),
            email_address: __sdk::__query_builder::IxCol::new(table_name, "email_address"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            visibility: __sdk::__query_builder::IxCol::new(table_name, "visibility"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MessageTopic {}
