// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct MtaConnectionLog {
    pub id: u64,
    pub client_ip: String,
    pub stage: String,
    pub action: String,
    pub timestamp: __sdk::Timestamp,
    pub details: String,
}

impl __sdk::InModule for MtaConnectionLog {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `MtaConnectionLog`.
///
/// Provides typed access to columns for query building.
pub struct MtaConnectionLogCols {
    pub id: __sdk::__query_builder::Col<MtaConnectionLog, u64>,
    pub client_ip: __sdk::__query_builder::Col<MtaConnectionLog, String>,
    pub stage: __sdk::__query_builder::Col<MtaConnectionLog, String>,
    pub action: __sdk::__query_builder::Col<MtaConnectionLog, String>,
    pub timestamp: __sdk::__query_builder::Col<MtaConnectionLog, __sdk::Timestamp>,
    pub details: __sdk::__query_builder::Col<MtaConnectionLog, String>,
}

impl __sdk::__query_builder::HasCols for MtaConnectionLog {
    type Cols = MtaConnectionLogCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        MtaConnectionLogCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            client_ip: __sdk::__query_builder::Col::new(table_name, "client_ip"),
            stage: __sdk::__query_builder::Col::new(table_name, "stage"),
            action: __sdk::__query_builder::Col::new(table_name, "action"),
            timestamp: __sdk::__query_builder::Col::new(table_name, "timestamp"),
            details: __sdk::__query_builder::Col::new(table_name, "details"),
        }
    }
}

/// Indexed column accessor struct for the table `MtaConnectionLog`.
///
/// Provides typed access to indexed columns for query building.
pub struct MtaConnectionLogIxCols {
    pub id: __sdk::__query_builder::IxCol<MtaConnectionLog, u64>,
}

impl __sdk::__query_builder::HasIxCols for MtaConnectionLog {
    type IxCols = MtaConnectionLogIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        MtaConnectionLogIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for MtaConnectionLog {}
