// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
struct ProvisionAllUnprovisionedTopicsArgs {}

impl __sdk::InModule for ProvisionAllUnprovisionedTopicsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the procedure `provision_all_unprovisioned_topics`.
///
/// Implemented for [`super::RemoteProcedures`].
pub trait provision_all_unprovisioned_topics {
    fn provision_all_unprovisioned_topics(&self) {
        self.provision_all_unprovisioned_topics_then(|_, _| {});
    }

    fn provision_all_unprovisioned_topics_then(
        &self,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<u32, String>, __sdk::InternalError>)
            + Send
            + 'static,
    );
}

impl provision_all_unprovisioned_topics for super::RemoteProcedures {
    fn provision_all_unprovisioned_topics_then(
        &self,

        __callback: impl FnOnce(&super::ProcedureEventContext, Result<Result<u32, String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) {
        self.imp
            .invoke_procedure_with_callback::<_, Result<u32, String>>(
                "provision_all_unprovisioned_topics",
                ProvisionAllUnprovisionedTopicsArgs {},
                __callback,
            );
    }
}
