// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct ReceivedMessage {
    pub id: u64,
    pub mail_message_id: u64,
    pub category_id: u64,
    pub category_email: String,
    pub received_at: __sdk::Timestamp,
}

impl __sdk::InModule for ReceivedMessage {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `ReceivedMessage`.
///
/// Provides typed access to columns for query building.
pub struct ReceivedMessageCols {
    pub id: __sdk::__query_builder::Col<ReceivedMessage, u64>,
    pub mail_message_id: __sdk::__query_builder::Col<ReceivedMessage, u64>,
    pub category_id: __sdk::__query_builder::Col<ReceivedMessage, u64>,
    pub category_email: __sdk::__query_builder::Col<ReceivedMessage, String>,
    pub received_at: __sdk::__query_builder::Col<ReceivedMessage, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for ReceivedMessage {
    type Cols = ReceivedMessageCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        ReceivedMessageCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            mail_message_id: __sdk::__query_builder::Col::new(table_name, "mail_message_id"),
            category_id: __sdk::__query_builder::Col::new(table_name, "category_id"),
            category_email: __sdk::__query_builder::Col::new(table_name, "category_email"),
            received_at: __sdk::__query_builder::Col::new(table_name, "received_at"),
        }
    }
}

/// Indexed column accessor struct for the table `ReceivedMessage`.
///
/// Provides typed access to indexed columns for query building.
pub struct ReceivedMessageIxCols {
    pub category_id: __sdk::__query_builder::IxCol<ReceivedMessage, u64>,
    pub id: __sdk::__query_builder::IxCol<ReceivedMessage, u64>,
    pub mail_message_id: __sdk::__query_builder::IxCol<ReceivedMessage, u64>,
    pub received_at: __sdk::__query_builder::IxCol<ReceivedMessage, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasIxCols for ReceivedMessage {
    type IxCols = ReceivedMessageIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        ReceivedMessageIxCols {
            category_id: __sdk::__query_builder::IxCol::new(table_name, "category_id"),
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            mail_message_id: __sdk::__query_builder::IxCol::new(table_name, "mail_message_id"),
            received_at: __sdk::__query_builder::IxCol::new(table_name, "received_at"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for ReceivedMessage {}
