// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::requeue_temporary_failed_mails_schedule_type::RequeueTemporaryFailedMailsSchedule;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `requeue_temporary_failed_mails_schedule`.
///
/// Obtain a handle from the [`RequeueTemporaryFailedMailsScheduleTableAccess::requeue_temporary_failed_mails_schedule`] method on [`super::RemoteTables`],
/// like `ctx.db.requeue_temporary_failed_mails_schedule()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.requeue_temporary_failed_mails_schedule().on_insert(...)`.
pub struct RequeueTemporaryFailedMailsScheduleTableHandle<'ctx> {
    imp: __sdk::TableHandle<RequeueTemporaryFailedMailsSchedule>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `requeue_temporary_failed_mails_schedule`.
pub struct RequeueTemporaryFailedMailsScheduleTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables>
    for RequeueTemporaryFailedMailsScheduleTableAccessor
{
    type Row = RequeueTemporaryFailedMailsSchedule;
    type Handle<'db> = RequeueTemporaryFailedMailsScheduleTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.requeue_temporary_failed_mails_schedule()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `requeue_temporary_failed_mails_schedule`.
///
/// Implemented for [`super::RemoteTables`].
pub trait RequeueTemporaryFailedMailsScheduleTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`RequeueTemporaryFailedMailsScheduleTableHandle`], which mediates access to the table `requeue_temporary_failed_mails_schedule`.
    fn requeue_temporary_failed_mails_schedule(
        &self,
    ) -> RequeueTemporaryFailedMailsScheduleTableHandle<'_>;
}

impl RequeueTemporaryFailedMailsScheduleTableAccess for super::RemoteTables {
    fn requeue_temporary_failed_mails_schedule(
        &self,
    ) -> RequeueTemporaryFailedMailsScheduleTableHandle<'_> {
        RequeueTemporaryFailedMailsScheduleTableHandle {
            imp: self.imp.get_table::<RequeueTemporaryFailedMailsSchedule>(
                "requeue_temporary_failed_mails_schedule",
            ),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct RequeueTemporaryFailedMailsScheduleInsertCallbackId(__sdk::CallbackId);
pub struct RequeueTemporaryFailedMailsScheduleDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for RequeueTemporaryFailedMailsScheduleTableHandle<'ctx> {
    type Row = RequeueTemporaryFailedMailsSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RequeueTemporaryFailedMailsSchedule> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for RequeueTemporaryFailedMailsScheduleTableHandle<'ctx> {
    type Row = RequeueTemporaryFailedMailsSchedule;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = RequeueTemporaryFailedMailsSchedule> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = RequeueTemporaryFailedMailsScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RequeueTemporaryFailedMailsScheduleInsertCallbackId {
        RequeueTemporaryFailedMailsScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RequeueTemporaryFailedMailsScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = RequeueTemporaryFailedMailsScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RequeueTemporaryFailedMailsScheduleDeleteCallbackId {
        RequeueTemporaryFailedMailsScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RequeueTemporaryFailedMailsScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for RequeueTemporaryFailedMailsScheduleTableHandle<'ctx> {
    type InsertCallbackId = RequeueTemporaryFailedMailsScheduleInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RequeueTemporaryFailedMailsScheduleInsertCallbackId {
        RequeueTemporaryFailedMailsScheduleInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: RequeueTemporaryFailedMailsScheduleInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for RequeueTemporaryFailedMailsScheduleTableHandle<'ctx> {
    type DeleteCallbackId = RequeueTemporaryFailedMailsScheduleDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> RequeueTemporaryFailedMailsScheduleDeleteCallbackId {
        RequeueTemporaryFailedMailsScheduleDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: RequeueTemporaryFailedMailsScheduleDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct RequeueTemporaryFailedMailsScheduleUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for RequeueTemporaryFailedMailsScheduleTableHandle<'ctx> {
    type UpdateCallbackId = RequeueTemporaryFailedMailsScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RequeueTemporaryFailedMailsScheduleUpdateCallbackId {
        RequeueTemporaryFailedMailsScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RequeueTemporaryFailedMailsScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for RequeueTemporaryFailedMailsScheduleTableHandle<'ctx> {
    type UpdateCallbackId = RequeueTemporaryFailedMailsScheduleUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> RequeueTemporaryFailedMailsScheduleUpdateCallbackId {
        RequeueTemporaryFailedMailsScheduleUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: RequeueTemporaryFailedMailsScheduleUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `scheduled_id` unique index on the table `requeue_temporary_failed_mails_schedule`,
/// which allows point queries on the field of the same name
/// via the [`RequeueTemporaryFailedMailsScheduleScheduledIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.requeue_temporary_failed_mails_schedule().scheduled_id().find(...)`.
pub struct RequeueTemporaryFailedMailsScheduleScheduledIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<RequeueTemporaryFailedMailsSchedule, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> RequeueTemporaryFailedMailsScheduleTableHandle<'ctx> {
    /// Get a handle on the `scheduled_id` unique index on the table `requeue_temporary_failed_mails_schedule`.
    pub fn scheduled_id(&self) -> RequeueTemporaryFailedMailsScheduleScheduledIdUnique<'ctx> {
        RequeueTemporaryFailedMailsScheduleScheduledIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("scheduled_id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> RequeueTemporaryFailedMailsScheduleScheduledIdUnique<'ctx> {
    /// Find the subscribed row whose `scheduled_id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<RequeueTemporaryFailedMailsSchedule> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<RequeueTemporaryFailedMailsSchedule>(
        "requeue_temporary_failed_mails_schedule",
    );
    _table.add_unique_constraint::<u64>("scheduled_id", |row| &row.scheduled_id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<RequeueTemporaryFailedMailsSchedule>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse(
            "TableUpdate<RequeueTemporaryFailedMailsSchedule>",
            "TableUpdate",
        )
        .with_cause(e)
        .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `RequeueTemporaryFailedMailsSchedule`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait requeue_temporary_failed_mails_scheduleQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `RequeueTemporaryFailedMailsSchedule`.
    fn requeue_temporary_failed_mails_schedule(
        &self,
    ) -> __sdk::__query_builder::Table<RequeueTemporaryFailedMailsSchedule>;
}

impl requeue_temporary_failed_mails_scheduleQueryTableAccess for __sdk::QueryTableAccessor {
    fn requeue_temporary_failed_mails_schedule(
        &self,
    ) -> __sdk::__query_builder::Table<RequeueTemporaryFailedMailsSchedule> {
        __sdk::__query_builder::Table::new("requeue_temporary_failed_mails_schedule")
    }
}
