// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit e9bdb3e5f2cd8e90bb43b33f5fa54a6a9df04d27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct RevokeWebhookTokenArgs {
    pub token_hash: String,
}

impl From<RevokeWebhookTokenArgs> for super::Reducer {
    fn from(args: RevokeWebhookTokenArgs) -> Self {
        Self::RevokeWebhookToken {
            token_hash: args.token_hash,
        }
    }
}

impl __sdk::InModule for RevokeWebhookTokenArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `revoke_webhook_token`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait revoke_webhook_token {
    /// Request that the remote module invoke the reducer `revoke_webhook_token` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`revoke_webhook_token::revoke_webhook_token_then`] to run a callback after the reducer completes.
    fn revoke_webhook_token(&self, token_hash: String) -> __sdk::Result<()> {
        self.revoke_webhook_token_then(token_hash, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `revoke_webhook_token` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn revoke_webhook_token_then(
        &self,
        token_hash: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl revoke_webhook_token for super::RemoteReducers {
    fn revoke_webhook_token_then(
        &self,
        token_hash: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(RevokeWebhookTokenArgs { token_hash }, callback)
    }
}
