// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::category_app_password_type::CategoryAppPassword;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sender_category_app_passwords`.
///
/// Obtain a handle from the [`SenderCategoryAppPasswordsTableAccess::sender_category_app_passwords`] method on [`super::RemoteTables`],
/// like `ctx.db.sender_category_app_passwords()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_category_app_passwords().on_insert(...)`.
pub struct SenderCategoryAppPasswordsTableHandle<'ctx> {
    imp: __sdk::TableHandle<CategoryAppPassword>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sender_category_app_passwords`.
pub struct SenderCategoryAppPasswordsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SenderCategoryAppPasswordsTableAccessor {
    type Row = CategoryAppPassword;
    type Handle<'db> = SenderCategoryAppPasswordsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sender_category_app_passwords()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sender_category_app_passwords`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SenderCategoryAppPasswordsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SenderCategoryAppPasswordsTableHandle`], which mediates access to the table `sender_category_app_passwords`.
    fn sender_category_app_passwords(&self) -> SenderCategoryAppPasswordsTableHandle<'_>;
}

impl SenderCategoryAppPasswordsTableAccess for super::RemoteTables {
    fn sender_category_app_passwords(&self) -> SenderCategoryAppPasswordsTableHandle<'_> {
        SenderCategoryAppPasswordsTableHandle {
            imp: self
                .imp
                .get_table::<CategoryAppPassword>("sender_category_app_passwords"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SenderCategoryAppPasswordsInsertCallbackId(__sdk::CallbackId);
pub struct SenderCategoryAppPasswordsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SenderCategoryAppPasswordsTableHandle<'ctx> {
    type Row = CategoryAppPassword;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CategoryAppPassword> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SenderCategoryAppPasswordsTableHandle<'ctx> {
    type Row = CategoryAppPassword;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CategoryAppPassword> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SenderCategoryAppPasswordsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderCategoryAppPasswordsInsertCallbackId {
        SenderCategoryAppPasswordsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderCategoryAppPasswordsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SenderCategoryAppPasswordsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderCategoryAppPasswordsDeleteCallbackId {
        SenderCategoryAppPasswordsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderCategoryAppPasswordsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SenderCategoryAppPasswordsTableHandle<'ctx> {
    type InsertCallbackId = SenderCategoryAppPasswordsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderCategoryAppPasswordsInsertCallbackId {
        SenderCategoryAppPasswordsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderCategoryAppPasswordsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SenderCategoryAppPasswordsTableHandle<'ctx> {
    type DeleteCallbackId = SenderCategoryAppPasswordsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderCategoryAppPasswordsDeleteCallbackId {
        SenderCategoryAppPasswordsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderCategoryAppPasswordsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SenderCategoryAppPasswordsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SenderCategoryAppPasswordsTableHandle<'ctx> {
    type UpdateCallbackId = SenderCategoryAppPasswordsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderCategoryAppPasswordsUpdateCallbackId {
        SenderCategoryAppPasswordsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderCategoryAppPasswordsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SenderCategoryAppPasswordsTableHandle<'ctx> {
    type UpdateCallbackId = SenderCategoryAppPasswordsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderCategoryAppPasswordsUpdateCallbackId {
        SenderCategoryAppPasswordsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderCategoryAppPasswordsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sender_category_app_passwords`,
/// which allows point queries on the field of the same name
/// via the [`SenderCategoryAppPasswordsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_category_app_passwords().id().find(...)`.
pub struct SenderCategoryAppPasswordsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<CategoryAppPassword, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SenderCategoryAppPasswordsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sender_category_app_passwords`.
    pub fn id(&self) -> SenderCategoryAppPasswordsIdUnique<'ctx> {
        SenderCategoryAppPasswordsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SenderCategoryAppPasswordsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<CategoryAppPassword> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<CategoryAppPassword>("sender_category_app_passwords");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CategoryAppPassword>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CategoryAppPassword>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CategoryAppPassword`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sender_category_app_passwordsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CategoryAppPassword`.
    fn sender_category_app_passwords(&self) -> __sdk::__query_builder::Table<CategoryAppPassword>;
}

impl sender_category_app_passwordsQueryTableAccess for __sdk::QueryTableAccessor {
    fn sender_category_app_passwords(&self) -> __sdk::__query_builder::Table<CategoryAppPassword> {
        __sdk::__query_builder::Table::new("sender_category_app_passwords")
    }
}
