// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::mail_delivery_event_type::MailDeliveryEvent;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `sender_mail_delivery_events`.
///
/// Obtain a handle from the [`SenderMailDeliveryEventsTableAccess::sender_mail_delivery_events`] method on [`super::RemoteTables`],
/// like `ctx.db.sender_mail_delivery_events()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_mail_delivery_events().on_insert(...)`.
pub struct SenderMailDeliveryEventsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MailDeliveryEvent>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `sender_mail_delivery_events`.
pub struct SenderMailDeliveryEventsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for SenderMailDeliveryEventsTableAccessor {
    type Row = MailDeliveryEvent;
    type Handle<'db> = SenderMailDeliveryEventsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.sender_mail_delivery_events()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `sender_mail_delivery_events`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SenderMailDeliveryEventsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SenderMailDeliveryEventsTableHandle`], which mediates access to the table `sender_mail_delivery_events`.
    fn sender_mail_delivery_events(&self) -> SenderMailDeliveryEventsTableHandle<'_>;
}

impl SenderMailDeliveryEventsTableAccess for super::RemoteTables {
    fn sender_mail_delivery_events(&self) -> SenderMailDeliveryEventsTableHandle<'_> {
        SenderMailDeliveryEventsTableHandle {
            imp: self
                .imp
                .get_table::<MailDeliveryEvent>("sender_mail_delivery_events"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SenderMailDeliveryEventsInsertCallbackId(__sdk::CallbackId);
pub struct SenderMailDeliveryEventsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for SenderMailDeliveryEventsTableHandle<'ctx> {
    type Row = MailDeliveryEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailDeliveryEvent> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for SenderMailDeliveryEventsTableHandle<'ctx> {
    type Row = MailDeliveryEvent;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MailDeliveryEvent> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SenderMailDeliveryEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryEventsInsertCallbackId {
        SenderMailDeliveryEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMailDeliveryEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SenderMailDeliveryEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryEventsDeleteCallbackId {
        SenderMailDeliveryEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMailDeliveryEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for SenderMailDeliveryEventsTableHandle<'ctx> {
    type InsertCallbackId = SenderMailDeliveryEventsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryEventsInsertCallbackId {
        SenderMailDeliveryEventsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SenderMailDeliveryEventsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for SenderMailDeliveryEventsTableHandle<'ctx> {
    type DeleteCallbackId = SenderMailDeliveryEventsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryEventsDeleteCallbackId {
        SenderMailDeliveryEventsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SenderMailDeliveryEventsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct SenderMailDeliveryEventsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SenderMailDeliveryEventsTableHandle<'ctx> {
    type UpdateCallbackId = SenderMailDeliveryEventsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryEventsUpdateCallbackId {
        SenderMailDeliveryEventsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMailDeliveryEventsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for SenderMailDeliveryEventsTableHandle<'ctx> {
    type UpdateCallbackId = SenderMailDeliveryEventsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SenderMailDeliveryEventsUpdateCallbackId {
        SenderMailDeliveryEventsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SenderMailDeliveryEventsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `sender_mail_delivery_events`,
/// which allows point queries on the field of the same name
/// via the [`SenderMailDeliveryEventsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.sender_mail_delivery_events().id().find(...)`.
pub struct SenderMailDeliveryEventsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MailDeliveryEvent, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SenderMailDeliveryEventsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `sender_mail_delivery_events`.
    pub fn id(&self) -> SenderMailDeliveryEventsIdUnique<'ctx> {
        SenderMailDeliveryEventsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SenderMailDeliveryEventsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MailDeliveryEvent> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MailDeliveryEvent>("sender_mail_delivery_events");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MailDeliveryEvent>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MailDeliveryEvent>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MailDeliveryEvent`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait sender_mail_delivery_eventsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MailDeliveryEvent`.
    fn sender_mail_delivery_events(&self) -> __sdk::__query_builder::Table<MailDeliveryEvent>;
}

impl sender_mail_delivery_eventsQueryTableAccess for __sdk::QueryTableAccessor {
    fn sender_mail_delivery_events(&self) -> __sdk::__query_builder::Table<MailDeliveryEvent> {
        __sdk::__query_builder::Table::new("sender_mail_delivery_events")
    }
}
