// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit 73145eb5edc0e8f29cf67afc35a274ab307e0f1c).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetStalwartConfigArgs {
    pub jmap_url: String,
    pub admin_token: String,
}

impl From<SetStalwartConfigArgs> for super::Reducer {
    fn from(args: SetStalwartConfigArgs) -> Self {
        Self::SetStalwartConfig {
            jmap_url: args.jmap_url,
            admin_token: args.admin_token,
        }
    }
}

impl __sdk::InModule for SetStalwartConfigArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_stalwart_config`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_stalwart_config {
    /// Request that the remote module invoke the reducer `set_stalwart_config` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`set_stalwart_config::set_stalwart_config_then`] to run a callback after the reducer completes.
    fn set_stalwart_config(&self, jmap_url: String, admin_token: String) -> __sdk::Result<()> {
        self.set_stalwart_config_then(jmap_url, admin_token, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_stalwart_config` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_stalwart_config_then(
        &self,
        jmap_url: String,
        admin_token: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_stalwart_config for super::RemoteReducers {
    fn set_stalwart_config_then(
        &self,
        jmap_url: String,
        admin_token: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetStalwartConfigArgs {
                jmap_url,
                admin_token,
            },
            callback,
        )
    }
}
