// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.8.2 (commit 500c80313c1fa91459f2d04776e4bee1c58e3ee1).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct SetCategoryTopicsArgs {
    pub category_id: u64,
    pub topic_names: Vec<String>,
}

impl From<SetCategoryTopicsArgs> for super::Reducer {
    fn from(args: SetCategoryTopicsArgs) -> Self {
        Self::SetCategoryTopics {
            category_id: args.category_id,
            topic_names: args.topic_names,
        }
    }
}

impl __sdk::InModule for SetCategoryTopicsArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `set_category_topics`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait set_category_topics {
    /// Request that the remote module invoke the reducer `set_category_topics` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`set_category_topics::set_category_topics_then`] to run a callback after the reducer completes.
    fn set_category_topics(&self, category_id: u64, topic_names: Vec<String>) -> __sdk::Result<()> {
        self.set_category_topics_then(category_id, topic_names, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `set_category_topics` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn set_category_topics_then(
        &self,
        category_id: u64,
        topic_names: Vec<String>,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl set_category_topics for super::RemoteReducers {
    fn set_category_topics_then(
        &self,
        category_id: u64,
        topic_names: Vec<String>,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            SetCategoryTopicsArgs {
                category_id,
                topic_names,
            },
            callback,
        )
    }
}
