// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct TopicSubscriberCount {
    pub topic_id: u64,
    pub count: u64,
}

impl __sdk::InModule for TopicSubscriberCount {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `TopicSubscriberCount`.
///
/// Provides typed access to columns for query building.
pub struct TopicSubscriberCountCols {
    pub topic_id: __sdk::__query_builder::Col<TopicSubscriberCount, u64>,
    pub count: __sdk::__query_builder::Col<TopicSubscriberCount, u64>,
}

impl __sdk::__query_builder::HasCols for TopicSubscriberCount {
    type Cols = TopicSubscriberCountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        TopicSubscriberCountCols {
            topic_id: __sdk::__query_builder::Col::new(table_name, "topic_id"),
            count: __sdk::__query_builder::Col::new(table_name, "count"),
        }
    }
}
