// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::count_row_type::CountRow;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `total_accounts`.
///
/// Obtain a handle from the [`TotalAccountsTableAccess::total_accounts`] method on [`super::RemoteTables`],
/// like `ctx.db.total_accounts()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.total_accounts().on_insert(...)`.
pub struct TotalAccountsTableHandle<'ctx> {
    imp: __sdk::TableHandle<CountRow>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `total_accounts`.
pub struct TotalAccountsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for TotalAccountsTableAccessor {
    type Row = CountRow;
    type Handle<'db> = TotalAccountsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.total_accounts()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `total_accounts`.
///
/// Implemented for [`super::RemoteTables`].
pub trait TotalAccountsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`TotalAccountsTableHandle`], which mediates access to the table `total_accounts`.
    fn total_accounts(&self) -> TotalAccountsTableHandle<'_>;
}

impl TotalAccountsTableAccess for super::RemoteTables {
    fn total_accounts(&self) -> TotalAccountsTableHandle<'_> {
        TotalAccountsTableHandle {
            imp: self.imp.get_table::<CountRow>("total_accounts"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct TotalAccountsInsertCallbackId(__sdk::CallbackId);
pub struct TotalAccountsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for TotalAccountsTableHandle<'ctx> {
    type Row = CountRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CountRow> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for TotalAccountsTableHandle<'ctx> {
    type Row = CountRow;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = CountRow> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = TotalAccountsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TotalAccountsInsertCallbackId {
        TotalAccountsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TotalAccountsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = TotalAccountsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TotalAccountsDeleteCallbackId {
        TotalAccountsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TotalAccountsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for TotalAccountsTableHandle<'ctx> {
    type InsertCallbackId = TotalAccountsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TotalAccountsInsertCallbackId {
        TotalAccountsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: TotalAccountsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for TotalAccountsTableHandle<'ctx> {
    type DeleteCallbackId = TotalAccountsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> TotalAccountsDeleteCallbackId {
        TotalAccountsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: TotalAccountsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<CountRow>("total_accounts");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<CountRow>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<CountRow>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `CountRow`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait total_accountsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `CountRow`.
    fn total_accounts(&self) -> __sdk::__query_builder::Table<CountRow>;
}

impl total_accountsQueryTableAccess for __sdk::QueryTableAccessor {
    fn total_accounts(&self) -> __sdk::__query_builder::Table<CountRow> {
        __sdk::__query_builder::Table::new("total_accounts")
    }
}
