// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.3.0 (commit 755267c4218d91927e457feb403a2c6fcfa2d92a).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UnregisterAdminIdentityArgs {
    pub identity_hex: String,
}

impl From<UnregisterAdminIdentityArgs> for super::Reducer {
    fn from(args: UnregisterAdminIdentityArgs) -> Self {
        Self::UnregisterAdminIdentity {
            identity_hex: args.identity_hex,
        }
    }
}

impl __sdk::InModule for UnregisterAdminIdentityArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `unregister_admin_identity`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait unregister_admin_identity {
    /// Request that the remote module invoke the reducer `unregister_admin_identity` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`unregister_admin_identity::unregister_admin_identity_then`] to run a callback after the reducer completes.
    fn unregister_admin_identity(&self, identity_hex: String) -> __sdk::Result<()> {
        self.unregister_admin_identity_then(identity_hex, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `unregister_admin_identity` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn unregister_admin_identity_then(
        &self,
        identity_hex: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl unregister_admin_identity for super::RemoteReducers {
    fn unregister_admin_identity_then(
        &self,
        identity_hex: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UnregisterAdminIdentityArgs { identity_hex }, callback)
    }
}
