// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.6.0 (commit e9bdb3e5f2cd8e90bb43b33f5fa54a6a9df04d27).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UpdateMessageCategoryArgs {
    pub category_id: u64,
    pub name: String,
    pub description: String,
}

impl From<UpdateMessageCategoryArgs> for super::Reducer {
    fn from(args: UpdateMessageCategoryArgs) -> Self {
        Self::UpdateMessageCategory {
            category_id: args.category_id,
            name: args.name,
            description: args.description,
        }
    }
}

impl __sdk::InModule for UpdateMessageCategoryArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `update_message_category`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait update_message_category {
    /// Request that the remote module invoke the reducer `update_message_category` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`update_message_category::update_message_category_then`] to run a callback after the reducer completes.
    fn update_message_category(
        &self,
        category_id: u64,
        name: String,
        description: String,
    ) -> __sdk::Result<()> {
        self.update_message_category_then(category_id, name, description, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `update_message_category` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn update_message_category_then(
        &self,
        category_id: u64,
        name: String,
        description: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl update_message_category for super::RemoteReducers {
    fn update_message_category_then(
        &self,
        category_id: u64,
        name: String,
        description: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            UpdateMessageCategoryArgs {
                category_id,
                name,
                description,
            },
            callback,
        )
    }
}
