// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 2.10.0 (commit 73145eb5edc0e8f29cf67afc35a274ab307e0f1c).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct UserUnsubscribeByTokenArgs {
    pub token: String,
}

impl From<UserUnsubscribeByTokenArgs> for super::Reducer {
    fn from(args: UserUnsubscribeByTokenArgs) -> Self {
        Self::UserUnsubscribeByToken { token: args.token }
    }
}

impl __sdk::InModule for UserUnsubscribeByTokenArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `user_unsubscribe_by_token`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait user_unsubscribe_by_token {
    /// Request that the remote module invoke the reducer `user_unsubscribe_by_token` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    ///
    /// Use [`user_unsubscribe_by_token::user_unsubscribe_by_token_then`] to run a callback after the reducer completes.
    fn user_unsubscribe_by_token(&self, token: String) -> __sdk::Result<()> {
        self.user_unsubscribe_by_token_then(token, |_, _| {})
    }

    /// Request that the remote module invoke the reducer `user_unsubscribe_by_token` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn user_unsubscribe_by_token_then(
        &self,
        token: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl user_unsubscribe_by_token for super::RemoteReducers {
    fn user_unsubscribe_by_token_then(
        &self,
        token: String,
        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp
            .invoke_reducer_with_callback(UserUnsubscribeByTokenArgs { token }, callback)
    }
}
