// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::message_category_topic_type::MessageCategoryTopic;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_message_category_topics`.
///
/// Obtain a handle from the [`VisibleMessageCategoryTopicsTableAccess::visible_message_category_topics`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_message_category_topics()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_message_category_topics().on_insert(...)`.
pub struct VisibleMessageCategoryTopicsTableHandle<'ctx> {
    imp: __sdk::TableHandle<MessageCategoryTopic>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_message_category_topics`.
pub struct VisibleMessageCategoryTopicsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleMessageCategoryTopicsTableAccessor {
    type Row = MessageCategoryTopic;
    type Handle<'db> = VisibleMessageCategoryTopicsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_message_category_topics()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_message_category_topics`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleMessageCategoryTopicsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleMessageCategoryTopicsTableHandle`], which mediates access to the table `visible_message_category_topics`.
    fn visible_message_category_topics(&self) -> VisibleMessageCategoryTopicsTableHandle<'_>;
}

impl VisibleMessageCategoryTopicsTableAccess for super::RemoteTables {
    fn visible_message_category_topics(&self) -> VisibleMessageCategoryTopicsTableHandle<'_> {
        VisibleMessageCategoryTopicsTableHandle {
            imp: self
                .imp
                .get_table::<MessageCategoryTopic>("visible_message_category_topics"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleMessageCategoryTopicsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleMessageCategoryTopicsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleMessageCategoryTopicsTableHandle<'ctx> {
    type Row = MessageCategoryTopic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageCategoryTopic> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleMessageCategoryTopicsTableHandle<'ctx> {
    type Row = MessageCategoryTopic;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageCategoryTopic> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleMessageCategoryTopicsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoryTopicsInsertCallbackId {
        VisibleMessageCategoryTopicsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessageCategoryTopicsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleMessageCategoryTopicsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoryTopicsDeleteCallbackId {
        VisibleMessageCategoryTopicsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessageCategoryTopicsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleMessageCategoryTopicsTableHandle<'ctx> {
    type InsertCallbackId = VisibleMessageCategoryTopicsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoryTopicsInsertCallbackId {
        VisibleMessageCategoryTopicsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessageCategoryTopicsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleMessageCategoryTopicsTableHandle<'ctx> {
    type DeleteCallbackId = VisibleMessageCategoryTopicsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoryTopicsDeleteCallbackId {
        VisibleMessageCategoryTopicsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessageCategoryTopicsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleMessageCategoryTopicsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleMessageCategoryTopicsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleMessageCategoryTopicsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoryTopicsUpdateCallbackId {
        VisibleMessageCategoryTopicsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleMessageCategoryTopicsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleMessageCategoryTopicsTableHandle<'ctx> {
    type UpdateCallbackId = VisibleMessageCategoryTopicsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoryTopicsUpdateCallbackId {
        VisibleMessageCategoryTopicsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleMessageCategoryTopicsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `visible_message_category_topics`,
/// which allows point queries on the field of the same name
/// via the [`VisibleMessageCategoryTopicsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_message_category_topics().id().find(...)`.
pub struct VisibleMessageCategoryTopicsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MessageCategoryTopic, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleMessageCategoryTopicsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `visible_message_category_topics`.
    pub fn id(&self) -> VisibleMessageCategoryTopicsIdUnique<'ctx> {
        VisibleMessageCategoryTopicsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleMessageCategoryTopicsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MessageCategoryTopic> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<MessageCategoryTopic>("visible_message_category_topics");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MessageCategoryTopic>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MessageCategoryTopic>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MessageCategoryTopic`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_message_category_topicsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MessageCategoryTopic`.
    fn visible_message_category_topics(
        &self,
    ) -> __sdk::__query_builder::Table<MessageCategoryTopic>;
}

impl visible_message_category_topicsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_message_category_topics(
        &self,
    ) -> __sdk::__query_builder::Table<MessageCategoryTopic> {
        __sdk::__query_builder::Table::new("visible_message_category_topics")
    }
}
