// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::message_topic_category_type::MessageTopicCategory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_message_topic_categories`.
///
/// Obtain a handle from the [`VisibleMessageTopicCategoriesTableAccess::visible_message_topic_categories`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_message_topic_categories()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_message_topic_categories().on_insert(...)`.
pub struct VisibleMessageTopicCategoriesTableHandle<'ctx> {
    imp: __sdk::TableHandle<MessageTopicCategory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_message_topic_categories`.
pub struct VisibleMessageTopicCategoriesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleMessageTopicCategoriesTableAccessor {
    type Row = MessageTopicCategory;
    type Handle<'db> = VisibleMessageTopicCategoriesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_message_topic_categories()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_message_topic_categories`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleMessageTopicCategoriesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleMessageTopicCategoriesTableHandle`], which mediates access to the table `visible_message_topic_categories`.
    fn visible_message_topic_categories(&self) -> VisibleMessageTopicCategoriesTableHandle<'_>;
}

impl VisibleMessageTopicCategoriesTableAccess for super::RemoteTables {
    fn visible_message_topic_categories(&self) -> VisibleMessageTopicCategoriesTableHandle<'_> {
        VisibleMessageTopicCategoriesTableHandle {
            imp: self
                .imp
                .get_table::<MessageTopicCategory>("visible_message_topic_categories"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleMessageTopicCategoriesInsertCallbackId(__sdk::CallbackId);
pub struct VisibleMessageTopicCategoriesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleMessageTopicCategoriesTableHandle<'ctx> {
    type Row = MessageTopicCategory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageTopicCategory> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleMessageTopicCategoriesTableHandle<'ctx> {
    type Row = MessageTopicCategory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageTopicCategory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleMessageTopicCategoriesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicCategoriesInsertCallbackId {
        VisibleMessageTopicCategoriesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessageTopicCategoriesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleMessageTopicCategoriesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicCategoriesDeleteCallbackId {
        VisibleMessageTopicCategoriesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessageTopicCategoriesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleMessageTopicCategoriesTableHandle<'ctx> {
    type InsertCallbackId = VisibleMessageTopicCategoriesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicCategoriesInsertCallbackId {
        VisibleMessageTopicCategoriesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessageTopicCategoriesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleMessageTopicCategoriesTableHandle<'ctx> {
    type DeleteCallbackId = VisibleMessageTopicCategoriesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicCategoriesDeleteCallbackId {
        VisibleMessageTopicCategoriesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessageTopicCategoriesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleMessageTopicCategoriesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleMessageTopicCategoriesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleMessageTopicCategoriesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicCategoriesUpdateCallbackId {
        VisibleMessageTopicCategoriesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleMessageTopicCategoriesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

impl<'ctx> __sdk::WithUpdate for VisibleMessageTopicCategoriesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleMessageTopicCategoriesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleMessageTopicCategoriesUpdateCallbackId {
        VisibleMessageTopicCategoriesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleMessageTopicCategoriesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `id` unique index on the table `visible_message_topic_categories`,
/// which allows point queries on the field of the same name
/// via the [`VisibleMessageTopicCategoriesIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_message_topic_categories().id().find(...)`.
pub struct VisibleMessageTopicCategoriesIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MessageTopicCategory, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleMessageTopicCategoriesTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `visible_message_topic_categories`.
    pub fn id(&self) -> VisibleMessageTopicCategoriesIdUnique<'ctx> {
        VisibleMessageTopicCategoriesIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleMessageTopicCategoriesIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MessageTopicCategory> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table =
        client_cache.get_or_make_table::<MessageTopicCategory>("visible_message_topic_categories");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MessageTopicCategory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MessageTopicCategory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MessageTopicCategory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_message_topic_categoriesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MessageTopicCategory`.
    fn visible_message_topic_categories(
        &self,
    ) -> __sdk::__query_builder::Table<MessageTopicCategory>;
}

impl visible_message_topic_categoriesQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_message_topic_categories(
        &self,
    ) -> __sdk::__query_builder::Table<MessageTopicCategory> {
        __sdk::__query_builder::Table::new("visible_message_topic_categories")
    }
}
