// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::category_visibility_type::CategoryVisibility;
use super::message_category_type::MessageCategory;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_message_categories`.
///
/// Obtain a handle from the [`VisibleMessageCategoriesTableAccess::visible_message_categories`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_message_categories()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_message_categories().on_insert(...)`.
pub struct VisibleMessageCategoriesTableHandle<'ctx> {
    imp: __sdk::TableHandle<MessageCategory>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_message_categories`.
pub struct VisibleMessageCategoriesTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleMessageCategoriesTableAccessor {
    type Row = MessageCategory;
    type Handle<'db> = VisibleMessageCategoriesTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_message_categories()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_message_categories`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleMessageCategoriesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleMessageCategoriesTableHandle`], which mediates access to the table `visible_message_categories`.
    fn visible_message_categories(&self) -> VisibleMessageCategoriesTableHandle<'_>;
}

impl VisibleMessageCategoriesTableAccess for super::RemoteTables {
    fn visible_message_categories(&self) -> VisibleMessageCategoriesTableHandle<'_> {
        VisibleMessageCategoriesTableHandle {
            imp: self
                .imp
                .get_table::<MessageCategory>("visible_message_categories"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleMessageCategoriesInsertCallbackId(__sdk::CallbackId);
pub struct VisibleMessageCategoriesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleMessageCategoriesTableHandle<'ctx> {
    type Row = MessageCategory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageCategory> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleMessageCategoriesTableHandle<'ctx> {
    type Row = MessageCategory;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MessageCategory> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleMessageCategoriesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoriesInsertCallbackId {
        VisibleMessageCategoriesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessageCategoriesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleMessageCategoriesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoriesDeleteCallbackId {
        VisibleMessageCategoriesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessageCategoriesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleMessageCategoriesTableHandle<'ctx> {
    type InsertCallbackId = VisibleMessageCategoriesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoriesInsertCallbackId {
        VisibleMessageCategoriesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessageCategoriesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleMessageCategoriesTableHandle<'ctx> {
    type DeleteCallbackId = VisibleMessageCategoriesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessageCategoriesDeleteCallbackId {
        VisibleMessageCategoriesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessageCategoriesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MessageCategory>("visible_message_categories");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<MessageCategory>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MessageCategory>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `MessageCategory`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_message_categoriesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `MessageCategory`.
    fn visible_message_categories(&self) -> __sdk::__query_builder::Table<MessageCategory>;
}

impl visible_message_categoriesQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_message_categories(&self) -> __sdk::__query_builder::Table<MessageCategory> {
        __sdk::__query_builder::Table::new("visible_message_categories")
    }
}
