// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::received_message_type::ReceivedMessage;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_messages`.
///
/// Obtain a handle from the [`VisibleMessagesTableAccess::visible_messages`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_messages()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_messages().on_insert(...)`.
pub struct VisibleMessagesTableHandle<'ctx> {
    imp: __sdk::TableHandle<ReceivedMessage>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_messages`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleMessagesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleMessagesTableHandle`], which mediates access to the table `visible_messages`.
    fn visible_messages(&self) -> VisibleMessagesTableHandle<'_>;
}

impl VisibleMessagesTableAccess for super::RemoteTables {
    fn visible_messages(&self) -> VisibleMessagesTableHandle<'_> {
        VisibleMessagesTableHandle {
            imp: self.imp.get_table::<ReceivedMessage>("visible_messages"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleMessagesInsertCallbackId(__sdk::CallbackId);
pub struct VisibleMessagesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VisibleMessagesTableHandle<'ctx> {
    type Row = ReceivedMessage;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = ReceivedMessage> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleMessagesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessagesInsertCallbackId {
        VisibleMessagesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleMessagesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleMessagesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleMessagesDeleteCallbackId {
        VisibleMessagesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleMessagesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<ReceivedMessage>("visible_messages");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<ReceivedMessage>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<ReceivedMessage>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `ReceivedMessage`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_messagesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `ReceivedMessage`.
    fn visible_messages(&self) -> __sdk::__query_builder::Table<ReceivedMessage>;
}

impl visible_messagesQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_messages(&self) -> __sdk::__query_builder::Table<ReceivedMessage> {
        __sdk::__query_builder::Table::new("visible_messages")
    }
}
