// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::account_email_type::AccountEmail;
use super::email_source_type::EmailSource;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_account_emails`.
///
/// Obtain a handle from the [`VisibleAccountEmailsTableAccess::visible_account_emails`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_account_emails()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_account_emails().on_insert(...)`.
pub struct VisibleAccountEmailsTableHandle<'ctx> {
    imp: __sdk::TableHandle<AccountEmail>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

/// Lifetime-aware accessor marker for the table `visible_account_emails`.
pub struct VisibleAccountEmailsTableAccessor;

impl __sdk::TableAccessor<super::RemoteTables> for VisibleAccountEmailsTableAccessor {
    type Row = AccountEmail;
    type Handle<'db> = VisibleAccountEmailsTableHandle<'db>;

    fn get<'db>(db: &'db super::RemoteTables) -> Self::Handle<'db> {
        db.visible_account_emails()
    }
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_account_emails`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleAccountEmailsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleAccountEmailsTableHandle`], which mediates access to the table `visible_account_emails`.
    fn visible_account_emails(&self) -> VisibleAccountEmailsTableHandle<'_>;
}

impl VisibleAccountEmailsTableAccess for super::RemoteTables {
    fn visible_account_emails(&self) -> VisibleAccountEmailsTableHandle<'_> {
        VisibleAccountEmailsTableHandle {
            imp: self.imp.get_table::<AccountEmail>("visible_account_emails"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleAccountEmailsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleAccountEmailsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableLike for VisibleAccountEmailsTableHandle<'ctx> {
    type Row = AccountEmail;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountEmail> + '_ {
        self.imp.iter()
    }
}

impl<'ctx> __sdk::Table for VisibleAccountEmailsTableHandle<'ctx> {
    type Row = AccountEmail;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AccountEmail> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleAccountEmailsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAccountEmailsInsertCallbackId {
        VisibleAccountEmailsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleAccountEmailsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleAccountEmailsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAccountEmailsDeleteCallbackId {
        VisibleAccountEmailsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleAccountEmailsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

impl<'ctx> __sdk::WithInsert for VisibleAccountEmailsTableHandle<'ctx> {
    type InsertCallbackId = VisibleAccountEmailsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAccountEmailsInsertCallbackId {
        VisibleAccountEmailsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleAccountEmailsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }
}

impl<'ctx> __sdk::WithDelete for VisibleAccountEmailsTableHandle<'ctx> {
    type DeleteCallbackId = VisibleAccountEmailsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAccountEmailsDeleteCallbackId {
        VisibleAccountEmailsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleAccountEmailsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AccountEmail>("visible_account_emails");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AccountEmail>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AccountEmail>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AccountEmail`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_account_emailsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AccountEmail`.
    fn visible_account_emails(&self) -> __sdk::__query_builder::Table<AccountEmail>;
}

impl visible_account_emailsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_account_emails(&self) -> __sdk::__query_builder::Table<AccountEmail> {
        __sdk::__query_builder::Table::new("visible_account_emails")
    }
}
