// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::admin_identity_type::AdminIdentity;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_admin_identities`.
///
/// Obtain a handle from the [`VisibleAdminIdentitiesTableAccess::visible_admin_identities`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_admin_identities()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_admin_identities().on_insert(...)`.
pub struct VisibleAdminIdentitiesTableHandle<'ctx> {
    imp: __sdk::TableHandle<AdminIdentity>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_admin_identities`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleAdminIdentitiesTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleAdminIdentitiesTableHandle`], which mediates access to the table `visible_admin_identities`.
    fn visible_admin_identities(&self) -> VisibleAdminIdentitiesTableHandle<'_>;
}

impl VisibleAdminIdentitiesTableAccess for super::RemoteTables {
    fn visible_admin_identities(&self) -> VisibleAdminIdentitiesTableHandle<'_> {
        VisibleAdminIdentitiesTableHandle {
            imp: self
                .imp
                .get_table::<AdminIdentity>("visible_admin_identities"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleAdminIdentitiesInsertCallbackId(__sdk::CallbackId);
pub struct VisibleAdminIdentitiesDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VisibleAdminIdentitiesTableHandle<'ctx> {
    type Row = AdminIdentity;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = AdminIdentity> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleAdminIdentitiesInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAdminIdentitiesInsertCallbackId {
        VisibleAdminIdentitiesInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleAdminIdentitiesInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleAdminIdentitiesDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleAdminIdentitiesDeleteCallbackId {
        VisibleAdminIdentitiesDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleAdminIdentitiesDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

pub struct VisibleAdminIdentitiesUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for VisibleAdminIdentitiesTableHandle<'ctx> {
    type UpdateCallbackId = VisibleAdminIdentitiesUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> VisibleAdminIdentitiesUpdateCallbackId {
        VisibleAdminIdentitiesUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: VisibleAdminIdentitiesUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

/// Access to the `identity` unique index on the table `visible_admin_identities`,
/// which allows point queries on the field of the same name
/// via the [`VisibleAdminIdentitiesIdentityUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_admin_identities().identity().find(...)`.
pub struct VisibleAdminIdentitiesIdentityUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<AdminIdentity, __sdk::Identity>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> VisibleAdminIdentitiesTableHandle<'ctx> {
    /// Get a handle on the `identity` unique index on the table `visible_admin_identities`.
    pub fn identity(&self) -> VisibleAdminIdentitiesIdentityUnique<'ctx> {
        VisibleAdminIdentitiesIdentityUnique {
            imp: self
                .imp
                .get_unique_constraint::<__sdk::Identity>("identity"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> VisibleAdminIdentitiesIdentityUnique<'ctx> {
    /// Find the subscribed row whose `identity` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &__sdk::Identity) -> Option<AdminIdentity> {
        self.imp.find(col_val)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<AdminIdentity>("visible_admin_identities");
    _table.add_unique_constraint::<__sdk::Identity>("identity", |row| &row.identity);
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<AdminIdentity>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<AdminIdentity>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `AdminIdentity`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_admin_identitiesQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `AdminIdentity`.
    fn visible_admin_identities(&self) -> __sdk::__query_builder::Table<AdminIdentity>;
}

impl visible_admin_identitiesQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_admin_identities(&self) -> __sdk::__query_builder::Table<AdminIdentity> {
        __sdk::__query_builder::Table::new("visible_admin_identities")
    }
}
