// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Account {
    pub id: u64,
    pub identity: __sdk::Identity,
    pub name: String,
    pub email: String,
    pub is_active: bool,
    pub last_synced: __sdk::Timestamp,
}

impl __sdk::InModule for Account {
    type Module = super::RemoteModule;
}

/// Column accessor struct for the table `Account`.
///
/// Provides typed access to columns for query building.
pub struct AccountCols {
    pub id: __sdk::__query_builder::Col<Account, u64>,
    pub identity: __sdk::__query_builder::Col<Account, __sdk::Identity>,
    pub name: __sdk::__query_builder::Col<Account, String>,
    pub email: __sdk::__query_builder::Col<Account, String>,
    pub is_active: __sdk::__query_builder::Col<Account, bool>,
    pub last_synced: __sdk::__query_builder::Col<Account, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasCols for Account {
    type Cols = AccountCols;
    fn cols(table_name: &'static str) -> Self::Cols {
        AccountCols {
            id: __sdk::__query_builder::Col::new(table_name, "id"),
            identity: __sdk::__query_builder::Col::new(table_name, "identity"),
            name: __sdk::__query_builder::Col::new(table_name, "name"),
            email: __sdk::__query_builder::Col::new(table_name, "email"),
            is_active: __sdk::__query_builder::Col::new(table_name, "is_active"),
            last_synced: __sdk::__query_builder::Col::new(table_name, "last_synced"),
        }
    }
}

/// Indexed column accessor struct for the table `Account`.
///
/// Provides typed access to indexed columns for query building.
pub struct AccountIxCols {
    pub id: __sdk::__query_builder::IxCol<Account, u64>,
    pub identity: __sdk::__query_builder::IxCol<Account, __sdk::Identity>,
    pub last_synced: __sdk::__query_builder::IxCol<Account, __sdk::Timestamp>,
}

impl __sdk::__query_builder::HasIxCols for Account {
    type IxCols = AccountIxCols;
    fn ix_cols(table_name: &'static str) -> Self::IxCols {
        AccountIxCols {
            id: __sdk::__query_builder::IxCol::new(table_name, "id"),
            identity: __sdk::__query_builder::IxCol::new(table_name, "identity"),
            last_synced: __sdk::__query_builder::IxCol::new(table_name, "last_synced"),
        }
    }
}

impl __sdk::__query_builder::CanBeLookupTable for Account {}
