// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub(super) struct AddSubscriptionArgs {
    pub subscriber_account_id: u64,
    pub subscriber_email: String,
    pub category_id: u64,
}

impl From<AddSubscriptionArgs> for super::Reducer {
    fn from(args: AddSubscriptionArgs) -> Self {
        Self::AddSubscription {
            subscriber_account_id: args.subscriber_account_id,
            subscriber_email: args.subscriber_email,
            category_id: args.category_id,
        }
    }
}

impl __sdk::InModule for AddSubscriptionArgs {
    type Module = super::RemoteModule;
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the reducer `add_subscription`.
///
/// Implemented for [`super::RemoteReducers`].
pub trait add_subscription {
    /// Request that the remote module invoke the reducer `add_subscription` to run as soon as possible.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and this method provides no way to listen for its completion status.
    /// /// Use [`add_subscription:add_subscription_then`] to run a callback after the reducer completes.
    fn add_subscription(
        &self,
        subscriber_account_id: u64,
        subscriber_email: String,
        category_id: u64,
    ) -> __sdk::Result<()> {
        self.add_subscription_then(
            subscriber_account_id,
            subscriber_email,
            category_id,
            |_, _| {},
        )
    }

    /// Request that the remote module invoke the reducer `add_subscription` to run as soon as possible,
    /// registering `callback` to run when we are notified that the reducer completed.
    ///
    /// This method returns immediately, and errors only if we are unable to send the request.
    /// The reducer will run asynchronously in the future,
    ///  and its status can be observed with the `callback`.
    fn add_subscription_then(
        &self,
        subscriber_account_id: u64,
        subscriber_email: String,
        category_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()>;
}

impl add_subscription for super::RemoteReducers {
    fn add_subscription_then(
        &self,
        subscriber_account_id: u64,
        subscriber_email: String,
        category_id: u64,

        callback: impl FnOnce(&super::ReducerEventContext, Result<Result<(), String>, __sdk::InternalError>)
            + Send
            + 'static,
    ) -> __sdk::Result<()> {
        self.imp.invoke_reducer_with_callback(
            AddSubscriptionArgs {
                subscriber_account_id,
                subscriber_email,
                category_id,
            },
            callback,
        )
    }
}
