// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use super::mta_message_log_type::MtaMessageLog;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `mta_message_log`.
///
/// Obtain a handle from the [`MtaMessageLogTableAccess::mta_message_log`] method on [`super::RemoteTables`],
/// like `ctx.db.mta_message_log()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mta_message_log().on_insert(...)`.
pub struct MtaMessageLogTableHandle<'ctx> {
    imp: __sdk::TableHandle<MtaMessageLog>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `mta_message_log`.
///
/// Implemented for [`super::RemoteTables`].
pub trait MtaMessageLogTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`MtaMessageLogTableHandle`], which mediates access to the table `mta_message_log`.
    fn mta_message_log(&self) -> MtaMessageLogTableHandle<'_>;
}

impl MtaMessageLogTableAccess for super::RemoteTables {
    fn mta_message_log(&self) -> MtaMessageLogTableHandle<'_> {
        MtaMessageLogTableHandle {
            imp: self.imp.get_table::<MtaMessageLog>("mta_message_log"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct MtaMessageLogInsertCallbackId(__sdk::CallbackId);
pub struct MtaMessageLogDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for MtaMessageLogTableHandle<'ctx> {
    type Row = MtaMessageLog;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = MtaMessageLog> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = MtaMessageLogInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MtaMessageLogInsertCallbackId {
        MtaMessageLogInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: MtaMessageLogInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = MtaMessageLogDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> MtaMessageLogDeleteCallbackId {
        MtaMessageLogDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: MtaMessageLogDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<MtaMessageLog>("mta_message_log");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct MtaMessageLogUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for MtaMessageLogTableHandle<'ctx> {
    type UpdateCallbackId = MtaMessageLogUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> MtaMessageLogUpdateCallbackId {
        MtaMessageLogUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: MtaMessageLogUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<MtaMessageLog>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<MtaMessageLog>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `mta_message_log`,
/// which allows point queries on the field of the same name
/// via the [`MtaMessageLogIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.mta_message_log().id().find(...)`.
pub struct MtaMessageLogIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<MtaMessageLog, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> MtaMessageLogTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `mta_message_log`.
    pub fn id(&self) -> MtaMessageLogIdUnique<'ctx> {
        MtaMessageLogIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> MtaMessageLogIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<MtaMessageLog> {
        self.imp.find(col_val)
    }
}
