// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.3.0 (commit ).

#![allow(unused, clippy::all)]
use super::subscription_type::Subscription;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `subscriptions`.
///
/// Obtain a handle from the [`SubscriptionsTableAccess::subscriptions`] method on [`super::RemoteTables`],
/// like `ctx.db.subscriptions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscriptions().on_insert(...)`.
pub struct SubscriptionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Subscription>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `subscriptions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait SubscriptionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`SubscriptionsTableHandle`], which mediates access to the table `subscriptions`.
    fn subscriptions(&self) -> SubscriptionsTableHandle<'_>;
}

impl SubscriptionsTableAccess for super::RemoteTables {
    fn subscriptions(&self) -> SubscriptionsTableHandle<'_> {
        SubscriptionsTableHandle {
            imp: self.imp.get_table::<Subscription>("subscriptions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct SubscriptionsInsertCallbackId(__sdk::CallbackId);
pub struct SubscriptionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for SubscriptionsTableHandle<'ctx> {
    type Row = Subscription;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Subscription> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = SubscriptionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionsInsertCallbackId {
        SubscriptionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: SubscriptionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = SubscriptionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> SubscriptionsDeleteCallbackId {
        SubscriptionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: SubscriptionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Subscription>("subscriptions");
    _table.add_unique_constraint::<u64>("id", |row| &row.id);
}
pub struct SubscriptionsUpdateCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::TableWithPrimaryKey for SubscriptionsTableHandle<'ctx> {
    type UpdateCallbackId = SubscriptionsUpdateCallbackId;

    fn on_update(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row, &Self::Row) + Send + 'static,
    ) -> SubscriptionsUpdateCallbackId {
        SubscriptionsUpdateCallbackId(self.imp.on_update(Box::new(callback)))
    }

    fn remove_on_update(&self, callback: SubscriptionsUpdateCallbackId) {
        self.imp.remove_on_update(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::TableUpdate<__ws::BsatnFormat>,
) -> __sdk::Result<__sdk::TableUpdate<Subscription>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Subscription>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

/// Access to the `id` unique index on the table `subscriptions`,
/// which allows point queries on the field of the same name
/// via the [`SubscriptionsIdUnique::find`] method.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.subscriptions().id().find(...)`.
pub struct SubscriptionsIdUnique<'ctx> {
    imp: __sdk::UniqueConstraintHandle<Subscription, u64>,
    phantom: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

impl<'ctx> SubscriptionsTableHandle<'ctx> {
    /// Get a handle on the `id` unique index on the table `subscriptions`.
    pub fn id(&self) -> SubscriptionsIdUnique<'ctx> {
        SubscriptionsIdUnique {
            imp: self.imp.get_unique_constraint::<u64>("id"),
            phantom: std::marker::PhantomData,
        }
    }
}

impl<'ctx> SubscriptionsIdUnique<'ctx> {
    /// Find the subscribed row whose `id` column value is equal to `col_val`,
    /// if such a row is present in the client cache.
    pub fn find(&self, col_val: &u64) -> Option<Subscription> {
        self.imp.find(col_val)
    }
}
