// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

// This was generated using spacetimedb cli version 1.2.0 (commit ).

#![allow(unused, clippy::all)]
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

#[derive(__lib::ser::Serialize, __lib::de::Deserialize, Clone, PartialEq, Debug)]
#[sats(crate = __lib)]
pub struct Subscription {
    pub id: u64,
    pub subscriber_account_id: u64,
    pub subscriber_email: String,
    pub category_id: u64,
    pub subscribed_at: i64,
    pub active: bool,
}

impl __sdk::InModule for Subscription {
    type Module = super::RemoteModule;
}
