// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

#![allow(unused, clippy::all)]
use super::subscription_type::Subscription;
use spacetimedb_sdk::__codegen::{self as __sdk, __lib, __sats, __ws};

/// Table handle for the table `visible_subscriptions`.
///
/// Obtain a handle from the [`VisibleSubscriptionsTableAccess::visible_subscriptions`] method on [`super::RemoteTables`],
/// like `ctx.db.visible_subscriptions()`.
///
/// Users are encouraged not to explicitly reference this type,
/// but to directly chain method calls,
/// like `ctx.db.visible_subscriptions().on_insert(...)`.
pub struct VisibleSubscriptionsTableHandle<'ctx> {
    imp: __sdk::TableHandle<Subscription>,
    ctx: std::marker::PhantomData<&'ctx super::RemoteTables>,
}

#[allow(non_camel_case_types)]
/// Extension trait for access to the table `visible_subscriptions`.
///
/// Implemented for [`super::RemoteTables`].
pub trait VisibleSubscriptionsTableAccess {
    #[allow(non_snake_case)]
    /// Obtain a [`VisibleSubscriptionsTableHandle`], which mediates access to the table `visible_subscriptions`.
    fn visible_subscriptions(&self) -> VisibleSubscriptionsTableHandle<'_>;
}

impl VisibleSubscriptionsTableAccess for super::RemoteTables {
    fn visible_subscriptions(&self) -> VisibleSubscriptionsTableHandle<'_> {
        VisibleSubscriptionsTableHandle {
            imp: self.imp.get_table::<Subscription>("visible_subscriptions"),
            ctx: std::marker::PhantomData,
        }
    }
}

pub struct VisibleSubscriptionsInsertCallbackId(__sdk::CallbackId);
pub struct VisibleSubscriptionsDeleteCallbackId(__sdk::CallbackId);

impl<'ctx> __sdk::Table for VisibleSubscriptionsTableHandle<'ctx> {
    type Row = Subscription;
    type EventContext = super::EventContext;

    fn count(&self) -> u64 {
        self.imp.count()
    }
    fn iter(&self) -> impl Iterator<Item = Subscription> + '_ {
        self.imp.iter()
    }

    type InsertCallbackId = VisibleSubscriptionsInsertCallbackId;

    fn on_insert(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleSubscriptionsInsertCallbackId {
        VisibleSubscriptionsInsertCallbackId(self.imp.on_insert(Box::new(callback)))
    }

    fn remove_on_insert(&self, callback: VisibleSubscriptionsInsertCallbackId) {
        self.imp.remove_on_insert(callback.0)
    }

    type DeleteCallbackId = VisibleSubscriptionsDeleteCallbackId;

    fn on_delete(
        &self,
        callback: impl FnMut(&Self::EventContext, &Self::Row) + Send + 'static,
    ) -> VisibleSubscriptionsDeleteCallbackId {
        VisibleSubscriptionsDeleteCallbackId(self.imp.on_delete(Box::new(callback)))
    }

    fn remove_on_delete(&self, callback: VisibleSubscriptionsDeleteCallbackId) {
        self.imp.remove_on_delete(callback.0)
    }
}

#[doc(hidden)]
pub(super) fn register_table(client_cache: &mut __sdk::ClientCache<super::RemoteModule>) {
    let _table = client_cache.get_or_make_table::<Subscription>("visible_subscriptions");
}

#[doc(hidden)]
pub(super) fn parse_table_update(
    raw_updates: __ws::v2::TableUpdate,
) -> __sdk::Result<__sdk::TableUpdate<Subscription>> {
    __sdk::TableUpdate::parse_table_update(raw_updates).map_err(|e| {
        __sdk::InternalError::failed_parse("TableUpdate<Subscription>", "TableUpdate")
            .with_cause(e)
            .into()
    })
}

#[allow(non_camel_case_types)]
/// Extension trait for query builder access to the table `Subscription`.
///
/// Implemented for [`__sdk::QueryTableAccessor`].
pub trait visible_subscriptionsQueryTableAccess {
    #[allow(non_snake_case)]
    /// Get a query builder for the table `Subscription`.
    fn visible_subscriptions(&self) -> __sdk::__query_builder::Table<Subscription>;
}

impl visible_subscriptionsQueryTableAccess for __sdk::QueryTableAccessor {
    fn visible_subscriptions(&self) -> __sdk::__query_builder::Table<Subscription> {
        __sdk::__query_builder::Table::new("visible_subscriptions")
    }
}
