[book]
authors = ["Franz Dietrich"]
language = "en"
src = "src"
title = "Kommunikationszentrum setup and maintenance"

[output.html]
additional-css = ["theme/custom.css"]

[preprocessor.d2]
layout = "dagre"
inline = false
