direction: down


external: "External Systems" {
direction: down
django: "Django\nOAuth Provider\nPort 8000" {
  style.fill: lightyellow
}

stalwart: "Stalwart MTA\nPorts Submission: 465, 587\nPort Jmap: 443/8093" {
  style.fill: lightgray
}
}

core: "Core Kommunikationszentrum" {
  admin_ui: "Admin Web UI\n(Dioxus)\nPort 8080" {
  style.fill: lightblue
}
spacetimedb: "SpacetimeDB\n(Database + HTTP Routes)\nPort 3000" {
  style.fill: lightcoral
}
sender: "Sender Service\n(Email Sending)" {
  style.fill: lightgreen
  }
}




core.admin_ui <-> core.spacetimedb: "WebSocket\nSubscriptions" {
  style.stroke: blue
}
core.admin_ui -> external.django: "OAuth\nLogin" {
  style.stroke: orange
}
external.stalwart -> core.spacetimedb: "MTA\nHooks (HTTP)\nInbound Email" {
  style.stroke: red
}
external.django -> core.spacetimedb: "User Sync (HTTP)\nvia admin command\nand via django signals" {
  style.stroke: green
}
core.sender -> external.stalwart: "Send Email"
core.sender -> core.spacetimedb: "Store Email Status"
core.sender <-> core.spacetimedb: "Process Email (Fanout)"
core.spacetimedb -> core.sender: "Load memberships"
